### ISSUE TITLE
OCM. federated user gets a server crash when uploading files via tus

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#10285]
```
Web UI 10.3.0
Ocis: 6.5.0
```

Steps: 
`Given using server "LOCAL"`
`And "Alice" has generated invitation`
`And using server "REMOTE"`
`And "Brian" has accepted invitation`
`And using server "LOCAL"`
`And "Alice" shares folder f1 to "Brian"`
`When "Brian" tries to upload file to shared folder f1 via TUS`

Actual: 
server crash: 
```
panic: runtime error: index out of range [0] with length 0
2024-10-11 09:29:30 
2024-10-11 09:29:30 goroutine 602 [running]:
2024-10-11 09:29:30 github.com/cs3org/reva/v2/pkg/rhttp/datatx/manager/tus.(*manager).Handler.func1()
2024-10-11 09:29:30     github.com/cs3org/reva/v2@v2.25.0/pkg/rhttp/datatx/manager/tus/tus.go:139 +0x31c
2024-10-11 09:29:30 created by github.com/cs3org/reva/v2/pkg/rhttp/datatx/manager/tus.(*manager).Handler in goroutine 577
2024-10-11 09:29:30     github.com/cs3org/reva/v2@v2.25.0/pkg/rhttp/datatx/manager/tus/tus.go:130 +0x354
2024-10-11 09:29:31 2024/10/11 07:29:31 INFO memory is not limited, skipping package=github.com/KimMachineGun/automemlimit/memlimit
2024-10-11 09:29:31 2024/10/11 07:29:31 Could not create config: config file already exists, use --force-overwrite to overwrite or --diff to show diff
2024-10-11 09:29:32 2024/10/11 07:29:32 INFO memory is not limited, skipping package=github.com/KimMachineGun/automemlimit/memlimit
```

Alice can see uploaded file. After restarting Brian instance -> file is exist 
Expected: no server crash

CC @2403905

**Comment by micbar** [comment]
@2403905 Done? Please close then 😄
