### ISSUE TITLE
Fresh 6.0.5 Deployment with HELM Chart can not be accessed via Web UI

### ISSUE THREAD

**Issue by marvinkurock** [owncloud/ocis#10361]
## Describe the bug
When installing the version 6.0.5 via HELM in our openshift kubrnetes cluster, the deployment succeeds, but when accessing the web ui we get an error:
config.json missing or invalid.

The deployment itself seems to work. We can access ocis via the client application.

## Steps to reproduce
1. Deploy ocis 6.0.5 via helm
2. try to access the web ui

## Expected behavior
Getting to the login screen and to ocis web ui.
We did not configure any config.json manually. We only used the helm values to configure the deployment.

The message on the web ui:
![Screenshot 2024-10-21 111810](https://github.com/user-attachments/assets/b63b0928-8939-472c-81df-68614d9982d1)

The error code in the web browser console:
`index.html-6PXeMCgV.mjs:32 
 ZodError: [
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "mime-types",
      0,
      "app_providers",
      0,
      "icon"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "mime-types",
      1,
      "app_providers",
      0,
      "icon"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "mime-types",
      2,
      "app_providers",
      0,
      "icon"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "mime-types",
      3,
      "app_providers",
      0,
      "icon"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "mime-types",
      4,
      "app_providers",
      0,
      "icon"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "mime-types",
      5,
      "app_providers",
      0,
      "icon"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "mime-types",
      6,
      "app_providers",
      0,
      "icon"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "mime-types",
      7,
      "app_providers",
      0,
      "icon"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "mime-types",
      8,
      "app_providers",
      0,
      "icon"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "mime-types",
      9,
      "app_providers",
      0,
      "icon"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "mime-types",
      10,
      "app_providers",
      0,
      "icon"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "mime-types",
      11,
      "app_providers",
      0,
      "icon"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "mime-types",
      12,
      "app_providers",
      0,
      "icon"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "mime-types",
      13,
      "app_providers",
      0,
      "icon"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "mime-types",
      14,
      "app_providers",
      0,
      "icon"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "mime-types",
      15,
      "app_providers",
      0,
      "icon"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "mime-types",
      16,
      "app_providers",
      0,
      "icon"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "mime-types",
      17,
      "app_providers",
      0,
      "icon"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "mime-types",
      18,
      "app_providers",
      0,
      "icon"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "mime-types",
      19,
      "app_providers",
      0,
      "icon"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "mime-types",
      20,
      "app_providers",
      0,
      "icon"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "mime-types",
      21,
      "app_providers",
      0,
      "icon"
    ],
    "message": "Required"
  },
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "undefined",
    "path": [
      "mime-types",
      22,
      "app_providers",
      0,
      "icon"
    ],
    "message": "Required"
  }
]
    at get error (PortalTarget.vue_vue…A--6rH.mjs:56:71084)
    at Ft.parse (PortalTarget.vue_vue…A--6rH.mjs:56:73321)
    at Ss.processResponse (index.html-6PXeMCgV.mjs:6:21536)
    at Ss.internalRequest (index.html-6PXeMCgV.mjs:6:21675)
    at async Wi.loadData (index.html-6PXeMCgV.mjs:6:13838)
    at async Object.s$ [as bootstrapApp] (index.html-6PXeMCgV.mjs:32:34505)
﻿

`

**Comment by wkloucek** [comment]
Looks like `iconURI` needs to be set, see eg. https://github.com/owncloud/ocis-charts/blob/1a4a31fdf6ba5a5c5305a57dd6112fc3d9a0e38d/deployments/ocis-office/helmfile.yaml#L155

Seems like oC Web nowadays requires an icon in the /app/list entries. I'm not sure if this was intended or if icons should be still optional
