### ISSUE TITLE
All oCIS services rely on /tmp to be a read-write filesystem because of govips

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#10378]
## Describe the bug
Run oCIS 6.6 in Kubernetes, eg via https://github.com/owncloud/ocis-charts/pull/778

## Steps to reproduce
1. install it
2. look at the pods
3.

## Expected behavior
Pods are running

## Actual behavior
Pods are crashing, eg:

```
+ nats-799bb65f6d-z7mwf › nats
nats-799bb65f6d-z7mwf nats panic: Couldn't create temporary directory: mkdir /tmp/govips-2656736891: read-only file system
nats-799bb65f6d-z7mwf nats 
nats-799bb65f6d-z7mwf nats goroutine 1 [running]:
nats-799bb65f6d-z7mwf nats github.com/davidbyttow/govips/v2/vips.temporaryDirectoryOrPanic()
nats-799bb65f6d-z7mwf nats 	github.com/davidbyttow/govips/v2@v2.15.0/vips/icc_profiles.go:671 +0x89
nats-799bb65f6d-z7mwf nats github.com/davidbyttow/govips/v2/vips.init()
nats-799bb65f6d-z7mwf nats 	github.com/davidbyttow/govips/v2@v2.15.0/vips/icc_profiles.go:647 +0x17
- nats-799bb65f6d-z7mwf › nats
```

If you switch to the external nats example, you're gonna see the same message on all other oCIS pods, too:

```
+ proxy-6c7d4846cc-p45zh › proxy
proxy-6c7d4846cc-p45zh proxy panic: Couldn't create temporary directory: mkdir /tmp/govips-3013908145: read-only file system
proxy-6c7d4846cc-p45zh proxy 
proxy-6c7d4846cc-p45zh proxy goroutine 1 [running]:
proxy-6c7d4846cc-p45zh proxy github.com/davidbyttow/govips/v2/vips.temporaryDirectoryOrPanic()
proxy-6c7d4846cc-p45zh proxy 	github.com/davidbyttow/govips/v2@v2.15.0/vips/icc_profiles.go:671 +0x89
proxy-6c7d4846cc-p45zh proxy github.com/davidbyttow/govips/v2/vips.init()
proxy-6c7d4846cc-p45zh proxy 	github.com/davidbyttow/govips/v2@v2.15.0/vips/icc_profiles.go:647 +0x17
- proxy-6c7d4846cc-p45zh › proxy
```

## Setup

oCIS 6.6 in Kubernetes

**Comment by wkloucek** [comment]
Probably similar to https://github.com/owncloud/ocis/issues/4894

**Comment by rhafer** [comment]
This should fix it: https://github.com/davidbyttow/govips/pull/442

**Comment by wkloucek** [comment]
Ok, for now I'll look adding volumes to /tmp everywhere

**Comment by wkloucek** [comment]
workaround in https://github.com/owncloud/ocis-charts/pull/778/commits/531a08d96108347682a09a123ef2884704f38851

**Comment by wkloucek** [comment]
Will be fixed when we pull in https://github.com/davidbyttow/govips/releases/tag/v2.16.0
