### ISSUE TITLE
Share a Project Space via OCIS API make the Webclient hung

### ISSUE THREAD

**Issue by OMarohn** [owncloud/ocis#10707]
## Describe the bug
After i share a Project Space with an User via ocis grpc api, the Web UI get non functional an Stuck.
The grpc Call returns no error. 
In the Console i get following error:

Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com
License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
Copyright 2023 Fonticons, Inc.

index.html-UdMqTK0y.mjs:5  ownCloud Web UI 10.0.0 
index.html-UdMqTK0y.mjs:5  Infinite Scale 6.2.0 Community 
PortalTarget.vue_vue_type_script_lang-CAy3JYul.mjs:13 TypeError: Cannot read properties of undefined (reading '0')
    at Sb (PortalTarget.vue_vue_type_script_lang-CAy3JYul.mjs:22:58990)
    at index.html-UdMqTK0y.mjs:5:10038
    at Array.map (<anonymous>)
    at Object.listMyDrives (index.html-UdMqTK0y.mjs:5:10031)
    at async Jf (PortalTarget.vue_vue_type_script_lang-CAy3JYul.mjs:48:78389)
    at async Promise.all (index 1)
    at async Proxy.loadSpaces (PortalTarget.vue_vue_type_script_lang-CAy3JYul.mjs:48:79609)
    at async HI.Z.immediate (index.html-UdMqTK0y.mjs:5:204160)  

## Steps to reproduce
1. call the API as follows
	shareResp, err := a.gateway.CreateShare(a.context,
		&v1beta13.CreateShareRequest{
			ResourceInfo: space.GetRootInfo(),
			Grant: &v1beta13.ShareGrant{
				Grantee: &providerv1beta1.Grantee{
					Type: providerv1beta1.GranteeType_GRANTEE_TYPE_USER,
					Id:   &providerv1beta1.Grantee_UserId{UserId: usrresp.GetUsers()[0].Id},
				},
				Permissions: &v1beta13.SharePermissions{
					Permissions: &providerv1beta1.ResourcePermissions{
						AddGrant:             true,
						GetPath:              true,
						GetQuota:             true,
						InitiateFileDownload: true,
						ListContainer:        true,
						ListRecycle:          true,
						Stat:                 true}, 
				},
			},
		},
	)

3. Try to login in the OCIS Web Client

## Expected behavior
If the grpc Request get invalid Parameters, for example Grants. The Request should return an error. 
The UI shoud ignore, or log invalid Data.

## Actual behavior
The Web Client hang

**Comment by OMarohn** [comment]
If i delete the Space (Purge: T ) the Web Client works again.
Exists an Permission Set that will work?
