### ISSUE TITLE
Panic on server start

### ISSUE THREAD

**Issue by labkode** [owncloud/ocis#1173]
I've build on latest master, commit: 7f19d24bac16968fcef28e0055e1912a69ff6b18

```
# ./bin/ocis server
2021-01-05T10:09:47+01:00 INF runtime ready on localhost:10666 service=runtime
panic: runtime error: invalid memory address or nil pointer dereference
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x18400cd]

goroutine 1 [running]:
net/http.(*onceCloseListener).close(...)
        /usr/local/go/src/net/http/server.go:3371
sync.(*Once).doSlow(0xc0002b0100, 0xc000c614e0)
        /usr/local/go/src/sync/once.go:66 +0xec
sync.(*Once).Do(...)
        /usr/local/go/src/sync/once.go:57
net/http.(*onceCloseListener).Close(0xc0002b00f0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:3367 +0x78
panic(0x33b0c60, 0x501af70)
        /usr/local/go/src/runtime/panic.go:969 +0x1b9
net/http.(*onceCloseListener).Accept(0xc0002b00f0, 0xc000124010, 0x3360260, 0x501ae90, 0x37eeac0)
        <autogenerated>:1 +0x32
net/http.(*Server).Serve(0xc000e2e000, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/server.go:2937 +0x266
net/http.Serve(...)
        /usr/local/go/src/net/http/server.go:2498
github.com/refs/pman/pkg/service.Start(0x8, 0x3903448)
        /root/go/pkg/mod/github.com/refs/pman@v0.0.0-20201214134707-9ce4dcebbbf8/pkg/service/service.go:123 +0x372
github.com/owncloud/ocis/ocis/pkg/runtime.(*Runtime).Start(0xc000592ca0, 0xc000592ca0, 0x0)
        /root/ocis/ocis/pkg/runtime/runtime.go:83 +0x45
github.com/owncloud/ocis/ocis/pkg/command.Server.func2(0xc000c43200, 0x0, 0x0)
        /root/ocis/ocis/pkg/command/server.go:36 +0x74
github.com/micro/cli/v2.(*Command).Run(0xc0001aa120, 0xc000c42d80, 0x0, 0x0)
        /root/go/pkg/mod/github.com/micro/cli/v2@v2.1.2/command.go:161 +0x4ed
github.com/micro/cli/v2.(*App).RunContext(0xc000683080, 0x3c0f060, 0xc000124010, 0xc00012c000, 0x2, 0x2, 0x0, 0x0)
        /root/go/pkg/mod/github.com/micro/cli/v2@v2.1.2/app.go:303 +0x81f
github.com/micro/cli/v2.(*App).Run(...)
        /root/go/pkg/mod/github.com/micro/cli/v2@v2.1.2/app.go:210
github.com/owncloud/ocis/ocis/pkg/command.Execute(0xffffffff, 0xc00010e058)
        /root/ocis/ocis/pkg/command/root.go:70 +0x526
main.main()
        /root/ocis/ocis/cmd/ocis/main.go:10 +0x25
```

@refs @butonic

**Comment by refs** [comment]
runtime issue. Tracked [here](https://github.com/refs/pman/issues/9)
