### ISSUE TITLE
Random Phoenix test failure on deleting all except few files at once

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis#1245]
- [ ] reenable test

Might or might not be related to stray data:

```
1) Scenario: Delete all except for a few files at once (attempt 2) # tests/acceptance/features/webUIDeleteFilesFolders/deleteFilesFolders.feature:77
   ✔ Before # tests/acceptance/setup.js:28
   ✔ Before # tests/acceptance/setup.js:32
   ✔ Before # tests/acceptance/setup.js:36
   ✔ Before # tests/acceptance/setup.js:46
   ✔ Before # tests/acceptance/setup.js:68
   ✔ Before # tests/acceptance/setup.js:75
   ✔ Before # tests/acceptance/stepDefinitions/filesContext.js:18
   ✔ Before # tests/acceptance/stepDefinitions/generalContext.js:228
   ✔ Before # tests/acceptance/stepDefinitions/generalContext.js:267
   ✔ Given user "user1" has been created with default attributes # tests/acceptance/stepDefinitions/provisioningContext.js:147
   ✔ And user "user1" has logged in using the webUI # tests/acceptance/stepDefinitions/loginContext.js:67
   ✔ And the user has browsed to the files page # tests/acceptance/stepDefinitions/filesContext.js:82
   ✔ When the user marks all files for batch action using the webUI # tests/acceptance/stepDefinitions/filesContext.js:477
   ✔ And the user unmarks these files for batch action using the webUI # tests/acceptance/stepDefinitions/filesContext.js:494
       | name          |
       | lorem.txt     |
       | simple-folder |
   ✔ And the user batch deletes the marked files using the webUI # tests/acceptance/stepDefinitions/filesContext.js:481
   ✔ Then as "user1" file "lorem.txt" should exist # tests/acceptance/stepDefinitions/webdavContext.js:46
   ✔ And as "user1" folder "simple-folder" should exist # tests/acceptance/stepDefinitions/webdavContext.js:46
   ✔ And folder "simple-folder" should be listed on the webUI # tests/acceptance/stepDefinitions/filesContext.js:395
   ✔ And file "lorem.txt" should be listed on the webUI # tests/acceptance/stepDefinitions/filesContext.js:391
   ✔ But as "user1" file "data.zip" should not exist # tests/acceptance/stepDefinitions/webdavContext.js:35
   ✔ And file "data.zip" should not be listed on the webUI # tests/acceptance/stepDefinitions/filesContext.js:412
   ✖ And there should be 2 files/folders listed on the webUI # tests/acceptance/stepDefinitions/filesContext.js:736
       Error while running "equal" command: Failed [equal]: (3 == 2) - expected "2" but got: "3" (undefinedms)
           at _callee40$ (/srv/app/phoenix/tests/acceptance/stepDefinitions/filesContext.js:738:24)
           at processTicksAndRejections (internal/process/task_queues.js:86:5)
   - And no message should be displayed on the webUI # tests/acceptance/stepDefinitions/generalContext.js:120
   ✔ After # tests/acceptance/stepDefinitions/provisioningContext.js:221
   ✔ After # tests/acceptance/stepDefinitions/generalContext.js:272
   ✔ After # tests/acceptance/stepDefinitions/generalContext.js:252
   ✔ After # tests/acceptance/setup.js:110
   ✔ After # tests/acceptance/setup.js:106
   ✔ After # tests/acceptance/setup.js:102
   ✔ After # tests/acceptance/setup.js:95
   ✔ After # tests/acceptance/setup.js:86
   ✔ After # tests/acceptance/setup.js:54
```

**Comment by kobergj** [comment]
Since there was no actions since 3 years I consider this fixed. Closing.
