### ISSUE TITLE
Conflict / overwrite issues with TUS

### ISSUE THREAD

**Issue by PVince81** [owncloud/ocis#1294]
Run the following acceptance tests with Phoenix:

- tests/acceptance/features/webUIUpload/uploadEdgecases.feature:123
~~tests/acceptance/features/webUIUpload/upload.feature:84~~

The failure seems to be related to how the new TUS based implementation handles conflicts or overwrites.

**Comment by micbar** [comment]
fixed by #2280

**Comment by phil-davis** [comment]
https://drone.owncloud.com/owncloud/ocis/9644/50/9
`webUIUpload/upload.feature:94` failed.
```
  Scenario: conflict with a big file (when chunking is implemented this upload should be chunked) # features/webUIUpload/upload.feature:94
- Connecting to selenium on port 4444...
ℹ Connected to selenium on port 4444 (431ms).
  Using: chrome (94.0.4606.61) on Linux platform.
    Given user "Alice" has been created with default attributes and without skeleton files in the server
    And user "Alice" has created folder "simple-folder" in the server
    And user "Alice" has uploaded file with content "initial content" to "lorem.txt" in the server
    And user "Alice" has uploaded file with content "initial content" to "simple-folder/lorem.txt" in the server
    And user "Alice" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 941 milliseconds.
√ Element <input[autocomplete="kopano-account username"]> was not present after 114 milliseconds.
√ Element <.app-content> was visible after 776 milliseconds.
    Given a file with the size of "30000000" bytes and the name "big-video.mp4" has been created locally in the middleware
    When the user renames file "lorem.txt" to "big-video.mp4" using the webUI
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"b6543720ba07329cf2388f8d814a6ce9","status":0,"value":[]}
       at Proxy.isSideBarOpen (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.isSideBarOpenForResource (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:52:24)
       at Proxy.openSideBar (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:246:28)
       at Proxy.openFileActionsMenu (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:232:18)
       at Proxy.renameFile (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:88:18)
       at World.<anonymous> (/srv/app/web/tests/acceptance/stepDefinitions/filesContext.js:256:53)
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"b6543720ba07329cf2388f8d814a6ce9","status":0,"value":[]}
       at Proxy.isSideBarOpen (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.closeSidebarIfOpen (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:13:24)
       at Proxy.openSideBar (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:252:24)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.openFileActionsMenu (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:232:7)
       at Proxy.renameFile (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:88:7)
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"b6543720ba07329cf2388f8d814a6ce9","status":0,"value":[]}
       at Proxy.isSideBarOpen (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.closeSidebarIfOpen (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:13:24)
       at Proxy.waitForFileVisible (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:338:24)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.clickRow (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:265:7)
       at Proxy.openSideBar (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:255:7)
       at Proxy.openFileActionsMenu (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:232:7)
       at Proxy.renameFile (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:88:7)
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='lorem.txt' or @data-test-resource-path='/lorem.txt')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was present after 21 milliseconds.
√ Element <.files-table .oc-tbody-tr> was present after 19 milliseconds.
waiting for 500ms ...
   NoSuchElementError: An error occurred while running .isVisible() command on <//div[contains(@id, "files-sidebar")]//*[contains(@class, "is-active-sub-panel")]//button[contains(@class, "header__back")]>: 
   {"sessionId":"b6543720ba07329cf2388f8d814a6ce9","status":0,"value":[]}
       at Proxy.activatePanel (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:80:20)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
       at Proxy.openFileActionsMenu (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:233:7)
       at Proxy.renameFile (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:88:7)
Timeout waiting for Ajax calls to start
waiting for 500ms ...
√ Element <//*[@id="sidebar-panel-actions-item"]//*[contains(@class, "sidebar-panel__body-content")]> was present after 9 milliseconds.
√ Element <.oc-modal> was visible after 35 milliseconds.
waiting for 500ms ...
√ Element <.oc-modal> was not present after 102 milliseconds.
    And the user reloads the current page of the webUI
    And the user uploads a created file "big-video.mp4" with overwrite using the webUI
    Then file "big-video.mp4" should be listed on the webUI
√ Element <#new-file-menu-btn:enabled> was visible after 816 milliseconds.
√ Element <#files-file-upload-button> was visible after 65 milliseconds.
waiting for 500ms ...
   NoSuchElementError: An error occurred while running .isVisible() command on <//*[@id="files-sidebar"]>: 
   {"sessionId":"b6543720ba07329cf2388f8d814a6ce9","status":0,"value":[]}
       at Proxy.isSideBarOpen (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:30:18)
       at Proxy.closeSidebarIfOpen (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/appSideBar.js:13:24)
       at Proxy.waitForFileVisible (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:338:24)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
√ Element <.oc-modal> was not present after 21 milliseconds.
Timeout waiting for Ajax calls to start
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='big-video.mp4' or @data-test-resource-path='/big-video.mp4') and @data-test-resource-type='file']/ancestor::tr[contains(@class, "oc-tbody-tr")]> was present after 24 milliseconds.
√ Element <.files-table .oc-tbody-tr> was present after 11 milliseconds.
    And as "Alice" the content of "big-video.mp4" in the server should be the same as the content of local file "big-video.mp4"
    ✖ failed
      Error: AssertionError [ERR_ASSERTION]: asserting content of local file "/uploads/big-video.mp4"
          at assertContentOfLocalFileIs (/usr/src/app/src/stepDefinitions/filesContext.js:151:17)
          at StepDef.action (/usr/src/app/src/stepDefinitions/filesContext.js:133:5)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async /usr/src/app/src/app.js:66:7
          at /srv/app/web/tests/acceptance/stepDefinitions/middlewareContext.js:38:15
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Maybe this fail is related?

**Comment by saw-jan** [comment]
File overwrite works and covered in webUI scenario: https://github.com/owncloud/web/blob/752ab3a836d4c44edefa925981aa759bcd11da38/tests/e2e/cucumber/features/smoke/upload.feature#L20-L22

And `webUIUpload/upload.feature:95` also works
```feature
Scenario: conflict with a big file (when chunking is implemented this upload should be chunked)
```

So, closing this
