### ISSUE TITLE
NPE when passing config file via PROXY_CONFIG in single binary mode

### ISSUE THREAD

**Issue by IljaN** [owncloud/ocis#139]
It appears that the config can't be loaded:

```
ERR policy reva is not configured service=proxy
2020-03-12 21:23:00.592395 I | http: panic serving [::1]:51584: runtime error: invalid memory address or nil pointer dereference
goroutine 105 [running]:
net/http.(*conn).serve.func1(0xc001558320)
	/usr/local/Cellar/go/1.13.4/libexec/src/net/http/server.go:1767 +0x139
panic(0x55738e0, 0x6e291d0)
	/usr/local/Cellar/go/1.13.4/libexec/src/runtime/panic.go:679 +0x1b2
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc000c87ef0, 0x5c3fce0, 0xc000162460, 0xc00033d200)
	/usr/local/Cellar/go/1.13.4/libexec/src/net/http/httputil/reverseproxy.go:206 +0x144
github.com/owncloud/ocis-proxy/pkg/proxy.(*MultiHostReverseProxy).ServeHTTP(0xc000c87ef0, 0x5c3fce0, 0xc000162460, 0xc00033d200)
	/Users/mbarz/go/pkg/mod/github.com/owncloud/ocis-proxy@v0.0.0-20200310100127-5a38d286e52c/pkg/proxy/proxy.go:119 +0x37e
net/http.serverHandler.ServeHTTP(0xc0001620e0, 0x5c3fce0, 0xc000162460, 0xc00033d200)
	/usr/local/Cellar/go/1.13.4/libexec/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc001558320, 0x5c49060, 0xc0014d6980)
	/usr/local/Cellar/go/1.13.4/libexec/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/Cellar/go/1.13.4/libexec/src/net/http/server.go:2927 +0x38e
```

**Comment by IljaN** [comment]
This func is not called in single-binary mode: https://github.com/owncloud/ocis-proxy/blob/2aba428eb1ef177894fffc9477ad6a091d2cf676/pkg/command/root.go#L16

@refs Shouldn't this logic live inside the server command?

**Comment by IljaN** [comment]
Fix here: https://github.com/owncloud/ocis-proxy/pull/12

- [ ] After the fix is merged ocis-proxy version needs to be updated.
