### ISSUE TITLE
IDP crashes with stacktrace if config file is empty

### ISSUE THREAD

**Issue by IljaN** [owncloud/ocis#1589]
Reported via https://github.com/owncloud/ocis/issues/1395 by @m0nhawk

Following error happens on login if identifier-registration.yaml is empty.
```
ocis              | {"level":"debug","service":"glauth","handler":"ocis","num_entries":1,"binddn":"cn=konnectd,ou=sysusers,dc=example,dc=org","basedn":"dc=example,dc=org","filter":"(objectClass=posixaccount)","src":{"IP":"127.0.0.1","Port":55226,"Zone":""},"time":"2021-01-23T07:23:59.184629558Z","message":"AP: Search OK"}
ocis              | 2021-01-23 07:23:59.185102 I | http: panic serving 127.0.0.1:37418: runtime error: slice bounds out of range [4:3]
ocis              | goroutine 3043 [running]:
ocis              | net/http.(*conn).serve.func1(0xc001abcbe0)
ocis              | 	/usr/local/go/src/net/http/server.go:1801 +0x147
ocis              | panic(0x362f620, 0xc0015af220)
ocis              | 	/usr/local/go/src/runtime/panic.go:975 +0x47a
ocis              | stash.kopano.io/kc/konnect/identity/clients.(*Registry).getDynamicClient(0xc00013ab40, 0xc000f6efe8, 0x3, 0x3, 0x512b620)
ocis              | 	/srv/app/pkg/mod/stash.kopano.io/kc/konnect@v0.33.3/identity/clients/registry.go:321 +0x19c
ocis              | stash.kopano.io/kc/konnect/identity/clients.(*Registry).Get(0xc00013ab40, 0x3bd5a60, 0xc000143da0, 0xc000f6efe8, 0x3, 0x1, 0x1)
ocis              | 	/srv/app/pkg/mod/stash.kopano.io/kc/konnect@v0.33.3/identity/clients/registry.go:315 +0xc5
````
Error happes in:
https://github.com/Kopano-dev/konnect/blob/de5a37b84aa0b52d1d69336c9de48b306ba756a9/identity/clients/registry.go#L321

clientId is web in this case but the expected key is .dyn (4 chars)

**Comment by kobergj** [comment]
Closing as it is probably not relevant any more.
