### ISSUE TITLE
Panic on SIGINT

### ISSUE THREAD

**Issue by IljaN** [owncloud/ocis#1858]
## Describe the bug
Panic when sending SIGINT (Ctrl+C) to ocis server

## Steps to reproduce
1. cd ./ocis/ocis
2. make clean build
3. bin/ocis server
4. Wait until server is ready and logs "stop scrolling" 
5. Ctrl+C

## Expected behavior
Graceful shutdown

## Actual behavior
```
{"level":"warn","service":"proxy","time":"2021-03-25T21:18:53+01:00","message":"No tls certificate provided, using a generated one"}
{"level":"info","service":"storage","pkg":"rgrpc","time":"2021-03-25T21:18:53+01:00","message":"rgrpc: grpc service enabled: usershareprovider"}
{"level":"info","service":"storage","pkg":"rgrpc","time":"2021-03-25T21:18:53+01:00","message":"rgrpc: grpc service enabled: publicshareprovider"}
{"level":"info","service":"storage","pkg":"rgrpc","time":"2021-03-25T21:18:53+01:00","message":"grpc server listening at tcp:0.0.0.0:9150"}
{"level":"info","service":"proxy","transport":"https","addr":"0.0.0.0:9200","time":"2021-03-25T21:18:53+01:00","message":"starting server"}
{"level":"info","service":"proxy","transport":"debug","addr":"0.0.0.0:9205","time":"2021-03-25T21:18:53+01:00","message":"starting server"}
{"level":"info","service":"accounts","transport":"http","addr":"0.0.0.0:9181","time":"2021-03-25T21:18:54+01:00","message":"starting server"}
{"level":"info","service":"accounts","transport":"grpc","addr":"0.0.0.0:9180","time":"2021-03-25T21:18:54+01:00","message":"starting server"}
^Cpanic: send on closed channel

goroutine 52 [running]:
os/signal.process(0x3e35748, 0x5178b10)
	/usr/local/go/src/os/signal/signal.go:245 +0x1a9
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:23 +0x45
created by os/signal.Notify.func1.1
	/usr/local/go/src/os/signal/signal.go:151 +0x45
```
## Setup
Ubuntu/x86, current master.

**Comment by ScharfViktor** [comment]
re-tested with local server oCIS version 1.11.0
Setup: macOS Big Sure v11.4

without panic, I suggest to close @IljaN 

`{"level":"info","service":"storage","pkg":"rgrpc","time":"2021-09-08T10:59:35+02:00","message":"service \"gateway\" correctly closed"}
{"level":"info","service":"storage","pkg":"rgrpc","time":"2021-09-08T10:59:35+02:00","message":"service \"authregistry\" correctly closed"}
{"level":"info","service":"accounts","server":"http","time":"2021-09-08T10:59:35+02:00","message":"shutting down server"}
{"level":"info","service":"accounts","server":"grpc","time":"2Viktors-Air:ocis scharfviktor$ `

**Comment by IljaN** [comment]
Let me retest

**Comment by IljaN** [comment]
Yes is fixed now
```
{"level":"info","service":"storage","pkg":"rgrpc","time":"2021-09-08T11:24:16+02:00","message":"service \"authprovider\" correctly closed"}
{"level":"info","service":"storage","pkg":"grace","time":"2021-09-08T11:24:16+02:00","message":"pid file \"/tmp/revad--1bc90045-fa07-4246-8abb-b60518abffdf.pid\" got removed"}
```
