### ISSUE TITLE
Panic when running 'ocis accounts' without 'ocis settings' configured

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/ocis#2062]
## Describe the bug

I was following the diagram on https://owncloud.dev/ocis/#architecture-overview to split all the components dealing with identity management in oCIS to run them on an independent pod and missed the dependency between `ocis accounts` and `ocis settings` as it does not appear on the diagram. cc/ @wkloucek 

Running any LDAP query on GLAuth returned `ldap_bind: Invalid credentials (49)`.

## Steps to reproduce

1. Run `ocis storage-metadata`, `ocis accounts`, `ocis glauth` and `ocis idp`
2. Query GLAuth by running `ldapsearch -x -H "ldap://ocis-idp.ocis.svc.cluster.local:9125" -D "cn=idp,ou=sysusers,dc=example,dc=org" -w "idp" -b "ou=users,dc=example,dc=org"`

## Expected behavior
No panic thrown in the logs, with a clear message mentioning the dependency on a well-configured `ocis settings` endpoint.

## Actual behavior

<details>
  <summary>
    <b>These panics are logged.</b>
  </summary>
<p>

```console
2021-05-21 07:50:35  file=v3@v3.0.0-20210408173139-0d57213d3f5c/grpc.go:378 level=error panic recovered: runtime error: invalid memory address or nil pointer dereference
2021-05-21 07:50:35  file=v3@v3.0.0-20210408173139-0d57213d3f5c/grpc.go:379 level=error goroutine 135 [running]:
runtime/debug.Stack(0xc00000e720, 0xc000a05502, 0xc000a05500)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/asim/go-micro/plugins/server/grpc/v3.(*grpcServer).processRequest.func1.1(0xc000b67298)
	/go/pkg/mod/github.com/asim/go-micro/plugins/server/grpc/v3@v3.0.0-20210408173139-0d57213d3f5c/grpc.go:379 +0x2a9
panic(0x256ce80, 0x43ccbc0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/owncloud/ocis/ocis-pkg/roles.(*Manager).List(0xc000236b60, 0x3101c48, 0xc0015be030, 0xc000b05340, 0x1, 0x4, 0xc000b66428, 0x113f98d, 0xc0014ce360)
	/drone/src/ocis-pkg/roles/manager.go:49 +0x2c6
github.com/owncloud/ocis/ocis-pkg/roles.(*Manager).FindPermissionByID(0xc000236b60, 0x3101c48, 0xc0015be030, 0xc000b05340, 0x1, 0x4, 0x2a4a02f, 0x24, 0xc282414a3e804ecc)
	/drone/src/ocis-pkg/roles/manager.go:60 +0x85
github.com/owncloud/ocis/accounts/pkg/service/v0.Service.hasSelfManagementPermissions(0xc0009b50a0, 0x19, 0x30e4388, 0xc0009c9a90, 0xff, 0x0, 0x0, 0xc0009d0c00, 0x15, 0x1f4, ...)
	/drone/src/accounts/pkg/service/v0/accounts.go:94 +0xa5
github.com/owncloud/ocis/accounts/pkg/service/v0.Service.ListAccounts(0xc0009b50a0, 0x19, 0x30e4388, 0xc0009c9a90, 0xff, 0x0, 0x0, 0xc0009d0c00, 0x15, 0x1f4, ...)
	/drone/src/accounts/pkg/service/v0/accounts.go:127 +0xb8
github.com/owncloud/ocis/accounts/pkg/proto/v0.(*accountsServiceHandler).ListAccounts(0xc001fe7550, 0x3101c48, 0xc0015be030, 0xc000a39980, 0xc001481680, 0x7faa26ceb108, 0x40)
	/drone/src/accounts/pkg/proto/v0/accounts.pb.micro.go:230 +0x5b
reflect.Value.call(0xc000032080, 0xc000764e48, 0x13, 0x29eebf2, 0x4, 0xc000af91e8, 0x4, 0x4, 0x16, 0x2850d80, ...)
	/usr/local/go/src/reflect/value.go:476 +0x8e7
reflect.Value.Call(0xc000032080, 0xc000764e48, 0x13, 0xc000af91e8, 0x4, 0x4, 0x36, 0xc000af9218, 0x45675e)
	/usr/local/go/src/reflect/value.go:337 +0xb9
github.com/asim/go-micro/plugins/server/grpc/v3.(*grpcServer).processRequest.func1(0x3101c48, 0xc0015be030, 0x311a758, 0xc000a3b280, 0x27e8c60, 0xc001481680, 0x0, 0x0)
	/go/pkg/mod/github.com/asim/go-micro/plugins/server/grpc/v3@v3.0.0-20210408173139-0d57213d3f5c/grpc.go:384 +0x2da
github.com/asim/go-micro/v3/util/wrapper.TraceHandler.func1.1(0x3101c48, 0xc000b6df20, 0x311a758, 0xc000a3b280, 0x27e8c60, 0xc001481680, 0x0, 0x0)
	/go/pkg/mod/github.com/asim/go-micro/v3@v3.5.1-0.20210217182006-0f0ace1a44a9/util/wrapper/wrapper.go:118 +0x1c2
github.com/asim/go-micro/v3/util/wrapper.HandlerStats.func1.1(0x3101c48, 0xc000b6df20, 0x311a758, 0xc000a3b280, 0x27e8c60, 0xc001481680, 0x0, 0x0)
	/go/pkg/mod/github.com/asim/go-micro/v3@v3.5.1-0.20210217182006-0f0ace1a44a9/util/wrapper/wrapper.go:63 +0x83
github.com/asim/go-micro/plugins/wrapper/trace/opencensus/v3.NewHandlerWrapper.func1.1(0x3101c48, 0xc000b6df20, 0x311a758, 0xc000a3b280, 0x27e8c60, 0xc001481680, 0x0, 0x0)
	/go/pkg/mod/github.com/asim/go-micro/plugins/wrapper/trace/opencensus/v3@v3.0.0-20210408173139-0d57213d3f5c/opencensus.go:117 +0x424
github.com/asim/go-micro/plugins/wrapper/monitoring/prometheus/v3.(*wrapper).HandlerFunc.func1(0x3101ba0, 0xc000b05240, 0x311a758, 0xc000a3b280, 0x27e8c60, 0xc001481680, 0x0, 0x0)
	/go/pkg/mod/github.com/asim/go-micro/plugins/wrapper/monitoring/prometheus/v3@v3.0.0-20210408173139-0d57213d3f5c/prometheus.go:264 +0x1c4
github.com/asim/go-micro/plugins/server/grpc/v3.(*grpcServer).processRequest(0xc001ffe000, 0x310f6c8, 0xc0001212c0, 0xc000042980, 0xc001e13ef0, 0xc000239290, 0x16, 0x3101ba0, 0xc000b05240, 0x0, ...)
	/go/pkg/mod/github.com/asim/go-micro/plugins/server/grpc/v3@v3.0.0-20210408173139-0d57213d3f5c/grpc.go:401 +0x7de
github.com/asim/go-micro/plugins/server/grpc/v3.(*grpcServer).handler(0xc001ffe000, 0x0, 0x0, 0x310f6c8, 0xc0001212c0, 0x0, 0x0)
	/go/pkg/mod/github.com/asim/go-micro/plugins/server/grpc/v3@v3.0.0-20210408173139-0d57213d3f5c/grpc.go:320 +0x7a8
google.golang.org/grpc.(*Server).processStreamingRPC(0xc001feba00, 0x311aff8, 0xc000b75380, 0xc000b71000, 0x0, 0xc0000498e0, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1329 +0xcd8
google.golang.org/grpc.(*Server).handleStream(0xc001feba00, 0x311aff8, 0xc000b75380, 0xc000b71000, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1415 +0xb45
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0000ed4b0, 0xc001feba00, 0x311aff8, 0xc000b75380, 0xc000b71000)
	/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xa5

2021-05-21 07:50:35  file=v3@v3.0.0-20210408173139-0d57213d3f5c/grpc.go:378 level=error panic recovered: runtime error: invalid memory address or nil pointer dereference
2021-05-21 07:50:35  file=v3@v3.0.0-20210408173139-0d57213d3f5c/grpc.go:379 level=error goroutine 142 [running]:
runtime/debug.Stack(0xc00000e720, 0xc001476102, 0xc0014761e0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9f
github.com/asim/go-micro/plugins/server/grpc/v3.(*grpcServer).processRequest.func1.1(0xc000b67298)
	/go/pkg/mod/github.com/asim/go-micro/plugins/server/grpc/v3@v3.0.0-20210408173139-0d57213d3f5c/grpc.go:379 +0x2a9
panic(0x256ce80, 0x43ccbc0)
	/usr/local/go/src/runtime/panic.go:965 +0x1b9
github.com/owncloud/ocis/ocis-pkg/roles.(*Manager).List(0xc000236b60, 0x3101c48, 0xc0015bed20, 0xc000b05880, 0x1, 0x4, 0xc000b66428, 0x113f98d, 0xc0014ce540)
	/drone/src/ocis-pkg/roles/manager.go:49 +0x2c6
github.com/owncloud/ocis/ocis-pkg/roles.(*Manager).FindPermissionByID(0xc000236b60, 0x3101c48, 0xc0015bed20, 0xc000b05880, 0x1, 0x4, 0x2a4a02f, 0x24, 0xc282414a3e804ecc)
	/drone/src/ocis-pkg/roles/manager.go:60 +0x85
github.com/owncloud/ocis/accounts/pkg/service/v0.Service.hasSelfManagementPermissions(0xc0009b50a0, 0x19, 0x30e4388, 0xc0009c9a90, 0xff, 0x0, 0x0, 0xc0009d0c00, 0x15, 0x1f4, ...)
	/drone/src/accounts/pkg/service/v0/accounts.go:94 +0xa5
github.com/owncloud/ocis/accounts/pkg/service/v0.Service.ListAccounts(0xc0009b50a0, 0x19, 0x30e4388, 0xc0009c9a90, 0xff, 0x0, 0x0, 0xc0009d0c00, 0x15, 0x1f4, ...)
	/drone/src/accounts/pkg/service/v0/accounts.go:127 +0xb8
github.com/owncloud/ocis/accounts/pkg/proto/v0.(*accountsServiceHandler).ListAccounts(0xc001fe7550, 0x3101c48, 0xc0015bed20, 0xc0015e80c0, 0xc0015ea000, 0x7faa26ceb108, 0x40)
	/drone/src/accounts/pkg/proto/v0/accounts.pb.micro.go:230 +0x5b
reflect.Value.call(0xc000032080, 0xc000764e48, 0x13, 0x29eebf2, 0x4, 0xc000af91e8, 0x4, 0x4, 0x16, 0x2850d80, ...)
	/usr/local/go/src/reflect/value.go:476 +0x8e7
reflect.Value.Call(0xc000032080, 0xc000764e48, 0x13, 0xc000af91e8, 0x4, 0x4, 0x36, 0xc000af9218, 0x45675e)
	/usr/local/go/src/reflect/value.go:337 +0xb9
github.com/asim/go-micro/plugins/server/grpc/v3.(*grpcServer).processRequest.func1(0x3101c48, 0xc0015bed20, 0x311a758, 0xc000a3b800, 0x27e8c60, 0xc0015ea000, 0x0, 0x0)
	/go/pkg/mod/github.com/asim/go-micro/plugins/server/grpc/v3@v3.0.0-20210408173139-0d57213d3f5c/grpc.go:384 +0x2da
github.com/asim/go-micro/v3/util/wrapper.TraceHandler.func1.1(0x3101c48, 0xc0015bec30, 0x311a758, 0xc000a3b800, 0x27e8c60, 0xc0015ea000, 0x0, 0x0)
	/go/pkg/mod/github.com/asim/go-micro/v3@v3.5.1-0.20210217182006-0f0ace1a44a9/util/wrapper/wrapper.go:118 +0x1c2
github.com/asim/go-micro/v3/util/wrapper.HandlerStats.func1.1(0x3101c48, 0xc0015bec30, 0x311a758, 0xc000a3b800, 0x27e8c60, 0xc0015ea000, 0x0, 0x0)
	/go/pkg/mod/github.com/asim/go-micro/v3@v3.5.1-0.20210217182006-0f0ace1a44a9/util/wrapper/wrapper.go:63 +0x83
github.com/asim/go-micro/plugins/wrapper/trace/opencensus/v3.NewHandlerWrapper.func1.1(0x3101c48, 0xc0015bec30, 0x311a758, 0xc000a3b800, 0x27e8c60, 0xc0015ea000, 0x0, 0x0)
	/go/pkg/mod/github.com/asim/go-micro/plugins/wrapper/trace/opencensus/v3@v3.0.0-20210408173139-0d57213d3f5c/opencensus.go:117 +0x424
github.com/asim/go-micro/plugins/wrapper/monitoring/prometheus/v3.(*wrapper).HandlerFunc.func1(0x3101ba0, 0xc000b05780, 0x311a758, 0xc000a3b800, 0x27e8c60, 0xc0015ea000, 0x0, 0x0)
	/go/pkg/mod/github.com/asim/go-micro/plugins/wrapper/monitoring/prometheus/v3@v3.0.0-20210408173139-0d57213d3f5c/prometheus.go:264 +0x1c4
github.com/asim/go-micro/plugins/server/grpc/v3.(*grpcServer).processRequest(0xc001ffe000, 0x310f6c8, 0xc000121380, 0xc000042980, 0xc001e13ef0, 0xc000239428, 0x16, 0x3101ba0, 0xc000b05780, 0x0, ...)
	/go/pkg/mod/github.com/asim/go-micro/plugins/server/grpc/v3@v3.0.0-20210408173139-0d57213d3f5c/grpc.go:401 +0x7de
github.com/asim/go-micro/plugins/server/grpc/v3.(*grpcServer).handler(0xc001ffe000, 0x0, 0x0, 0x310f6c8, 0xc000121380, 0x0, 0x0)
	/go/pkg/mod/github.com/asim/go-micro/plugins/server/grpc/v3@v3.0.0-20210408173139-0d57213d3f5c/grpc.go:320 +0x7a8
google.golang.org/grpc.(*Server).processStreamingRPC(0xc001feba00, 0x311aff8, 0xc000c2d680, 0xc000b71700, 0x0, 0xc0000498e0, 0x0, 0x0, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1329 +0xcd8
google.golang.org/grpc.(*Server).handleStream(0xc001feba00, 0x311aff8, 0xc000c2d680, 0xc000b71700, 0x0)
	/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1415 +0xb45
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc001419bd0, 0xc001feba00, 0x311aff8, 0xc000c2d680, 0xc000b71700)
	/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xa5
```

</p>
</details>

## Setup

I'm using the `owncloud/ocis:latest` docker image with the following running processes:

```
/ # ps aux
PID   USER     TIME  COMMAND
    1 root      0:00 {entrypoint} /bin/sh /entrypoint
    7 root      0:43 ocis storage-metadata
   11 root      0:32 ocis idp
   12 root      0:27 ocis glauth
   13 root      0:00 ocis accounts
   14 root      0:00 sleep infinite
  ```

## Additional context

```
# ocis version
+----------+-------------------+--------------------------------------------------------------------+
| Version  |      Address      |                                 Id                                 |
+----------+-------------------+--------------------------------------------------------------------+
|          | 0.0.0.0:9215      | com.owncloud.storage.metadata-9748f1a9-ab56-4fe1-af10-f109d256d1f7 |
| 34a8ed38 | 10.100.27.82:9180 | com.owncloud.api.accounts-4f80a2b3-38aa-4882-a0d8-7f03e1bf7947     |
| 34a8ed38 | 10.100.27.82:9181 | com.owncloud.web.accounts-4f80a2b3-38aa-4882-a0d8-7f03e1bf7947     |
| 34a8ed38 | 10.100.27.82:9130 | com.owncloud.web.idp-26b71684-4dd5-4dcd-a506-6dbdd3875dad          |
+----------+-------------------+--------------------------------------------------------------------+
```

**Comment by wkloucek** [comment]
we removed the accounts servers, therefore no longer an issue
