### ISSUE TITLE
today my proxy died ...

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#2422]
```
proxy_1                  | 2021-08-19T19:05:03Z INF access-log bytes=299 duration=84.289891 method=PUT path="/remote.php/dav/files/jfd/Bilder/Poco X3//VID_20210815_124101.mp4" proto=HTTP/1.1 remote-addr=192.168.1.1 request=1859904b-941d-4511-bca6-8d836dc4963f service=proxy status=503
proxy_1                  | 2021/08/19 19:05:03 httputil: ReverseProxy read error during body copy: invalid byte in chunk length
proxy_1                  | panic: runtime error: invalid memory address or nil pointer dereference
proxy_1                  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x64337e]
proxy_1                  | 
proxy_1                  | goroutine 79576 [running]:
proxy_1                  | bufio.(*Reader).Read(0xc0019c93e0, 0xc001768000, 0x8000, 0x8000, 0xc0027c2d18, 0xc001768000, 0xc0027c2d00)
proxy_1                  |      /usr/local/go/src/bufio/bufio.go:213 +0x11e
proxy_1                  | io.(*LimitedReader).Read(0xc0026fdae8, 0xc001768000, 0x8000, 0x8000, 0x8000, 0x2000, 0x0)
proxy_1                  |      /usr/local/go/src/io/io.go:473 +0x63
proxy_1                  | net/http.(*body).readLocked(0xc001692180, 0xc001768000, 0x8000, 0x8000, 0x8000, 0x2000, 0x0)
proxy_1                  |      /usr/local/go/src/net/http/transfer.go:842 +0x5f
proxy_1                  | net/http.(*body).Read(0xc001692180, 0xc001768000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
proxy_1                  |      /usr/local/go/src/net/http/transfer.go:834 +0xf9
proxy_1                  | io.(*LimitedReader).Read(0xc00000fcb0, 0xc001768000, 0x8000, 0x8000, 0x2000, 0x0, 0x0)
proxy_1                  |      /usr/local/go/src/io/io.go:473 +0x63
proxy_1                  | io.copyBuffer(0x322af80, 0xc00027cc10, 0x3227900, 0xc00000fcb0, 0xc001768000, 0x8000, 0x8000, 0xa, 0xc00000fcb0, 0x8f1c93)
proxy_1                  |      /usr/local/go/src/io/io.go:423 +0x12c
proxy_1                  | io.Copy(...)
proxy_1                  |      /usr/local/go/src/io/io.go:382
proxy_1                  | net.genericReadFrom(0x3227c00, 0xc0019ca330, 0x3227900, 0xc00000fcb0, 0x0, 0x0, 0x26eb400)
proxy_1                  |      /usr/local/go/src/net/net.go:655 +0x9a
proxy_1                  | net.(*TCPConn).readFrom(0xc0019ca330, 0x3227900, 0xc00000fcb0, 0xc0005ec9e0, 0xc0005ec9d8, 0x40db4a)
proxy_1                  |      /usr/local/go/src/net/tcpsock_posix.go:54 +0xe9
proxy_1                  | net.(*TCPConn).ReadFrom(0xc0019ca330, 0x3227900, 0xc00000fcb0, 0x7f353494fef8, 0xc0019ca330, 0x1)
proxy_1                  |      /usr/local/go/src/net/tcpsock.go:103 +0x4d
proxy_1                  | io.copyBuffer(0x3227c00, 0xc0019ca330, 0x3227900, 0xc00000fcb0, 0x0, 0x0, 0x0, 0x28484e0, 0xc0005ecb01, 0x7f353494fed8)
proxy_1                  |      /usr/local/go/src/io/io.go:409 +0x357
proxy_1                  | io.Copy(...)
proxy_1                  |      /usr/local/go/src/io/io.go:382
proxy_1                  | net/http.persistConnWriter.ReadFrom(0xc00298d320, 0x3227900, 0xc00000fcb0, 0x7f353494fed8, 0xc00298d320, 0x320000c0027c2d01)
proxy_1                  |      /usr/local/go/src/net/http/transport.go:1768 +0x85
proxy_1                  | bufio.(*Writer).ReadFrom(0xc0008b7440, 0x3227900, 0xc00000fcb0, 0x7f353494feb8, 0xc0008b7440, 0x7f353494fe01)
proxy_1                  |      /usr/local/go/src/bufio/bufio.go:730 +0x37e
proxy_1                  | io.copyBuffer(0x3221480, 0xc0008b7440, 0x3227900, 0xc00000fcb0, 0x0, 0x0, 0x0, 0xc0005ecc38, 0x410378, 0x18)
proxy_1                  |      /usr/local/go/src/io/io.go:409 +0x357
proxy_1                  | io.Copy(...)
proxy_1                  |      /usr/local/go/src/io/io.go:382
proxy_1                  | net/http.(*transferWriter).doBodyCopy(0xc000c4f720, 0x3221480, 0xc0008b7440, 0x3227900, 0xc00000fcb0, 0x91e912, 0xc0019ca330, 0xc001767000)
proxy_1                  |      /usr/local/go/src/net/http/transfer.go:409 +0x6a
proxy_1                  | net/http.(*transferWriter).writeBody(0xc000c4f720, 0x3221480, 0xc0008b7440, 0x0, 0x0)
proxy_1                  |      /usr/local/go/src/net/http/transfer.go:367 +0x825
proxy_1                  | net/http.(*Request).write(0xc001905500, 0x3221480, 0xc0008b7440, 0x0, 0x0, 0x0, 0x0, 0x0)
proxy_1                  |      /usr/local/go/src/net/http/request.go:697 +0x7c6
proxy_1                  | net/http.(*persistConn).writeLoop(0xc00298d320)
proxy_1                  |      /usr/local/go/src/net/http/transport.go:2385 +0x1a7
proxy_1                  | created by net/http.(*Transport).dialConn
proxy_1                  |      /usr/local/go/src/net/http/transport.go:1744 +0xc9c
```

hmmm
```
grep VID_20210815_124101.mp4 owncloud.log
{"reqId":"dffce365-98c7-46c6-9f15-348c3c47f43d","level":2,"time":"2021-08-19T19:15:47+00:00","remoteAddr":"172.20.0.27","user":"jfd","app":"core","method":"PUT","url":"\/remote.php\/dav\/files\/jfd\/Bilder\/Poco%20X3\/\/VID_20210815_124101.mp4","message":"ignoring lock release with type 1 for files\/7fdae9de3cfadee9f53fa34ec1c17bd6. Lock hasn't been acquired before"}
{"reqId":"dffce365-98c7-46c6-9f15-348c3c47f43d","level":2,"time":"2021-08-19T19:15:47+00:00","remoteAddr":"172.20.0.27","user":"jfd","app":"core","method":"PUT","url":"\/remote.php\/dav\/files\/jfd\/Bilder\/Poco%20X3\/\/VID_20210815_124101.mp4","message":"ignoring lock release with type 1 for files\/bddc107925ae4ee0537bc0edb1dc0f8e. Lock hasn't been acquired before"}
{"reqId":"dffce365-98c7-46c6-9f15-348c3c47f43d","level":2,"time":"2021-08-19T19:15:47+00:00","remoteAddr":"172.20.0.27","user":"jfd","app":"core","method":"PUT","url":"\/remote.php\/dav\/files\/jfd\/Bilder\/Poco%20X3\/\/VID_20210815_124101.mp4","message":"ignoring lock release with type 1 for files\/38ce38188f7cd2172e2a323b483dee25. Lock hasn't been acquired before"}
```
hm, the time is off by 10min ... but there are no other entries for `VID_20210815_124101.mp4`. Maybe the request id has more entries?
```
grep dffce365-98c7-46c6-9f15-348c3c47f43d owncloud.log
{"reqId":"dffce365-98c7-46c6-9f15-348c3c47f43d","level":2,"time":"2021-08-19T19:15:47+00:00","remoteAddr":"172.20.0.27","user":"jfd","app":"core","method":"PUT","url":"\/remote.php\/dav\/files\/jfd\/Bilder\/Poco%20X3\/\/VID_20210815_124101.mp4","message":"ignoring lock release with type 1 for files\/7fdae9de3cfadee9f53fa34ec1c17bd6. Lock hasn't been acquired before"}
{"reqId":"dffce365-98c7-46c6-9f15-348c3c47f43d","level":2,"time":"2021-08-19T19:15:47+00:00","remoteAddr":"172.20.0.27","user":"jfd","app":"core","method":"PUT","url":"\/remote.php\/dav\/files\/jfd\/Bilder\/Poco%20X3\/\/VID_20210815_124101.mp4","message":"ignoring lock release with type 1 for files\/bddc107925ae4ee0537bc0edb1dc0f8e. Lock hasn't been acquired before"}
{"reqId":"dffce365-98c7-46c6-9f15-348c3c47f43d","level":2,"time":"2021-08-19T19:15:47+00:00","remoteAddr":"172.20.0.27","user":"jfd","app":"core","method":"PUT","url":"\/remote.php\/dav\/files\/jfd\/Bilder\/Poco%20X3\/\/VID_20210815_124101.mp4","message":"ignoring lock release with type 1 for files\/38ce38188f7cd2172e2a323b483dee25. Lock hasn't been acquired before"}
```

nothing ... hmm that time offset is weird. I do have time running away in containers... sometimes my oidc tokens are no longer valid. Checking the date in the containers right now ... all in sync ... ah no the time difference was on my win10 desktop and the docker containers running on it. So, unrelated to this PUT request, as it was sentd from my mobile...

**Comment by pascalwengerter** [comment]
@butonic has this happened again/is it reproducable? If not, please close or update the issue with a reproduction guide and definition of done :)
