### ISSUE TITLE
publicLinkCreate.feature:172 is failing

### ISSUE THREAD

**Issue by phil-davis** [owncloud/ocis#3581]
See PR #3580 that ran full-ci.

https://drone.owncloud.com/owncloud/ocis/10881/48/9
```
runsh: Total unexpected failed scenarios throughout the test run:
webUISharingPublicBasic/publicLinkCreate.feature:172
```

```
  Scenario: User can create a public link via quick action # features/webUISharingPublicBasic/publicLinkCreate.feature:172
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (209ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given user "Alice" has been created with default attributes and without skeleton files in the server
    Given user "Alice" has created folder "simple-folder" in the server
    And user "Alice" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 549 milliseconds.
√ Element <input[autocomplete="kopano-account username"]> was not present after 69 milliseconds.
√ Element <#files-view> was visible after 471 milliseconds.
    When the user creates a public link via quick action for resource "simple-folder" using the webUI
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='simple-folder' or @data-test-resource-path='/simple-folder')]/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 21 milliseconds.
waiting for 500ms ...
    Then user "Alice" should have a share with these details in the server:
      │ field       │ value             │
      │ share_type  │ public_link       │
      │ uid_owner   │ Alice             │
      │ permissions │ read              │
      │ path        │ /simple-folder    │
      │ name        │ Quick action link │
    ✖ failed
      Error: AssertionError [ERR_ASSERTION]: could not find expected share in "{
        "ocs": {
          "meta": {
            "status": "ok",
            "statuscode": 200,
            "message": "OK"
          },
          "data": []
        }
      }"
          at /usr/src/app/src/helpers/sharingHelper.js:146:16
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at async /usr/src/app/src/app.js:66:7
          at /srv/app/web/tests/acceptance/stepDefinitions/middlewareContext.js:38:15
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

This must have started failing in some "recent" PR that was merged without running full-ci. Needs investigation.

**Comment by phil-davis** [comment]
For Tuesday, QA - I added this to expected-failures in PR #3576 so that CI will be green in oCIS.

Please investigate why it is failing, which PR merged to oCIS this stated failing in. Then we can sort out if there is an oCIS bug to be fixed, or if some change to web (or web tests) is needed.

**Comment by amrita-shrestha** [comment]
When investigating, it was found that creating a public link through the quick action button is not working. So, webUISharingPublicBasic/publicLinkCreate.feature:172 is failing
