### ISSUE TITLE
`webUIFilesDetails/fileDetails.feature:42` and `webUIFilesDetails/fileDetails.feature:57` failed in CI

### ISSUE THREAD

**Issue by Talank** [owncloud/ocis#3651]
https://drone.owncloud.com/owncloud/ocis/11242/35/9

`webUIFilesDetails/fileDetails.feature:42` fails while opening sidebar for a folder
```
Scenario: View different areas of the app-sidebar for a file in favorites page # features/webUIFilesDetails/fileDetails.feature:42
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (323ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given these users have been created with default attributes and without skeleton files in the server:
      │ username │
      │ Alice    │
      │ Brian    │
    And user "Alice" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 903 milliseconds.
√ Element <input[autocomplete="kopano-account username"]> was not present after 287 milliseconds.
√ Element <#files-view> was visible after 500 milliseconds.
    Given user "Alice" has created file "lorem.txt" in the server
    And the user has browsed to the personal page
√ Element <//nav[@id="files-breadcrumb"]//*[(self::a or self::button)]/span[contains(text(),'Personal')]> was visible after 30 milliseconds.
    And user "Alice" has favorited element "lorem.txt" in the server
    And the user has browsed to the favorites page
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was present after 518 milliseconds.
    When the user opens the sidebar for file "lorem.txt" on the webUI
   NoSuchElementError: An error occurred while running .getText() command on <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='lorem.txt' or @data-test-resource-path='/lorem.txt')]>: 
   {"sessionId":"e02df32f93d40c05ed87e600fcd6d712","status":0,"value":[]}
       at Proxy.checkFileName (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:365:18)
       at Proxy.waitForFileVisible (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:353:18)
       at Proxy.clickRow (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:282:18)
       at Proxy.openSideBar (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:272:18)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
    ✖ failed
      AssertionError [ERR_ASSERTION]: An error occurred while running .getText() command on <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='lorem.txt' or @data-test-resource-path='/lorem.txt')]>:
          at Proxy.checkFileName (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:375:16)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at Proxy.waitForFileVisible (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:353:7)
          at Proxy.clickRow (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:282:7)
          at Proxy.openSideBar (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:272:7)
    Then the app-sidebar should be visible
    - skipped
    And the thumbnail should be visible in the app-sidebar
    - skipped
    And the "details" details panel should be visible
    - skipped
    When the user switches to "actions" panel in details panel using the webUI
    - skipped
    And the "actions" details panel should be visible
    - skipped
    When the user switches to "people" panel in details panel using the webUI
    - skipped
    Then the "people" details panel should be visible
    - skipped
```

And `webUIFilesDetails/fileDetails.feature:57` also fails with same reason.

```
Scenario: View different areas of the app-sidebar for a folder in favorites page # features/webUIFilesDetails/fileDetails.feature:57
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (318ms).
  Using: chrome (94.0.4606.61) on Linux platform.

    Given these users have been created with default attributes and without skeleton files in the server:
      │ username │
      │ Alice    │
      │ Brian    │
    And user "Alice" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 866 milliseconds.
√ Element <input[autocomplete="kopano-account username"]> was not present after 295 milliseconds.
√ Element <#files-view> was visible after 652 milliseconds.
    Given user "Alice" has created folder "simple-folder" in the server
    And the user has browsed to the personal page
√ Element <//nav[@id="files-breadcrumb"]//*[(self::a or self::button)]/span[contains(text(),'Personal')]> was visible after 27 milliseconds.
    And user "Alice" has favorited element "simple-folder" in the server
    And the user has browsed to the favorites page
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was present after 545 milliseconds.
    When the user opens the sidebar for folder "simple-folder" on the webUI
   NoSuchElementError: An error occurred while running .getText() command on <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='simple-folder' or @data-test-resource-path='/simple-folder')]>: 
   {"sessionId":"a0b3f024aa4eae051e81549f8c48f602","status":0,"value":[]}
       at Proxy.checkFileName (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:365:18)
       at Proxy.waitForFileVisible (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:353:18)
       at Proxy.clickRow (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:282:18)
       at Proxy.openSideBar (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:272:18)
       at runMicrotasks (<anonymous>)
       at processTicksAndRejections (internal/process/task_queues.js:95:5)
    ✖ failed
      AssertionError [ERR_ASSERTION]: An error occurred while running .getText() command on <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='simple-folder' or @data-test-resource-path='/simple-folder')]>:
          at Proxy.checkFileName (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:375:16)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:95:5)
          at Proxy.waitForFileVisible (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:353:7)
          at Proxy.clickRow (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:282:7)
          at Proxy.openSideBar (/srv/app/web/tests/acceptance/pageObjects/FilesPageElement/filesList.js:272:7)
    Then the app-sidebar should be visible
    - skipped
    And the thumbnail should be visible in the app-sidebar
    - skipped
    And the "details" details panel should be visible
    - skipped
    When the user switches to "actions" panel in details panel using the webUI
    - skipped
    And the "actions" details panel should be visible
    - skipped
    When the user switches to "people" panel in details panel using the webUI
    - skipped
    Then the "people" details panel should be visible
    - skipped
    When the user switches to "links" panel in details panel using the webUI
    - skipped
    Then the "links" details panel should be visible
    - skipped
```

**Comment by saw-jan** [comment]
Will be resolved by https://github.com/owncloud/ocis/pull/3652

**Comment by saw-jan** [comment]
Tests are expected to fail. added to list in PR #3652
Closing here
