### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#3655]
## Describe the bug
sometimes ocis crashes on startup with
```
ocis/bin/ocis server
fatal error: concurrent map iteration and map write

goroutine 125 [running]:
runtime.throw({0x3d5f037, 0x7fccd8a181d8})
	/usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc001a4a3f8 sp=0xc001a4a3c8 pc=0x13c9af1
runtime.mapiternext(0x37fc940)
```

see https://drone.owncloud.com/owncloud/ocis/11243/35/5
and https://drone.owncloud.com/owncloud/ocis/11246/29/4

**Comment by wkloucek** [comment]
the log actually says (interesting part was missing):

```
goroutine 125 [running]:
runtime.throw({0x3d5f037, 0x7fccd8a181d8})
	/usr/local/go/src/runtime/panic.go:1198 +0x71 fp=0xc001a4a3f8 sp=0xc001a4a3c8 pc=0x13c9af1
runtime.mapiternext(0x37fc940)
	/usr/local/go/src/runtime/map.go:858 +0x4eb fp=0xc001a4a468 sp=0xc001a4a3f8 pc=0x13a25cb
github.com/go-chi/chi/v5.(*node).setEndpoint(0xc0007d8aa0, 0x3ff, {0x5087d80, 0xc0007c8e00}, {0xc0007ae1a0, 0x0})
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/tree.go:346 +0x448 fp=0xc001a4a568 sp=0xc001a4a468 pc=0x18fd768
github.com/go-chi/chi/v5.(*node).InsertRoute(0xc0007ae1ba, 0xc001a4a6a0, {0xc0007ae1a0, 0x1b}, {0x5087d80, 0xc0007c8e00})
	/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/tree.go:161 +0x40d fp=0xc001a4a640 sp=0xc001a4a568 pc=0x18fc9cd
	
```

Therefore it's the chi router race condition, which @C0rby tries to fix in https://github.com/owncloud/ocis/pull/3604

**Comment by C0rby** [comment]
This issue is 2 days old. Sometime during the last 2 days I implemented the workaround in the webdav extension. This issue should no longer happen but the workaround should be replaced with a proper fix.

**Comment by individual-it** [comment]
closing this for now as it didn't happen for a while
