### ISSUE TITLE
decomposedfs requires uuid length space ids

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#3677]
Set `"OCIS_SYSTEM_USER_ID": "some-system-user-id"` and `"OCIS_ADMIN_USER_ID": "some-admin-user-id"`, login will work, but listing the personal space produces a panic:
```
goroutine 1531 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x7a
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x19
github.com/cs3org/reva/v2/internal/grpc/interceptors/recovery.recoveryFunc({0x5f653f8, 0xc004984450}, {0x4a33060, 0xc0043ddd40})
	/home/vscode/repositories/reva/internal/grpc/interceptors/recovery/recovery.go:48 +0x51
github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom({0x5f653f8, 0xc004984450}, {0x4a33060, 0xc0043ddd40}, 0x5c50b40)
	/home/vscode/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/recovery/interceptors.go:61 +0x8f
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1.1()
	/home/vscode/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.3.0/recovery/interceptors.go:29 +0xaa
panic({0x4a33060, 0xc0043ddd40})
	/usr/local/go/src/runtime/panic.go:844 +0x25a
github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs.readSpaceAndNodeFromSpaceTypeLink({0xc00453e840, 0x3a})
	/home/vscode/repositories/reva/pkg/storage/utils/decomposedfs/spaces.go:228 +0x35a
github.com/cs3org/reva/v2/pkg/storage/utils/decomposedfs.(*Decomposedfs).ListStorageSpaces(0xc000f44a00, {0x5f653f8, 0xc004984720}, {0xc000a7e4e0, 0x1, 0x1}, 0x0)
	/home/vscode/repositories/reva/pkg/storage/utils/decomposedfs/spaces.go:341 +0xc3c
github.com/cs3org/reva/v2/internal/grpc/services/storageprovider.(*service).ListStorageSpaces(0xc000f44a50, {0x5f653f8, 0xc004984720}, 0xc00495d080)
	/home/vscode/repositories/reva/internal/grpc/services/storageprovider/storageprovider.go:524 +0x3fc
github.com/cs3org/go-cs3apis/cs3/storage/provider/v1beta1._ProviderAPI_ListStorageSpaces_Handler.func1({0x5f653f8, 0xc004984720}, {0x4a6be80, 0xc00495d080})
	/home/vscode/go/pkg/mod/github.com/cs3org/go-cs3apis@v0.0.0-20220412090512-93c5918b4bde/cs3/storage/provider/v1beta1/provider_api.pb.go:6103 +0xfd
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1({0x5f653f8, 0xc004984720}, {0x4a6be80, 0xc00495d080}, 0xc004964860, 0xc0049689d8)
```
where `/home/vscode/repositories/reva/pkg/storage/utils/decomposedfs/spaces.go:228` expects spaceid and nodeid of uuid length:
```
	if link[0:10] != "....spaces" || link[46:51] != "nodes" {
		return "", "", errtypes.InternalError("malformed link")
	}
```

**Comment by butonic** [comment]
fix in https://github.com/cs3org/reva/pull/2854
