### ISSUE TITLE
ocis SEGFAULT while running  out of disk space

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#388]
testing with owncloud/ocis:1.0.0-beta8 on a 24GB linux partition

* Upload a large file via phoenix web gui
* Repeat, until the file system is full
* The log shows "panic: runtime error: invalid memory address or nil pointer dereference"
* The phoenix web gui shows
* The user is logged out after a few minutes of idle wait.
* The login button no longer responds

```
2020-07-15T13:06:09Z WRN core access token not set pkg=rhttp service=reva traceid=296eb6daea484bb0a10b78e9618d43f5
2020-07-15T13:06:09Z INF unary code=OK end="15/Jul/2020:13:06:09 +0000" from=tcp://127.0.0.1:46866 pkg=rgrpc service=reva start="15/Jul/2020:13:06:09 +0000" time_ns=25786 traceid=296eb6daea484bb0a10b78e9618d43f5 uri=/cs3.auth.registry.v1beta1.RegistryAPI/GetAuthProvider user-agent=grpc-go/1.26.0
2020-07-15T13:06:09Z INF user id:<idp:"https://localhost:9200" opaque_id:"einstein" > username:"einstein" mail:"einstein@example.org" display_name:"Einstein"  authenticated pkg=rgrpc service=reva traceid=296eb6daea484bb0a10b78e9618d43f5
2020-07-15T13:06:09Z INF unary code=OK end="15/Jul/2020:13:06:09 +0000" from=tcp://127.0.0.1:56676 pkg=rgrpc service=reva start="15/Jul/2020:13:06:09 +0000" time_ns=5624290 traceid=296eb6daea484bb0a10b78e9618d43f5 uri=/cs3.auth.provider.v1beta1.ProviderAPI/Authenticate user-agent=grpc-go/1.26.0
2020-07-15T13:06:09Z INF unary code=OK end="15/Jul/2020:13:06:09 +0000" from=tcp://127.0.0.1:46876 pkg=rgrpc service=reva start="15/Jul/2020:13:06:09 +0000" time_ns=102008 traceid=296eb6daea484bb0a10b78e9618d43f5 uri=/cs3.storage.registry.v1beta1.RegistryAPI/GetStorageProvider user-agent=grpc-go/1.26.0
2020-07-15T13:06:09Z INF unary code=OK end="15/Jul/2020:13:06:09 +0000" from=tcp://127.0.0.1:49464 pkg=rgrpc service=reva start="15/Jul/2020:13:06:09 +0000" time_ns=274842 traceid=296eb6daea484bb0a10b78e9618d43f5 uri=/cs3.storage.provider.v1beta1.ProviderAPI/CreateHome user-agent=grpc-go/1.26.0
2020-07-15T13:06:09Z INF unary code=OK end="15/Jul/2020:13:06:09 +0000" from=tcp://127.0.0.1:46982 pkg=rgrpc service=reva start="15/Jul/2020:13:06:09 +0000" time_ns=7953084 traceid=296eb6daea484bb0a10b78e9618d43f5 uri=/cs3.gateway.v1beta1.GatewayAPI/Authenticate user-agent=grpc-go/1.26.0
2020-07-15T13:06:09Z INF core access token generated pkg=rhttp service=reva traceid=296eb6daea484bb0a10b78e9618d43f5
[tusd] 2020/07/15 13:06:09 event="RequestIncoming" method="PATCH" path="/5d5948ef-99af-4c37-af88-f42fecbc3b29" requestId="" 
2020-07-15T13:06:09Z INF tusd routing: path=/5d5948ef-99af-4c37-af88-f42fecbc3b29 pkg=rhttp service=reva traceid=296eb6daea484bb0a10b78e9618d43f5
[tusd] 2020/07/15 13:06:09 event="ChunkWriteStart" id="5d5948ef-99af-4c37-af88-f42fecbc3b29" maxSize="4249645056" offset="2010353664" 
[tusd] 2020/07/15 13:06:09 event="ResponseOutgoing" status="500" method="PATCH" path="/5d5948ef-99af-4c37-af88-f42fecbc3b29" error="write /var/tmp/reva/data/einstein/uploads/5d5948ef-99af-4c37-af88-f42fecbc3b29: no space left on device" requestId="" 
2020-07-15T13:06:09Z ERR http end="15/Jul/2020:13:06:09 +0000" host=127.0.0.1 method=PATCH pkg=rhttp proto=HTTP/1.1 service=reva size=104 start="15/Jul/2020:13:06:09 +0000" status=500 time_ns=8900549 traceid=296eb6daea484bb0a10b78e9618d43f5 uri=/data/5d5948ef-99af-4c37-af88-f42fecbc3b29 url=/data/5d5948ef-99af-4c37-af88-f42fecbc3b29
2020-07-15T13:06:09Z ERR http end="15/Jul/2020:13:06:09 +0000" host=127.0.0.1 method=PATCH pkg=rhttp proto=HTTP/1.1 service=reva size=0 start="15/Jul/2020:13:06:09 +0000" status=500 time_ns=22065364 traceid=296eb6daea484bb0a10b78e9618d43f5 uri=/data/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNTk0OTA0NzUzLCJpYXQiOjE1OTQ4MTgzNTMsInRhcmdldCI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTE2NC9kYXRhLzVkNTk0OGVmLTk5YWYtNGMzNy1hZjg4LWY0MmZlY2JjM2IyOSJ9.yeayFDTEb0jfVBsBZhEV0QoT9Y70GGfMPnrP8lNm-do url=/data/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJyZXZhIiwiZXhwIjoxNTk0OTA0NzUzLCJpYXQiOjE1OTQ4MTgzNTMsInRhcmdldCI6Imh0dHA6Ly9sb2NhbGhvc3Q6OTE2NC9kYXRhLzVkNTk0OGVmLTk5YWYtNGMzNy1hZjg4LWY0MmZlY2JjM2IyOSJ9.yeayFDTEb0jfVBsBZhEV0QoT9Y70GGfMPnrP8lNm-do
2020-07-15 13:06:09.214668 I | httputil: ReverseProxy read error during body copy: unexpected EOF
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1524380]

goroutine 1173 [running]:
bufio.(*Reader).Read(0xc001e65680, 0xc002d2a000, 0x8000, 0x8000, 0x8, 0xc001c4d6c8, 0x13f96a8)
	/usr/local/go/src/bufio/bufio.go:212 +0x130
io.(*LimitedReader).Read(0xc002c19e00, 0xc002d2a000, 0x8000, 0x8000, 0x155b51f, 0xc001c84200, 0xc002d2a000)
	/usr/local/go/src/io/io.go:448 +0x63
net/http.(*body).readLocked(0xc000ea1dc0, 0xc002d2a000, 0x8000, 0x8000, 0x1570878, 0xc001c84200, 0xc002d2a000)
	/usr/local/go/src/net/http/transfer.go:847 +0x5f
net/http.(*body).Read(0xc000ea1dc0, 0xc002d2a000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/transfer.go:839 +0x102
io.(*LimitedReader).Read(0xc002c19e20, 0xc002d2a000, 0x8000, 0x8000, 0x4000, 0x0, 0x0)
	/usr/local/go/src/io/io.go:448 +0x63
io.copyBuffer(0x3d1ef20, 0xc001f82ba0, 0x3d1bc40, 0xc002c19e20, 0xc002d2a000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/go/src/io/io.go:402 +0x122
io.Copy(...)
	/usr/local/go/src/io/io.go:364
net.genericReadFrom(0x3d1bee0, 0xc0006660c8, 0x3d1bc40, 0xc002c19e20, 0x0, 0x0, 0x37be600)
	/usr/local/go/src/net/net.go:625 +0x9a
net.(*TCPConn).readFrom(0xc0006660c8, 0x3d1bc40, 0xc002c19e20, 0xc0005f59e8, 0x136ce9a, 0x33a8040)
	/usr/local/go/src/net/tcpsock_posix.go:54 +0xe2
net.(*TCPConn).ReadFrom(0xc0006660c8, 0x3d1bc40, 0xc002c19e20, 0x7f05d5f01268, 0xc0006660c8, 0xc0005f5a01)
	/usr/local/go/src/net/tcpsock.go:103 +0x4d
io.copyBuffer(0x3d1bee0, 0xc0006660c8, 0x3d1bc40, 0xc002c19e20, 0x0, 0x0, 0x0, 0x35272e0, 0xc00005cf01, 0x7f05d5f01248)
	/usr/local/go/src/io/io.go:388 +0x2ed
io.Copy(...)
	/usr/local/go/src/io/io.go:364
net/http.persistConnWriter.ReadFrom(0xc001efed80, 0x3d1bc40, 0xc002c19e20, 0x7f05d5f01248, 0xc001efed80, 0x1)
	/usr/local/go/src/net/http/transport.go:1599 +0x85
bufio.(*Writer).ReadFrom(0xc000ea1b00, 0x3d1bc40, 0xc002c19e20, 0x7f05d5f01228, 0xc000ea1b00, 0x1)
	/usr/local/go/src/bufio/bufio.go:713 +0x34a
io.copyBuffer(0x3d16c60, 0xc000ea1b00, 0x3d1bc40, 0xc002c19e20, 0x0, 0x0, 0x0, 0xc0005f5c38, 0x136f588, 0x20)
	/usr/local/go/src/io/io.go:388 +0x2ed
io.Copy(...)
	/usr/local/go/src/io/io.go:364
net/http.(*transferWriter).doBodyCopy(0xc0001557c0, 0x3d16c60, 0xc000ea1b00, 0x3d1bc40, 0xc002c19e20, 0x33afd40, 0xc0005f5cc0, 0x1785c72)
	/usr/local/go/src/net/http/transfer.go:400 +0x6a
net/http.(*transferWriter).writeBody(0xc0001557c0, 0x3d16c60, 0xc000ea1b00, 0x2, 0x2)
	/usr/local/go/src/net/http/transfer.go:359 +0x6da
net/http.(*Request).write(0xc001c4ef00, 0x3d16c60, 0xc000ea1b00, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/http/request.go:682 +0x6d3
net/http.(*persistConn).writeLoop(0xc001efed80)
	/usr/local/go/src/net/http/transport.go:2207 +0x1c8
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:1575 +0xb23
process [proxy] exited with code: 2
```

Expected behaviour:

* The server handles a disk full condition without violating memory management.
* A crash should be handled by the runtime environment. Processes watched. Restarts attempted? 
   (restarts may fail repeatedly in a disk full condition, but I cannot see any activity in the log after this crash)

**Comment by micbar** [comment]
Expected behaviour is correct IMO.

Needs fixing
