### ISSUE TITLE
Panic on missing group schema ID

### ISSUE THREAD

**Issue by xoxys** [owncloud/ocis#4274]
## Describe the bug

oCIS panics if the `LDAP_GROUP_SCHEMA_ID` is set to an unknown attribute.

```
2022/07/25 08:54:31 http: panic serving 127.0.0.1:58538: runtime error: invalid memory address or nil pointer dereference
goroutine 2179 [running]:
net/http.(*conn).serve.func1()
	net/http/server.go:1825 +0xbf
panic({0x39ba680, 0x528cfc0})
	runtime/panic.go:844 +0x258
github.com/owncloud/ocis/v2/services/graph/pkg/identity.(*LDAP).GetGroups(0xc0008aaa20, {0x3dd8688, 0xc0089dea80}, 0xc0089dfa70)
	github.com/owncloud/ocis/v2/services/graph/pkg/identity/ldap.go:643 +0x84d
github.com/owncloud/ocis/v2/services/graph/pkg/service/v0.Graph.GetGroups({0xc000d68fc0, 0xc055252b40, 0xc0004495f0, {0x3de9348, 0xc0008aaa20}, {0x7fe8073207a0, 0xc0004679b8}, {0x3dd96f0, 0xc001584be0}, 0xc055217200, ...}, ...)
	github.com/owncloud/ocis/v2/services/graph/pkg/service/v0/groups.go:34 +0x1a2
net/http.HandlerFunc.ServeHTTP(0xc00101f960?, {0x7fe8046e5970?, 0xc0089c7040?}, 0xc0089dfa10?)
	net/http/server.go:2084 +0x2f
github.com/owncloud/ocis/v2/services/graph/pkg/middleware.RequireAdmin.func1.1({0x7fe8046e5970, 0xc0089c7040}, 0xc008864e00)
	github.com/owncloud/ocis/v2/services/graph/pkg/middleware/requireadmin.go:46 +0x212
net/http.HandlerFunc.ServeHTTP(0xc000dbbf80?, {0x7fe8046e5970?, 0xc0089c7040?}, 0xc007ae03e0?)
	net/http/server.go:2084 +0x2f
github.com/go-chi/chi/v5.(*ChainHandler).ServeHTTP(0x3989dc0?, {0x7fe8046e5970?, 0xc0089c7040?}, 0x36396c0?)
	github.com/go-chi/chi/v5@v5.0.7/chain.go:31 +0x2c
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc055252fc0, {0x7fe8046e5970, 0xc0089c7040}, 0xc008864e00)
	github.com/go-chi/chi/v5@v5.0.7/mux.go:442 +0x216
net/http.HandlerFunc.ServeHTTP(0x0?, {0x7fe8046e5970?, 0xc0089c7040?}, 0x528bb90?)
	net/http/server.go:2084 +0x2f
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc055252fc0, {0x7fe8046e5970, 0xc0089c7040}, 0xc008864e00)
	github.com/go-chi/chi/v5@v5.0.7/mux.go:71 +0x48d
github.com/go-chi/chi/v5.(*Mux).Mount.func1({0x7fe8046e5970, 0xc0089c7040}, 0xc008864e00)
	github.com/go-chi/chi/v5@v5.0.7/mux.go:314 +0x19c
net/http.HandlerFunc.ServeHTTP(0x3989dc0?, {0x7fe8046e5970?, 0xc0089c7040?}, 0xc008877bb0?)
	net/http/server.go:2084 +0x2f
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc055252cc0, {0x7fe8046e5970, 0xc0089c7040}, 0xc008864e00)
	github.com/go-chi/chi/v5@v5.0.7/mux.go:442 +0x216
net/http.HandlerFunc.ServeHTTP(0x0?, {0x7fe8046e5970?, 0xc0089c7040?}, 0x457210?)
	net/http/server.go:2084 +0x2f
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc055252cc0, {0x7fe8046e5970, 0xc0089c7040}, 0xc008864e00)
	github.com/go-chi/chi/v5@v5.0.7/mux.go:71 +0x48d
github.com/go-chi/chi/v5.(*Mux).Mount.func1({0x7fe8046e5970, 0xc0089c7040}, 0xc008864e00)
	github.com/go-chi/chi/v5@v5.0.7/mux.go:314 +0x19c
net/http.HandlerFunc.ServeHTTP(0x3989dc0?, {0x7fe8046e5970?, 0xc0089c7040?}, 0xc008877ba4?)
	net/http/server.go:2084 +0x2f
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc055252c60, {0x7fe8046e5970, 0xc0089c7040}, 0xc008864e00)
	github.com/go-chi/chi/v5@v5.0.7/mux.go:442 +0x216
net/http.HandlerFunc.ServeHTTP(0xc0055433a8?, {0x7fe8046e5970?, 0xc0089c7040?}, 0x393fe60?)
	net/http/server.go:2084 +0x2f
github.com/go-chi/chi/v5/middleware.StripSlashes.func1({0x7fe8046e5970, 0xc0089c7040}, 0xc008864e00)
	github.com/go-chi/chi/v5@v5.0.7/middleware/strip.go:30 +0x139
net/http.HandlerFunc.ServeHTTP(0x0?, {0x7fe8046e5970?, 0xc0089c7040?}, 0x457210?)
	net/http/server.go:2084 +0x2f
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc055252c60, {0x7fe8046e5970, 0xc0089c7040}, 0xc008864e00)
	github.com/go-chi/chi/v5@v5.0.7/mux.go:71 +0x48d
github.com/go-chi/chi/v5.(*Mux).Mount.func1({0x7fe8046e5970, 0xc0089c7040}, 0xc008864e00)
	github.com/go-chi/chi/v5@v5.0.7/mux.go:314 +0x19c
net/http.HandlerFunc.ServeHTTP(0x3989dc0?, {0x7fe8046e5970?, 0xc0089c7040?}, 0xc00898cc04?)
	net/http/server.go:2084 +0x2f
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc055252b40, {0x7fe8046e5970, 0xc0089c7040}, 0xc008864e00)
	github.com/go-chi/chi/v5@v5.0.7/mux.go:442 +0x216
net/http.HandlerFunc.ServeHTTP(0x3dd8688?, {0x7fe8046e5970?, 0xc0089c7040?}, 0x2?)
	net/http/server.go:2084 +0x2f
github.com/owncloud/ocis/v2/services/graph/pkg/middleware.Auth.func1.1({0x7fe8046e5970, 0xc0089c7040}, 0xc008864d00)
	github.com/owncloud/ocis/v2/services/graph/pkg/middleware/auth.go:84 +0x562
net/http.HandlerFunc.ServeHTTP(0x3dd61b0?, {0x7fe8046e5970?, 0xc0089c7040?}, 0xc000078c00?)
	net/http/server.go:2084 +0x2f
github.com/owncloud/ocis/v2/ocis-pkg/middleware.Logger.func1.1({0x3dd61b0, 0xc007d03c00}, 0xc008864d00)
	github.com/owncloud/ocis/v2/ocis-pkg/middleware/logger.go:17 +0xc8
net/http.HandlerFunc.ServeHTTP(0x3ba9ae0?, {0x3dd61b0?, 0xc007d03c00?}, 0xf?)
	net/http/server.go:2084 +0x2f
github.com/owncloud/ocis/v2/ocis-pkg/middleware.Version.func1.1({0x3dd61b0, 0xc007d03c00}, 0x3639f01?)
	github.com/owncloud/ocis/v2/ocis-pkg/middleware/version.go:18 +0x18f
net/http.HandlerFunc.ServeHTTP(0x3dd8688?, {0x3dd61b0?, 0xc007d03c00?}, 0x3639fa0?)
	net/http/server.go:2084 +0x2f
github.com/go-chi/chi/v5/middleware.RequestID.func1({0x3dd61b0, 0xc007d03c00}, 0xc008864c00)
	github.com/go-chi/chi/v5@v5.0.7/middleware/request_id.go:76 +0x354
net/http.HandlerFunc.ServeHTTP(0x3dd85e0?, {0x3dd61b0?, 0xc007d03c00?}, 0x528bb90?)
	net/http/server.go:2084 +0x2f
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc055252b40, {0x3dd61b0, 0xc007d03c00}, 0xc0087bd500)
	github.com/go-chi/chi/v5@v5.0.7/mux.go:88 +0x442
github.com/owncloud/ocis/v2/services/graph/pkg/service/v0.Graph.ServeHTTP(...)
	github.com/owncloud/ocis/v2/services/graph/pkg/service/v0/graph.go:85
github.com/owncloud/ocis/v2/services/graph/pkg/service/v0.instrument.ServeHTTP(...)
	github.com/owncloud/ocis/v2/services/graph/pkg/service/v0/instrument.go:24
github.com/owncloud/ocis/v2/services/graph/pkg/service/v0.logging.ServeHTTP(...)
	github.com/owncloud/ocis/v2/services/graph/pkg/service/v0/logging.go:24
github.com/owncloud/ocis/v2/services/graph/pkg/service/v0.tracing.ServeHTTP(...)
	github.com/owncloud/ocis/v2/services/graph/pkg/service/v0/tracing.go:20
net/http.serverHandler.ServeHTTP({0xc0084b1830?}, {0x3dd61b0, 0xc007d03c00}, 0xc0087bd500)
	net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc008365720, {0x3dd8688, 0xc0014f6780})
	net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	net/http/server.go:3071 +0x4db
```

## Expected behavior

Raise an error, but don't panic on unknown attributes.

## Setup

Container (owncloud/ocis:2.0.0-beta.5) + External OpenLDAP

**Comment by xoxys** [comment]
Seems to be fixed on latest already...

**Comment by dragonchaser** [comment]
@xoxys thx, closing then

**Comment by micbar** [comment]
what was the fix? Would be important to link the code change.

**Comment by xoxys** [comment]
Nobody knows right now

**Comment by dragonchaser** [comment]
could have been the bump of libregraph/idm shortly after the beta, but just guessing maybe @rhafer knows more?

**Comment by xoxys** [comment]
Thats what git bisect is made for, but I dont have time to look into it.

**Comment by rhafer** [comment]
I am pretty sure this is not fixed yet. At least I don't remember fixing it. Fix would be in the graph service. Will reopen and check again.
