### ISSUE TITLE
Panic on 32 bit Raspbian

### ISSUE THREAD

**Issue by dragotin** [owncloud/ocis#4604]
## Describe the bug

Tested version crashes on a Raspberry Pi running on latest 32 bit Raspbian:
```
panic: unaligned 64-bit atomic operation

goroutine 7682 [running]:
runtime/internal/atomic.panicUnaligned()
        runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Xadd64(0xc0462f4, 0x4)
        runtime/internal/atomic/atomic_arm.s:258 +0x14
github.com/blevesearch/zapx/v15.(*chunkedContentCoder).incrementBytesWritten(...)
        github.com/blevesearch/zapx/v15@v15.3.5/contentcoder.go:114
github.com/blevesearch/zapx/v15.(*chunkedContentCoder).flushContents(0xc046280)
        github.com/blevesearch/zapx/v15@v15.3.5/contentcoder.go:143 +0x294
github.com/blevesearch/zapx/v15.(*chunkedContentCoder).Close(...)
        github.com/blevesearch/zapx/v15@v15.3.5/contentcoder.go:110
github.com/blevesearch/zapx/v15.(*interim).writeDicts(0x5c7cff0)
        github.com/blevesearch/zapx/v15@v15.3.5/new.go:803 +0x11d8
github.com/blevesearch/zapx/v15.(*interim).convert(0x5c7cff0)
        github.com/blevesearch/zapx/v15@v15.3.5/new.go:277 +0x2f8
github.com/blevesearch/zapx/v15.(*ZapPlugin).newWithChunkMode(0x47deb54, {0x8661528, 0x1, 0x1}, 0x402)
        github.com/blevesearch/zapx/v15@v15.3.5/new.go:72 +0x218
github.com/blevesearch/zapx/v15.(*ZapPlugin).New(0x47deb54, {0x8661528, 0x1, 0x1})
        github.com/blevesearch/zapx/v15@v15.3.5/new.go:47 +0x40
github.com/blevesearch/bleve/v2/index/scorch.(*Scorch).Batch(0x24a0c400, 0x636a300)
        github.com/blevesearch/bleve/v2@v2.3.4/index/scorch/scorch.go:411 +0x5cc
github.com/blevesearch/bleve/v2/index/scorch.(*Scorch).Update(0x24a0c400, {0x358e8b8, 0x625fae0})
        github.com/blevesearch/bleve/v2@v2.3.4/index/scorch/scorch.go:334 +0x104
github.com/blevesearch/bleve/v2.(*indexImpl).Index(0x24a2a370, {0x8b2ad20, 0x6e}, {0x1c00e40, 0xac92870})
        github.com/blevesearch/bleve/v2@v2.3.4/index_impl.go:257 +0x218
github.com/owncloud/ocis/v2/services/search/pkg/search/index.(*Index).Add(0x24a32298, 0x20f5c600, 0x562be00)
        github.com/owncloud/ocis/v2/services/search/pkg/search/index/index.go:93 +0x9c
github.com/owncloud/ocis/v2/services/search/pkg/search/provider.(*Provider).handleEvent(0x24a2acd0, {0x1e38108, 0x15eaaf80})
        github.com/owncloud/ocis/v2/services/search/pkg/search/provider/events.go:120 +0xbcc
github.com/owncloud/ocis/v2/services/search/pkg/search/provider.New.func1.1()
        github.com/owncloud/ocis/v2/services/search/pkg/search/provider/searchprovider.go:93 +0x58
created by github.com/owncloud/ocis/v2/services/search/pkg/search/provider.New.func1
        github.com/owncloud/ocis/v2/services/search/pkg/search/provider/searchprovider.go:91 +0x2c
```

## Steps to reproduce

Edit and store a testfile with the web interface. On store, it panics.

## Setup
ownCloud Infinite Scale 2.0.0 Beta8 running from single binary build `./ocis-2.0.0-beta.8-linux-arm`

**Comment by dragotin** [comment]
ok, thx @wkloucek . 

@tbsbdr please note that with that, we can not support ARM 32. That should be noted.
