### ISSUE TITLE
[E2E] Nightly failure

### ISSUE THREAD

**Issue by grgprarup** [owncloud/ocis#4989]
E2E tests seems flaky for OCIS.

Build link: https://drone.owncloud.com/owncloud/ocis/16714/58/9, https://drone.owncloud.com/owncloud/ocis/16713/78/9
<details>
<summary>And "Alice" adds following users to the project space</summary>

```feature
And "Alice" adds following users to the project space # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:49
       | user  | role   |
       | Brian | editor |
       | Carol | viewer |
       locator.click: Error: strict mode violation: ".sidebar-panel .header__close" resolved to 2 elements:
           1) <button type="button" aria-label="Close file sidebar" cl…>…</button> aka playwright.$("internal:attr=[data-testid="sidebar-panel-details-space-item"] >> div:has-text("Details") button")
           2) <button type="button" aria-label="Close file sidebar" cl…>…</button> aka playwright.$("role=button[name="Close file sidebar"]")

       =========================== logs ===========================
       waiting for selector ".sidebar-panel .header__close"
         strict mode violation: ".sidebar-panel .header__close" resolved to 2 elements:
           1) <button type="button" aria-label="Close file sidebar" cl…>…</button> aka playwright.$("internal:attr=[data-testid="sidebar-panel-details-space-item"] >> div:has-text("Details") button")
           2) <button type="button" aria-label="Close file sidebar" cl…>…</button> aka playwright.$("role=button[name="Close file sidebar"]")

       ============================================================
           at Object.close (/drone/src/webTestRunner/tests/e2e/support/objects/app-files/utils/sidebar.ts:30:57)
           at addSpaceMembers (/drone/src/webTestRunner/tests/e2e/support/objects/app-files/spaces/actions.ts:115:27)
           at Spaces.addMembers (/drone/src/webTestRunner/tests/e2e/support/objects/app-files/spaces/index.ts:40:9)
           at World.<anonymous> (/drone/src/webTestRunner/tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:53:9)
```
</details>

<details>
<summary>And "Alice" updates the space "team.2" name to "management team</summary>

```feature
And "Alice" updates the space "team.2" name to "management team" # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:23
       locator.click: Error: strict mode violation: ".sidebar-panel .header__close" resolved to 2 elements:
           1) <button type="button" aria-label="Close file sidebar" cl…>…</button> aka playwright.$("internal:attr=[data-testid="sidebar-panel-details-space-item"] >> div:has-text("Details") button")
           2) <button type="button" aria-label="Close file sidebar" cl…>…</button> aka playwright.$("role=button[name="Close file sidebar"]")

       =========================== logs ===========================
       waiting for selector ".sidebar-panel .header__close"
         strict mode violation: ".sidebar-panel .header__close" resolved to 2 elements:
           1) <button type="button" aria-label="Close file sidebar" cl…>…</button> aka playwright.$("internal:attr=[data-testid="sidebar-panel-details-space-item"] >> div:has-text("Details") button")
           2) <button type="button" aria-label="Close file sidebar" cl…>…</button> aka playwright.$("role=button[name="Close file sidebar"]")

       ============================================================
           at Object.close (/drone/src/webTestRunner/tests/e2e/support/objects/app-files/utils/sidebar.ts:30:57)
           at changeSpaceName (/drone/src/webTestRunner/tests/e2e/support/objects/app-files/spaces/actions.ts:58:27)
           at Spaces.changeName (/drone/src/webTestRunner/tests/e2e/support/objects/app-files/spaces/index.ts:26:9)
           at World.<anonymous> (/drone/src/webTestRunner/tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:28:13)
```
</details>

<details>
<summary>And public link named "folderLink" of the resource "spaceFolder" should be visible to "Carol"</summary>

```feature
And public link named "folderLink" of the resource "spaceFolder" should be visible to "Carol" # tests/e2e/cucumber/steps/app-files/link.ts:58
       locator.click: Error: strict mode violation: ".sidebar-panel .header__close" resolved to 2 elements:
           1) <button type="button" aria-label="Close file sidebar" cl…>…</button> aka playwright.$("internal:attr=[data-testid="sidebar-panel-details-space-item"] >> div:has-text("Details") button")
           2) <button type="button" aria-label="Close file sidebar" cl…>…</button> aka playwright.$("role=button[name="Close file sidebar"]")

       =========================== logs ===========================
       waiting for selector ".sidebar-panel .header__close"
         strict mode violation: ".sidebar-panel .header__close" resolved to 2 elements:
           1) <button type="button" aria-label="Close file sidebar" cl…>…</button> aka playwright.$("internal:attr=[data-testid="sidebar-panel-details-space-item"] >> div:has-text("Details") button")
           2) <button type="button" aria-label="Close file sidebar" cl…>…</button> aka playwright.$("role=button[name="Close file sidebar"]")

       ============================================================
           at close (/drone/src/webTestRunner/tests/e2e/support/objects/app-files/utils/sidebar.ts:30:57)
           at Object.open (/drone/src/webTestRunner/tests/e2e/support/objects/app-files/utils/sidebar.ts:24:33)
           at getPublicLinkVisibility (/drone/src/webTestRunner/tests/e2e/support/objects/app-files/link/actions.ts:150:5)
           at Link.getPublicLinkUrl (/drone/src/webTestRunner/tests/e2e/support/objects/app-files/link/index.ts:62:28)
           at World.<anonymous> (/drone/src/webTestRunner/tests/e2e/cucumber/steps/app-files/link.ts:61:28)
```
</details>

<details>
<summary>When "Alice" changes the roles of the following users in the project space</summary>

```feature
When "Alice" changes the roles of the following users in the project space # tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:93
       | user  | role    |
       | Carol | manager |
       locator.click: Error: strict mode violation: ".sidebar-panel .header__close" resolved to 2 elements:
           1) <button type="button" aria-label="Close file sidebar" cl…>…</button> aka playwright.$("internal:attr=[data-testid="sidebar-panel-details-space-item"] >> div:has-text("Details") button")
           2) <button type="button" aria-label="Close file sidebar" cl…>…</button> aka playwright.$("role=button[name="Close file sidebar"]")

       =========================== logs ===========================
       waiting for selector ".sidebar-panel .header__close"
         strict mode violation: ".sidebar-panel .header__close" resolved to 2 elements:
           1) <button type="button" aria-label="Close file sidebar" cl…>…</button> aka playwright.$("internal:attr=[data-testid="sidebar-panel-details-space-item"] >> div:has-text("Details") button")
           2) <button type="button" aria-label="Close file sidebar" cl…>…</button> aka playwright.$("role=button[name="Close file sidebar"]")

       ============================================================
           at close (/drone/src/webTestRunner/tests/e2e/support/objects/app-files/utils/sidebar.ts:30:57)
           at Object.open (/drone/src/webTestRunner/tests/e2e/support/objects/app-files/utils/sidebar.ts:24:33)
           at changeSpaceRole (/drone/src/webTestRunner/tests/e2e/support/objects/app-files/spaces/actions.ts:174:5)
           at Spaces.changeRoles (/drone/src/webTestRunner/tests/e2e/support/objects/app-files/spaces/index.ts:59:9)
           at World.<anonymous> (/drone/src/webTestRunner/tests/e2e/cucumber/steps/app-files/page/spaces/projects.ts:97:9)
```
</details>

**Comment by saw-jan** [comment]
The fix is in this PR https://github.com/owncloud/web/pull/7910 (or I can create a separate PR for that)
But we only bump web commit-id when there is a new web release

**Comment by saw-jan** [comment]
Closing in favor of https://github.com/owncloud/ocis/issues/4984
