### ISSUE TITLE
Settings service normal user can edit existing bundles

### ISSUE THREAD

**Issue by C0rby** [owncloud/ocis#5033]
## Context
oCIS version: v2.0.0-rc.1

## Issue
A normal authenticated user can edit existing settings bundles.

```
curl -k -s -u einstein:relativity -X POST 'https://localhost:9200/api/v0/settings/bundles-add-setting' -d '{
    "bundle_id": "2a506de7-99bd-4f0d-994e-c38e72c28fd9",
    "setting":
        {
            "id": "aa8cfbe5-95d4-4f7e-a032-c3c01f5f062f",
"name": "language",
            "singleChoiceValue": {
"options": [
                    {
                        "value": {
                            "stringValue": "cs\""
                        },
                        "displayValue": "<h1>Czech</h1>"
                    }
                ]
            },
            "resource": {
                "type": "TYPE_USER"
            }
        }
}' | jq .

{
  "setting": {
    "id": "aa8cfbe5-95d4-4f7e-a032-c3c01f5f062f",
    "name": "language",
    "singleChoiceValue": {
      "options": [
        {
          "value": {
            "stringValue": "foo"
          },
          "displayValue": "foobar"
        }
      ]
    },
    "resource": {
      "type": "TYPE_USER"
    }
  }
}
```

## Expected
A normal user shouldn't be able to edit existing settings.

**Comment by butonic** [comment]
after starting ocis i get a 502 when trying this with einstein. when using admin it works, when trying again with einstein it works too 🤔 

the first time I get a panic:
```
2022/11/14 10:28:05 http: panic serving 127.0.0.1:40120: runtime error: index out of range [0] with length 0
goroutine 2330 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1850 +0x148
panic({0x36f9920, 0xc001715608})
	/usr/local/go/src/runtime/panic.go:890 +0x267
github.com/owncloud/ocis/v2/services/settings/pkg/store/metadata.(*Store).ReadBundle(0xc00189a580, {0xc003c8a900, 0x24})
	/home/vscode/repositories/ocis/services/settings/pkg/store/metadata/bundles.go:56 +0x2d8
github.com/owncloud/ocis/v2/services/settings/pkg/service/v0.Service.checkStaticPermissionsByBundleID({{0x0, 0x0}, 0xc000eab680, {{{0x0, 0x0}, 0x0, {0x0, 0x0}, {0x0, 0x0, ...}, ...}}, ...}, ...)
	/home/vscode/repositories/ocis/services/settings/pkg/service/v0/service.go:576 +0x8f
github.com/owncloud/ocis/v2/services/settings/pkg/service/v0.Service.AddSettingToBundle({{0x0, 0x0}, 0xc000eab680, {{{0x0, 0x0}, 0x0, {0x0, 0x0}, {0x0, 0x0, ...}, ...}}, ...}, ...)
	/home/vscode/repositories/ocis/services/settings/pkg/service/v0/service.go:241 +0xfb
github.com/owncloud/ocis/v2/protogen/gen/ocis/services/settings/v0.(*webBundleServiceHandler).AddSettingToBundle(0xc001801880, {0x7fe6fc59bc50, 0xc002f58600}, 0xc00329ac00)
	/home/vscode/repositories/ocis/protogen/gen/ocis/services/settings/v0/settings.pb.web.go:115 +0x23c
net/http.HandlerFunc.ServeHTTP(0xc001bb01a0, {0x7fe6fc59bc50, 0xc002f58600}, 0xc00329ac00)
	/usr/local/go/src/net/http/server.go:2109 +0x43
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc001884f00, {0x7fe6fc59bc50, 0xc002f58600}, 0xc00329ac00)
	/home/vscode/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:442 +0x292
net/http.HandlerFunc.ServeHTTP(0xc001bb0150, {0x7fe6fc59bc50, 0xc002f58600}, 0xc00329ac00)
	/usr/local/go/src/net/http/server.go:2109 +0x43
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc001884f00, {0x7fe6fc59bc50, 0xc002f58600}, 0xc00329ac00)
	/home/vscode/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:71 +0xfa
github.com/go-chi/chi/v5.(*Mux).Mount.func1({0x7fe6fc59bc50, 0xc002f58600}, 0xc00329ac00)
	/home/vscode/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:314 +0x20c
net/http.HandlerFunc.ServeHTTP(0xc001801980, {0x7fe6fc59bc50, 0xc002f58600}, 0xc00329ac00)
	/usr/local/go/src/net/http/server.go:2109 +0x43
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc001884e40, {0x7fe6fc59bc50, 0xc002f58600}, 0xc00329ac00)
	/home/vscode/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:442 +0x292
net/http.HandlerFunc.ServeHTTP(0xc001bb02b0, {0x7fe6fc59bc50, 0xc002f58600}, 0xc00329ac00)
	/usr/local/go/src/net/http/server.go:2109 +0x43
github.com/owncloud/ocis/v2/ocis-pkg/middleware.Static.func1.1({0x7fe6fc59bc50, 0xc002f58600}, 0xc00329ac00)
	/home/vscode/repositories/ocis/ocis-pkg/middleware/static.go:31 +0x186
net/http.HandlerFunc.ServeHTTP(0xc001883200, {0x7fe6fc59bc50, 0xc002f58600}, 0xc00329ac00)
	/usr/local/go/src/net/http/server.go:2109 +0x43
github.com/owncloud/ocis/v2/ocis-pkg/middleware.Logger.func1.1({0x4a326e8, 0xc0001c5340}, 0xc00329ac00)
	/home/vscode/repositories/ocis/ocis-pkg/middleware/logger.go:17 +0x11a
net/http.HandlerFunc.ServeHTTP(0xc0018019a0, {0x4a326e8, 0xc0001c5340}, 0xc00329ac00)
	/usr/local/go/src/net/http/server.go:2109 +0x43
github.com/owncloud/ocis/v2/ocis-pkg/middleware.Version.func1.1({0x4a326e8, 0xc0001c5340}, 0xc00329ac00)
	/home/vscode/repositories/ocis/ocis-pkg/middleware/version.go:18 +0x1af
net/http.HandlerFunc.ServeHTTP(0xc001883240, {0x4a326e8, 0xc0001c5340}, 0xc00329ac00)
	/usr/local/go/src/net/http/server.go:2109 +0x43
github.com/owncloud/ocis/v2/ocis-pkg/middleware.ExtractAccountUUID.func1.1({0x4a326e8, 0xc0001c5340}, 0xc00329ab00)
	/home/vscode/repositories/ocis/ocis-pkg/middleware/account.go:75 +0x65b
net/http.HandlerFunc.ServeHTTP(0xc001881e90, {0x4a326e8, 0xc0001c5340}, 0xc00329ab00)
	/usr/local/go/src/net/http/server.go:2109 +0x43
github.com/owncloud/ocis/v2/ocis-pkg/middleware.Secure.func1({0x4a326e8, 0xc0001c5340}, 0xc00329ab00)
	/home/vscode/repositories/ocis/ocis-pkg/middleware/header.go:57 +0x14a
net/http.HandlerFunc.ServeHTTP(0xc0004e2f18, {0x4a326e8, 0xc0001c5340}, 0xc00329ab00)
	/usr/local/go/src/net/http/server.go:2109 +0x43
github.com/go-chi/cors.(*Cors).Handler.func1({0x4a326e8, 0xc0001c5340}, 0xc00329ab00)
	/home/vscode/go/pkg/mod/github.com/go-chi/cors@v1.2.1/cors.go:228 +0x2ec
net/http.HandlerFunc.ServeHTTP(0xc0018019c0, {0x4a326e8, 0xc0001c5340}, 0xc00329ab00)
	/usr/local/go/src/net/http/server.go:2109 +0x43
github.com/owncloud/ocis/v2/ocis-pkg/middleware.NoCache.func1({0x4a326e8, 0xc0001c5340}, 0xc00329ab00)
	/home/vscode/repositories/ocis/ocis-pkg/middleware/header.go:20 +0x17e
net/http.HandlerFunc.ServeHTTP(0xc0004e2f30, {0x4a326e8, 0xc0001c5340}, 0xc00329ab00)
	/usr/local/go/src/net/http/server.go:2109 +0x43
github.com/go-chi/chi/v5/middleware.RequestID.func1({0x4a326e8, 0xc0001c5340}, 0xc00329aa00)
	/home/vscode/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/middleware/request_id.go:76 +0x267
net/http.HandlerFunc.ServeHTTP(0xc0004e2f48, {0x4a326e8, 0xc0001c5340}, 0xc00329aa00)
	/usr/local/go/src/net/http/server.go:2109 +0x43
github.com/go-chi/chi/v5/middleware.RealIP.func1({0x4a326e8, 0xc0001c5340}, 0xc00329aa00)
	/home/vscode/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/middleware/realip.go:35 +0xae
net/http.HandlerFunc.ServeHTTP(0xc0004e2f60, {0x4a326e8, 0xc0001c5340}, 0xc00329aa00)
	/usr/local/go/src/net/http/server.go:2109 +0x43
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc001884e40, {0x4a326e8, 0xc0001c5340}, 0xc00329aa00)
	/home/vscode/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:88 +0x282
net/http.serverHandler.ServeHTTP({0xc0017a82d0}, {0x4a326e8, 0xc0001c5340}, 0xc00471e100)
	/usr/local/go/src/net/http/server.go:2947 +0x474
net/http.(*conn).serve(0xc00192dea0, {0x4a34b50, 0xc000d66180})
	/usr/local/go/src/net/http/server.go:1991 +0x195c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3102 +0x9e5
2022/11/14 10:28:05 http: proxy error: EOF
```


ummm same for admin


```
2022/11/14 10:29:58 http: panic serving 127.0.0.1:34968: runtime error: index out of range [0] with length 0
goroutine 5736 [running]:
net/http.(*conn).serve.func1()
	/usr/local/go/src/net/http/server.go:1850 +0x148
panic({0x36f9920, 0xc00180aae0})
	/usr/local/go/src/runtime/panic.go:890 +0x267
github.com/owncloud/ocis/v2/services/settings/pkg/store/metadata.(*Store).ReadBundle(0xc00189a580, {0xc003bf5980, 0x24})
	/home/vscode/repositories/ocis/services/settings/pkg/store/metadata/bundles.go:56 +0x2d8
github.com/owncloud/ocis/v2/services/settings/pkg/service/v0.Service.checkStaticPermissionsByBundleID({{0x0, 0x0}, 0xc000eab680, {{{0x0, 0x0}, 0x0, {0x0, 0x0}, {0x0, 0x0, ...}, ...}}, ...}, ...)
	/home/vscode/repositories/ocis/services/settings/pkg/service/v0/service.go:576 +0x8f
github.com/owncloud/ocis/v2/services/settings/pkg/service/v0.Service.AddSettingToBundle({{0x0, 0x0}, 0xc000eab680, {{{0x0, 0x0}, 0x0, {0x0, 0x0}, {0x0, 0x0, ...}, ...}}, ...}, ...)
	/home/vscode/repositories/ocis/services/settings/pkg/service/v0/service.go:241 +0xfb
github.com/owncloud/ocis/v2/protogen/gen/ocis/services/settings/v0.(*webBundleServiceHandler).AddSettingToBundle(0xc001801880, {0x7fe6fc59bc50, 0xc001170b00}, 0xc00167a800)
	/home/vscode/repositories/ocis/protogen/gen/ocis/services/settings/v0/settings.pb.web.go:115 +0x23c
net/http.HandlerFunc.ServeHTTP(0xc001bb01a0, {0x7fe6fc59bc50, 0xc001170b00}, 0xc00167a800)
	/usr/local/go/src/net/http/server.go:2109 +0x43
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc001884f00, {0x7fe6fc59bc50, 0xc001170b00}, 0xc00167a800)
	/home/vscode/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:442 +0x292
net/http.HandlerFunc.ServeHTTP(0xc001bb0150, {0x7fe6fc59bc50, 0xc001170b00}, 0xc00167a800)
	/usr/local/go/src/net/http/server.go:2109 +0x43
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc001884f00, {0x7fe6fc59bc50, 0xc001170b00}, 0xc00167a800)
	/home/vscode/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:71 +0xfa
github.com/go-chi/chi/v5.(*Mux).Mount.func1({0x7fe6fc59bc50, 0xc001170b00}, 0xc00167a800)
	/home/vscode/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:314 +0x20c
net/http.HandlerFunc.ServeHTTP(0xc001801980, {0x7fe6fc59bc50, 0xc001170b00}, 0xc00167a800)
	/usr/local/go/src/net/http/server.go:2109 +0x43
github.com/go-chi/chi/v5.(*Mux).routeHTTP(0xc001884e40, {0x7fe6fc59bc50, 0xc001170b00}, 0xc00167a800)
	/home/vscode/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:442 +0x292
net/http.HandlerFunc.ServeHTTP(0xc001bb02b0, {0x7fe6fc59bc50, 0xc001170b00}, 0xc00167a800)
	/usr/local/go/src/net/http/server.go:2109 +0x43
github.com/owncloud/ocis/v2/ocis-pkg/middleware.Static.func1.1({0x7fe6fc59bc50, 0xc001170b00}, 0xc00167a800)
	/home/vscode/repositories/ocis/ocis-pkg/middleware/static.go:31 +0x186
net/http.HandlerFunc.ServeHTTP(0xc001883200, {0x7fe6fc59bc50, 0xc001170b00}, 0xc00167a800)
	/usr/local/go/src/net/http/server.go:2109 +0x43
github.com/owncloud/ocis/v2/ocis-pkg/middleware.Logger.func1.1({0x4a326e8, 0xc001d44540}, 0xc00167a800)
	/home/vscode/repositories/ocis/ocis-pkg/middleware/logger.go:17 +0x11a
net/http.HandlerFunc.ServeHTTP(0xc0018019a0, {0x4a326e8, 0xc001d44540}, 0xc00167a800)
	/usr/local/go/src/net/http/server.go:2109 +0x43
github.com/owncloud/ocis/v2/ocis-pkg/middleware.Version.func1.1({0x4a326e8, 0xc001d44540}, 0xc00167a800)
	/home/vscode/repositories/ocis/ocis-pkg/middleware/version.go:18 +0x1af
net/http.HandlerFunc.ServeHTTP(0xc001883240, {0x4a326e8, 0xc001d44540}, 0xc00167a800)
	/usr/local/go/src/net/http/server.go:2109 +0x43
github.com/owncloud/ocis/v2/ocis-pkg/middleware.ExtractAccountUUID.func1.1({0x4a326e8, 0xc001d44540}, 0xc00167a700)
	/home/vscode/repositories/ocis/ocis-pkg/middleware/account.go:75 +0x65b
net/http.HandlerFunc.ServeHTTP(0xc001881e90, {0x4a326e8, 0xc001d44540}, 0xc00167a700)
	/usr/local/go/src/net/http/server.go:2109 +0x43
github.com/owncloud/ocis/v2/ocis-pkg/middleware.Secure.func1({0x4a326e8, 0xc001d44540}, 0xc00167a700)
	/home/vscode/repositories/ocis/ocis-pkg/middleware/header.go:57 +0x14a
net/http.HandlerFunc.ServeHTTP(0xc0004e2f18, {0x4a326e8, 0xc001d44540}, 0xc00167a700)
	/usr/local/go/src/net/http/server.go:2109 +0x43
github.com/go-chi/cors.(*Cors).Handler.func1({0x4a326e8, 0xc001d44540}, 0xc00167a700)
	/home/vscode/go/pkg/mod/github.com/go-chi/cors@v1.2.1/cors.go:228 +0x2ec
net/http.HandlerFunc.ServeHTTP(0xc0018019c0, {0x4a326e8, 0xc001d44540}, 0xc00167a700)
	/usr/local/go/src/net/http/server.go:2109 +0x43
github.com/owncloud/ocis/v2/ocis-pkg/middleware.NoCache.func1({0x4a326e8, 0xc001d44540}, 0xc00167a700)
	/home/vscode/repositories/ocis/ocis-pkg/middleware/header.go:20 +0x17e
net/http.HandlerFunc.ServeHTTP(0xc0004e2f30, {0x4a326e8, 0xc001d44540}, 0xc00167a700)
	/usr/local/go/src/net/http/server.go:2109 +0x43
github.com/go-chi/chi/v5/middleware.RequestID.func1({0x4a326e8, 0xc001d44540}, 0xc00167a600)
	/home/vscode/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/middleware/request_id.go:76 +0x267
net/http.HandlerFunc.ServeHTTP(0xc0004e2f48, {0x4a326e8, 0xc001d44540}, 0xc00167a600)
	/usr/local/go/src/net/http/server.go:2109 +0x43
github.com/go-chi/chi/v5/middleware.RealIP.func1({0x4a326e8, 0xc001d44540}, 0xc00167a600)
	/home/vscode/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/middleware/realip.go:35 +0xae
net/http.HandlerFunc.ServeHTTP(0xc0004e2f60, {0x4a326e8, 0xc001d44540}, 0xc00167a600)
	/usr/local/go/src/net/http/server.go:2109 +0x43
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc001884e40, {0x4a326e8, 0xc001d44540}, 0xc00167a600)
	/home/vscode/go/pkg/mod/github.com/go-chi/chi/v5@v5.0.7/mux.go:88 +0x282
net/http.serverHandler.ServeHTTP({0xc0017a82d0}, {0x4a326e8, 0xc001d44540}, 0xc002540300)
	/usr/local/go/src/net/http/server.go:2947 +0x474
net/http.(*conn).serve(0xc00263af00, {0x4a34b50, 0xc0031cfbc0})
	/usr/local/go/src/net/http/server.go:1991 +0x195c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:3102 +0x9e5
2022/11/14 10:29:58 http: proxy error: EOF
```

👀

**Comment by butonic** [comment]
hmmm

```

	// SettingsManagementPermissionID is the hardcoded setting UUID for the settings management permission
	SettingsManagementPermissionID string = "79e13b30-3e22-11eb-bc51-0b9f0bad9a58"
...
	// CreateSpacePermissionID is the hardcoded setting UUID for the create space permission
	CreateSpacePermissionID string = "79e13b30-3e22-11eb-bc51-0b9f0bad9a58"
```

**Comment by rhafer** [comment]
> the first time I get a panic:

@butonic This should be fixed with: https://github.com/owncloud/ocis/pull/5057
