### ISSUE TITLE
oCIS Single Binary Panic

### ISSUE THREAD

**Issue by dragotin** [owncloud/ocis#5082]
I was testing ocis single binary on an odroid a bit back and forth, and got this panic:
```
{"level":"error","service":"storage-users","pkg":"rgrpc","traceid":"00000000000000000000000000000000","node":"marshaling error: json: unsupported value: encountered a cycle via *node.Node","node":"marshaling error: json: unsupported value: encountered a cycle via *node.Node","error":"xattr.Remove /data/ocis/base/storage/users/spaces/4c/510ada-c86b-4815-8820-42cdf82c3d51/nodes/4c/51/0a/da/-c86b-4815-8820-42cdf82c3d51 user.ocis.tmp.etag: no data available","time":"2022-11-19T17:29:23.577730385+01:00","message":"could not remove temporary etag attribute"}
{"level":"error","service":"storage-users","pkg":"rgrpc","traceid":"00000000000000000000000000000000","error":"no data available","nodepath":"/data/ocis/base/storage/users/spaces/4c/510ada-c86b-4815-8820-42cdf82c3d51/nodes/4c/51/0a/da/-c86b-4815-8820-42cdf82c3d51","time":"2022-11-19T17:29:23.709418697+01:00","message":"could not read quota"}
{"level":"error","service":"storage-users","pkg":"rgrpc","traceid":"00000000000000000000000000000000","error":"no data available","nodepath":"/data/ocis/base/storage/users/spaces/4c/510ada-c86b-4815-8820-42cdf82c3d51/nodes/4c/51/0a/da/-c86b-4815-8820-42cdf82c3d51","time":"2022-11-19T17:29:23.717594995+01:00","message":"could not read quota"}
panic: interface conversion: interface {} is nil, not bool

goroutine 99998 [running]:
github.com/owncloud/ocis/v2/services/search/pkg/search/index.fieldsToEntity(...)
        github.com/owncloud/ocis/v2/services/search/pkg/search/index/index.go:323
github.com/owncloud/ocis/v2/services/search/pkg/search/index.(*Index).getEntity(0x400151d080, {0x4003f04310, 0x6e})
        github.com/owncloud/ocis/v2/services/search/pkg/search/index/index.go:166 +0x6c4
github.com/owncloud/ocis/v2/services/search/pkg/search/index.(*Index).updateEntity(0x400151d080, {0x4003f04310?, 0xaaaab0a10b98?}, 0x4001403cd8)
        github.com/owncloud/ocis/v2/services/search/pkg/search/index/index.go:143 +0x2c
github.com/owncloud/ocis/v2/services/search/pkg/search/index.(*Index).markAsDeleted(0x400151d080, {0x4003f04310?, 0x4003a7e300?}, 0x1)
        github.com/owncloud/ocis/v2/services/search/pkg/search/index/index.go:109 +0x48
github.com/owncloud/ocis/v2/services/search/pkg/search/index.(*Index).Delete(0x4001ea54a0?, 0xaaaaae87b6d5?)
        github.com/owncloud/ocis/v2/services/search/pkg/search/index/index.go:100 +0x94
github.com/owncloud/ocis/v2/services/search/pkg/search/provider.(*Provider).handleEvent(0x4001ea54a0, {0xaaaab08578c0?, 0x400445f6e0?})
        github.com/owncloud/ocis/v2/services/search/pkg/search/provider/events.go:68 +0x11c
github.com/owncloud/ocis/v2/services/search/pkg/search/provider.New.func2.1()
        github.com/owncloud/ocis/v2/services/search/pkg/search/provider/searchprovider.go:102 +0x50
created by github.com/owncloud/ocis/v2/services/search/pkg/search/provider.New.func2
        github.com/owncloud/ocis/v2/services/search/pkg/search/provider/searchprovider.go:100 +0x34
```
I can not reliably say which operation in the web interface caused that.

oCIS daily build arm64 from 11/18/2022 12:13:41 PM

**Comment by micbar** [comment]
@aduffeck Can you take a look?

**Comment by dragotin** [comment]
Well, I can not really reproduce the problem. It only appeared once.

Let's close that for now.
