### ISSUE TITLE
Nightly webUI tests fail of `webUIUpload/uploadEdgecases.feature:15`

### ISSUE THREAD

**Issue by SagarGi** [owncloud/ocis#5657]
### Description
This tests seems to be failing sometimes in nightly. Might be good if we could make it stable.

```feature
Scenario: simple upload of a file that does not exist before # features/webUIUpload/uploadEdgecases.feature:15
- Connecting to selenium on port 4444...

ℹ Connected to selenium on port 4444 (10732ms).
  Using: chrome (104.0.5112.79) on Linux platform.

    Given user "Alice" has been created with default attributes and without skeleton files in the server
    And user "Alice" has logged in using the webUI
√ Element <input[autocomplete="kopano-account username"]> was visible after 321 milliseconds.
√ Element <input[autocomplete="kopano-account username"]> was not present after 187 milliseconds.
√ Element <#files-view> was visible after 606 milliseconds.
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was visible after 25 milliseconds.
    And the user browses to the files page
√ Element <//*[self::table[contains(@class, "files-table")] or self::div[contains(@class, "files-empty")] or self::div[contains(@class, "files-not-found")]]> was present after 266 milliseconds.
    When the user uploads file "new-'single'quotes.txt" using the webUI
√ Element <#upload-menu-btn:not([disabled])> was visible after 25 milliseconds.
√ Element <#files-file-upload-button> was visible after 34 milliseconds.
√ Element <.upload-info-status .upload-info-success, .upload-info-status .upload-info-danger> was visible after 61 milliseconds.
√ Element <#upload-info #close-upload-info-btn> was visible after 64 milliseconds.
    Then file "new-'single'quotes.txt" should be listed on the webUI
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name="new-'single'quotes.txt" or @data-test-resource-path="/new-'single'quotes.txt") and @data-test-resource-type='file']/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 24 milliseconds.
    And as "Alice" the content of "new-'single'quotes.txt" in the server should be the same as the content of local file "new-'single'quotes.txt"
    When the user uploads file "new-strängé filename (duplicate #2 &).txt" using the webUI
√ Element <#upload-menu-btn:not([disabled])> was visible after 26 milliseconds.
√ Element <#files-file-upload-button> was visible after 16 milliseconds.
√ Element <.upload-info-status .upload-info-success, .upload-info-status .upload-info-danger> was visible after 93 milliseconds.
√ Element <#upload-info #close-upload-info-btn> was visible after 23 milliseconds.
    Then file "new-strängé filename (duplicate #2 &).txt" should be listed on the webUI
√ Element <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='new-strängé filename (duplicate #2 &).txt' or @data-test-resource-path='/new-strängé filename (duplicate #2 &).txt') and @data-test-resource-type='file']/ancestor::tr[contains(@class, "oc-tbody-tr")]> was visible after 27 milliseconds.
    And as "Alice" the content of "new-strängé filename (duplicate #2 &).txt" in the server should be the same as the content of local file "new-strängé filename (duplicate #2 &).txt"
    When the user uploads file "zzzz-zzzz-will-be-at-the-end-of-the-folder-when-uploaded.txt" using the webUI
√ Element <#upload-menu-btn:not([disabled])> was visible after 14 milliseconds.
√ Element <#files-file-upload-button> was visible after 23 milliseconds.
√ Element <.upload-info-status .upload-info-success, .upload-info-status .upload-info-danger> was visible after 46 milliseconds.
√ Element <#upload-info #close-upload-info-btn> was visible after 20 milliseconds.
    Then file "zzzz-zzzz-will-be-at-the-end-of-the-folder-when-uploaded.txt" should be listed on the webUI
   NoSuchElementError: An error occurred while running .getText() command on <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='zzzz-zzzz-will-be-at-the-end-of-the-folder-when-uploaded.txt' or @data-test-resource-path='/zzzz-zzzz-will-be-at-the-end-of-the-folder-when-uploaded.txt') and @data-test-resource-type='file']>: 
   {"sessionId":"23dd6d06486709a7503e067c135d349e","status":0,"value":[]}
       at Proxy.checkFileName (/drone/src/webTestRunner/tests/acceptance/pageObjects/FilesPageElement/filesList.js:365:18)
       at Proxy.waitForFileVisible (/drone/src/webTestRunner/tests/acceptance/pageObjects/FilesPageElement/filesList.js:353:18)
       at World.<anonymous> (/drone/src/webTestRunner/tests/acceptance/stepDefinitions/filesContext.js:355:51)
    ✖ failed
      AssertionError [ERR_ASSERTION]: An error occurred while running .getText() command on <//span[contains(@class, "oc-resource-name") and (@data-test-resource-name='zzzz-zzzz-will-be-at-the-end-of-the-folder-when-uploaded.txt' or @data-test-resource-path='/zzzz-zzzz-will-be-at-the-end-of-the-folder-when-uploaded.txt') and @data-test-resource-type='file']>:
          at Proxy.checkFileName (/drone/src/webTestRunner/tests/acceptance/pageObjects/FilesPageElement/filesList.js:375:16)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (node:internal/process/task_queues:96:5)
          at Proxy.waitForFileVisible (/drone/src/webTestRunner/tests/acceptance/pageObjects/FilesPageElement/filesList.js:353:7)
    And as "Alice" the content of "zzzz-zzzz-will-be-at-the-end-of-the-folder-when-uploaded.txt" in the server should be the same as the content of local file "zzzz-zzzz-will-be-at-the-end-of-the-folder-when-uploaded.txt"
    - skipped
```
Failed Build link:  https://drone.owncloud.com/owncloud/ocis/19497/78/13

**Comment by amrita-shrestha** [comment]
@saw-jan  from my investigation this intermittent failure cause could be test speed :
When the user uploads file "zzzz-zzzz-will-be-at-the-end-of-the-folder-when-uploaded.txt" using the webUI
https://github.com/owncloud/web/blob/c62001a82758c3d72a3ceb41e7ec1699c5c4c285/tests/acceptance/pageObjects/personalPage.js#L162-L166
Then file "zzzz-zzzz-will-be-at-the-end-of-the-folder-when-uploaded.txt" should be listed on the webUI
https://github.com/owncloud/web/blob/851b7cf8e3ce33c92953094097a8784b16b85bb6/tests/acceptance/pageObjects/FilesPageElement/filesList.js#L357-L360.

My suggestion is to add ` .waitForAnimationToFinish() ` to wait some time before looking for file
```

**Comment by saw-jan** [comment]
I would think that the file should be visible while closing the upload dialog but can't say what might have caused the file to be not visible. Maybe the file upload was not successful?
Function `.waitForAnimationToFinish()` is just a `500ms` wait.

**Comment by amrita-shrestha** [comment]
> I would think that the file should be visible while closing the upload dialog but can't say what might have caused the file to be not visible. Maybe the file upload was not successful? Function `.waitForAnimationToFinish()` is just a `500ms` wait.

Yeah, that could be another reason also. Thats where tests fail while checking upload was successful or not.

**Comment by SwikritiT** [comment]
This error has not occurred recently, so I'm putting it in the backlog. We'll get back to it if it re-occurs in the future

**Comment by saw-jan** [comment]
Pretty stable til now. I will close it here. If reappears, we can re-open and try to figure out a better solution
