### ISSUE TITLE
Stack trace if roles aren't exiting in token

### ISSUE THREAD

**Issue by d7oc** [owncloud/ocis#6023]
## Describe the bug

If roles aren't set in the token and role driver is set to OIDC the following stack trace appears:

```
{"level":"error","service":"proxy","request-id":"32831181-3870-49b6-91ca-da2e5bebb352","userid":"2000f6a4-0a19-424d-8911-bd5cc3cf042d","rolesClaim":"roles","time":"2023-04-06T08:56:27.154611064Z","line":"github.com/owncloud/ocis/v2/services/proxy/pkg/userroles/oidcroles.go:46","message":"No roles in user claims"}
2023/04/06 08:56:27 http: panic serving 10.42.0.88:54838: runtime error: invalid memory address or nil pointer dereference
goroutine 1435 [running]:
net/http.(*conn).serve.func1()
	net/http/server.go:1854 +0xbf
panic({0x3d64a40, 0x59f9c30})
	runtime/panic.go:890 +0x263
github.com/owncloud/ocis/v2/services/proxy/pkg/middleware.createHome.getUserRoles({{0x4237380, 0xc0016d45b0}, {{{0x4246308, 0xc0016c5580}, 0x1, {0x0, 0x0}, {0xc0001a0000, 0x12, 0x1f4}, ...}}, ...}, ...)
	github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/create_home.go:87 +0x54
github.com/owncloud/ocis/v2/services/proxy/pkg/middleware.createHome.ServeHTTP({{0x4237380, 0xc0016d45b0}, {{{0x4246308, 0xc0016c5580}, 0x1, {0x0, 0x0}, {0xc0001a0000, 0x12, 0x1f4}, ...}}, ...}, ...)
	github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/create_home.go:56 +0x1bb
github.com/owncloud/ocis/v2/services/proxy/pkg/middleware.Policies.func1.1({0x7fbea8ca97c0?, 0xc0014eb680?}, 0x0?)
	github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/policies.go:20 +0x5a4
net/http.HandlerFunc.ServeHTTP(0x1?, {0x7fbea8ca97c0?, 0xc0014eb680?}, 0xc0001f6e00?)
	net/http/server.go:2122 +0x2f
github.com/owncloud/ocis/v2/services/proxy/pkg/middleware.selectorCookie.ServeHTTP({{0x423e0e0, 0xc00169ed80}, {{{0x4246308, 0xc0016c5580}, 0x1, {0x0, 0x0}, {0xc0001a0000, 0x12, 0x1f4}, ...}}, ...}, ...)
	github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/selector_cookie.go:36 +0x28d
github.com/owncloud/ocis/v2/services/proxy/pkg/middleware.accountResolver.ServeHTTP({{0x4237360, 0xc001715a70}, {{{0x4246308, 0xc0016c5580}, 0x1, {0x0, 0x0}, {0xc0001a0000, 0x12, 0x1f4}, ...}}, ...}, ...)
	github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/account_resolver.go:132 +0xa49
github.com/owncloud/ocis/v2/services/proxy/pkg/middleware.Authentication.func1.1({0x7fbea8ca97c0, 0xc0014eb680}, 0xc001dbc200)
	github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/authentication.go:64 +0x1fa
net/http.HandlerFunc.ServeHTTP(0x42530d8?, {0x7fbea8ca97c0?, 0xc0014eb680?}, 0x5cb45b8?)
	net/http/server.go:2122 +0x2f
github.com/owncloud/ocis/v2/services/proxy/pkg/router.Middleware.func1.1({0x7fbea8ca97c0, 0xc0014eb680}, 0xc001dbc100)
	github.com/owncloud/ocis/v2/services/proxy/pkg/router/router.go:31 +0x205
net/http.HandlerFunc.ServeHTTP(0xc0018f28a4?, {0x7fbea8ca97c0?, 0xc0014eb680?}, 0xc000090730?)
	net/http/server.go:2122 +0x2f
github.com/owncloud/ocis/v2/services/proxy/pkg/middleware.OIDCWellKnownRewrite.func1.1({0x7fbea8ca97c0, 0xc0014eb680}, 0xc001dbc100?)
	github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/oidc_well-known.go:45 +0x313
net/http.HandlerFunc.ServeHTTP(0xc001e02390?, {0x7fbea8ca97c0?, 0xc0014eb680?}, 0xc6ca05?)
	net/http/server.go:2122 +0x2f
github.com/owncloud/ocis/v2/services/proxy/pkg/middleware.HTTPSRedirect.func1({0x7fbea8ca97c0, 0xc0014eb680}, 0xc001dbc100)
	github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/https_redirect.go:17 +0x142
net/http.HandlerFunc.ServeHTTP(0x4250c00?, {0x7fbea8ca97c0?, 0xc0014eb680?}, 0xc001dbc100?)
	net/http/server.go:2122 +0x2f
github.com/owncloud/ocis/v2/services/proxy/pkg/middleware.AccessLog.func1.1({0x4250c00, 0xc001d267e0}, 0xc001dbc100)
	github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/accesslog.go:17 +0xc8
net/http.HandlerFunc.ServeHTTP(0x4253030?, {0x4250c00?, 0xc001d267e0?}, 0x39cf1b0?)
	net/http/server.go:2122 +0x2f
github.com/go-chi/chi/v5/middleware.RequestID.func1({0x4250c00, 0xc001d267e0}, 0xc00218ff00)
	github.com/go-chi/chi/v5@v5.0.8/middleware/request_id.go:76 +0x22d
net/http.HandlerFunc.ServeHTTP(0xc00218ff00?, {0x4250c00?, 0xc001d267e0?}, 0xc001649400?)
	net/http/server.go:2122 +0x2f
github.com/go-chi/chi/v5/middleware.RealIP.func1({0x4250c00, 0xc001d267e0}, 0xc00218ff00)
	github.com/go-chi/chi/v5@v5.0.8/middleware/realip.go:36 +0x9e
net/http.HandlerFunc.ServeHTTP(0x57052b?, {0x4250c00?, 0xc001d267e0?}, 0x4252520?)
	net/http/server.go:2122 +0x2f
github.com/owncloud/ocis/v2/ocis-pkg/middleware.TraceContext.func1({0x4250c00, 0xc001d267e0}, 0xc00218fe00)
	github.com/owncloud/ocis/v2/ocis-pkg/middleware/tracing.go:19 +0x184
net/http.HandlerFunc.ServeHTTP(0x0?, {0x4250c00?, 0xc001d267e0?}, 0x46f9d0?)
	net/http/server.go:2122 +0x2f
net/http.serverHandler.ServeHTTP({0xc001e02360?}, {0x4250c00, 0xc001d267e0}, 0xc00218fe00)
	net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc00082f4d0, {0x42530d8, 0xc000835bf0})
	net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
	net/http/server.go:3089 +0x5ed
```

## Steps to reproduce

1. Enable OIDC role driver
2. Have a token without roles

## Expected behavior
No stack trace

## Actual behavior
Stack trace

## Setup

3.0.0-alpha.2

## Additional context
Can be check with the Keycloak deployment example (just remove a role from the user)

**Comment by rhafer** [comment]
This seems to be fixed meanwhile. It works with current master and 5.0.x (didn't check the 4.0 releases)
