### ISSUE TITLE
Login fails runtime error: invalid memory

### ISSUE THREAD

**Issue by jamu85** [owncloud/ocis#626]
Found issue https://github.com/owncloud/ocis/issues/463 which was closed but it's still reproducible on my test setup

Setup is Traefik image with Letsencrypt certificate in front of ocis:latest image deployed on a hcloud node 

The node is available under https://ocis-traefik-demo.owncloud.works

The compose file is located in /home/jmueller/compose-playground/examples/ocis-traefik 

The application is started as deamon and should provide logs via `docker logs ocis` 

Debug User is created and key will be provided to someone who can debug

```
ocis       | 2020-09-29 10:55:21.286265 I | http: panic serving 172.18.0.2:56254: runtime error: invalid memory address or nil pointer dereference
ocis       | goroutine 115 [running]:
ocis       | net/http.(*conn).serve.func1(0xc0003bb4a0)
ocis       | 	/usr/local/go/src/net/http/server.go:1767 +0x139
ocis       | panic(0x344c4a0, 0x541ceb0)
ocis       | 	/usr/local/go/src/runtime/panic.go:679 +0x1b2
ocis       | github.com/coreos/go-oidc.(*Provider).UserInfo(0x0, 0x3e65520, 0xc0017d8720, 0x3e098a0, 0xc0016936e0, 0x0, 0x0, 0x0)
ocis       | 	/srv/app/pkg/mod/github.com/coreos/go-oidc@v2.2.1+incompatible/oidc.go:205 +0x51
ocis       | github.com/owncloud/ocis/proxy/pkg/middleware.OpenIDConnect.func1.1(0x3e57f20, 0xc00101f5e0, 0xc0017b2a00)
ocis       | 	/drone/src/proxy/pkg/middleware/openidconnect.go:75 +0x24d
ocis       | net/http.HandlerFunc.ServeHTTP(0xc00030bbf0, 0x3e57f20, 0xc00101f5e0, 0xc0017b2a00)
ocis       | 	/usr/local/go/src/net/http/server.go:2007 +0x44
ocis       | github.com/owncloud/ocis/proxy/pkg/middleware.RedirectToHTTPS.func1(0x3e57f20, 0xc00101f5e0, 0xc0017b2a00)
ocis       | 	/drone/src/proxy/pkg/middleware/https_redirect.go:17 +0x1b4
ocis       | net/http.HandlerFunc.ServeHTTP(0xc0003b6be0, 0x3e57f20, 0xc00101f5e0, 0xc0017b2a00)
ocis       | 	/usr/local/go/src/net/http/server.go:2007 +0x44
ocis       | net/http.serverHandler.ServeHTTP(0xc0002480e0, 0x3e57f20, 0xc00101f5e0, 0xc0017b2a00)
ocis       | 	/usr/local/go/src/net/http/server.go:2802 +0xa4
ocis       | net/http.(*conn).serve(0xc0003bb4a0, 0x3e65460, 0xc000ad0280)
ocis       | 	/usr/local/go/src/net/http/server.go:1890 +0x875
ocis       | created by net/http.(*Server).Serve
ocis       | 	/usr/local/go/src/net/http/server.go:2927 +0x38e
ocis       | 2020-09-29 10:55:21.288787 I | http: panic serving 172.18.0.2:56246: runtime error: invalid memory address or nil pointer dereference
ocis       | goroutine 74 [running]:
ocis       | net/http.(*conn).serve.func1(0xc0004d86e0)
ocis       | 	/usr/local/go/src/net/http/server.go:1767 +0x139
ocis       | panic(0x344c4a0, 0x541ceb0)
ocis       | 	/usr/local/go/src/runtime/panic.go:679 +0x1b2
ocis       | github.com/coreos/go-oidc.(*Provider).UserInfo(0x0, 0x3e65520, 0xc0016e9650, 0x3e098a0, 0xc00172ea80, 0x0, 0x0, 0x0)
ocis       | 	/srv/app/pkg/mod/github.com/coreos/go-oidc@v2.2.1+incompatible/oidc.go:205 +0x51
ocis       | github.com/owncloud/ocis/proxy/pkg/middleware.OpenIDConnect.func1.1(0x3e57f20, 0xc001790620, 0xc001711700)
ocis       | 	/drone/src/proxy/pkg/middleware/openidconnect.go:75 +0x24d
ocis       | net/http.HandlerFunc.ServeHTTP(0xc00030bbf0, 0x3e57f20, 0xc001790620, 0xc001711700)
ocis       | 	/usr/local/go/src/net/http/server.go:2007 +0x44
ocis       | github.com/owncloud/ocis/proxy/pkg/middleware.RedirectToHTTPS.func1(0x3e57f20, 0xc001790620, 0xc001711700)
ocis       | 	/drone/src/proxy/pkg/middleware/https_redirect.go:17 +0x1b4
ocis       | net/http.HandlerFunc.ServeHTTP(0xc0003b6be0, 0x3e57f20, 0xc001790620, 0xc001711700)
ocis       | 	/usr/local/go/src/net/http/server.go:2007 +0x44
ocis       | net/http.serverHandler.ServeHTTP(0xc0002480e0, 0x3e57f20, 0xc001790620, 0xc001711700)
ocis       | 	/usr/local/go/src/net/http/server.go:2802 +0xa4
ocis       | net/http.(*conn).serve(0xc0004d86e0, 0x3e65460, 0xc0008756c0)
ocis       | 	/usr/local/go/src/net/http/server.go:1890 +0x875
ocis       | created by net/http.(*Server).Serve
ocis       | 	/usr/local/go/src/net/http/server.go:2927 +0x38e
ocis       | 2020-09-29 10:55:21.291105 I | http: panic serving 172.18.0.2:56258: runtime error: invalid memory address or nil pointer dereference
ocis       | goroutine 113 [running]:
ocis       | net/http.(*conn).serve.func1(0xc0004d90e0)
ocis       | 	/usr/local/go/src/net/http/server.go:1767 +0x139
ocis       | panic(0x344c4a0, 0x541ceb0)
ocis       | 	/usr/local/go/src/runtime/panic.go:679 +0x1b2
ocis       | github.com/coreos/go-oidc.(*Provider).UserInfo(0x0, 0x3e65520, 0xc0016e96e0, 0x3e098a0, 0xc00172eae0, 0x0, 0x0, 0x0)
ocis       | 	/srv/app/pkg/mod/github.com/coreos/go-oidc@v2.2.1+incompatible/oidc.go:205 +0x51
ocis       | github.com/owncloud/ocis/proxy/pkg/middleware.OpenIDConnect.func1.1(0x3e57f20, 0xc001790700, 0xc001711400)
ocis       | 	/drone/src/proxy/pkg/middleware/openidconnect.go:75 +0x24d
ocis       | net/http.HandlerFunc.ServeHTTP(0xc00030bbf0, 0x3e57f20, 0xc001790700, 0xc001711400)
ocis       | 	/usr/local/go/src/net/http/server.go:2007 +0x44
ocis       | github.com/owncloud/ocis/proxy/pkg/middleware.RedirectToHTTPS.func1(0x3e57f20, 0xc001790700, 0xc001711400)
ocis       | 	/drone/src/proxy/pkg/middleware/https_redirect.go:17 +0x1b4
ocis       | net/http.HandlerFunc.ServeHTTP(0xc0003b6be0, 0x3e57f20, 0xc001790700, 0xc001711400)
ocis       | 	/usr/local/go/src/net/http/server.go:2007 +0x44
ocis       | net/http.serverHandler.ServeHTTP(0xc0002480e0, 0x3e57f20, 0xc001790700, 0xc001711400)
ocis       | 	/usr/local/go/src/net/http/server.go:2802 +0xa4
ocis       | net/http.(*conn).serve(0xc0004d90e0, 0x3e65460, 0xc000c9a040)
ocis       | 	/usr/local/go/src/net/http/server.go:1890 +0x875
ocis       | created by net/http.(*Server).Serve
ocis       | 	/usr/local/go/src/net/http/server.go:2927 +0x38e
ocis       | 2020-09-29 10:55:21.293944 I | http: panic serving 172.18.0.2:56262: runtime error: invalid memory address or nil pointer dereference
ocis       | goroutine 122 [running]:
ocis       | net/http.(*conn).serve.func1(0xc0003bb720)
ocis       | 	/usr/local/go/src/net/http/server.go:1767 +0x139
ocis       | panic(0x344c4a0, 0x541ceb0)
ocis       | 	/usr/local/go/src/runtime/panic.go:679 +0x1b2
ocis       | github.com/coreos/go-oidc.(*Provider).UserInfo(0x0, 0x3e65520, 0xc0017d8810, 0x3e098a0, 0xc001693740, 0x0, 0x0, 0x0)
ocis       | 	/srv/app/pkg/mod/github.com/coreos/go-oidc@v2.2.1+incompatible/oidc.go:205 +0x51
ocis       | github.com/owncloud/ocis/proxy/pkg/middleware.OpenIDConnect.func1.1(0x3e57f20, 0xc00101f6c0, 0xc001711800)
ocis       | 	/drone/src/proxy/pkg/middleware/openidconnect.go:75 +0x24d
ocis       | net/http.HandlerFunc.ServeHTTP(0xc00030bbf0, 0x3e57f20, 0xc00101f6c0, 0xc001711800)
ocis       | 	/usr/local/go/src/net/http/server.go:2007 +0x44
ocis       | github.com/owncloud/ocis/proxy/pkg/middleware.RedirectToHTTPS.func1(0x3e57f20, 0xc00101f6c0, 0xc001711800)
ocis       | 	/drone/src/proxy/pkg/middleware/https_redirect.go:17 +0x1b4
ocis       | net/http.HandlerFunc.ServeHTTP(0xc0003b6be0, 0x3e57f20, 0xc00101f6c0, 0xc001711800)
ocis       | 	/usr/local/go/src/net/http/server.go:2007 +0x44
ocis       | net/http.serverHandler.ServeHTTP(0xc0002480e0, 0x3e57f20, 0xc00101f6c0, 0xc001711800)
ocis       | 	/usr/local/go/src/net/http/server.go:2802 +0xa4
ocis       | net/http.(*conn).serve(0xc0003bb720, 0x3e65460, 0xc000ad06c0)
ocis       | 	/usr/local/go/src/net/http/server.go:1890 +0x875
ocis       | created by net/http.(*Server).Serve
ocis       | 	/usr/local/go/src/net/http/server.go:2927 +0x38e
ocis       | 2020-09-29 10:55:21.296446 I | http: panic serving 172.18.0.2:56252: runtime error: invalid memory address or nil pointer dereference
ocis       | goroutine 114 [running]:
ocis       | net/http.(*conn).serve.func1(0xc0003bb400)
ocis       | 	/usr/local/go/src/net/http/server.go:1767 +0x139
ocis       | panic(0x344c4a0, 0x541ceb0)
ocis       | 	/usr/local/go/src/runtime/panic.go:679 +0x1b2
ocis       | github.com/coreos/go-oidc.(*Provider).UserInfo(0x0, 0x3e65520, 0xc0016e97d0, 0x3e098a0, 0xc00172eb40, 0x0, 0x0, 0x0)
ocis       | 	/srv/app/pkg/mod/github.com/coreos/go-oidc@v2.2.1+incompatible/oidc.go:205 +0x51
ocis       | github.com/owncloud/ocis/proxy/pkg/middleware.OpenIDConnect.func1.1(0x3e57f20, 0xc0017907e0, 0xc0017b2100)
ocis       | 	/drone/src/proxy/pkg/middleware/openidconnect.go:75 +0x24d
ocis       | net/http.HandlerFunc.ServeHTTP(0xc00030bbf0, 0x3e57f20, 0xc0017907e0, 0xc0017b2100)
ocis       | 	/usr/local/go/src/net/http/server.go:2007 +0x44
ocis       | github.com/owncloud/ocis/proxy/pkg/middleware.RedirectToHTTPS.func1(0x3e57f20, 0xc0017907e0, 0xc0017b2100)
ocis       | 	/drone/src/proxy/pkg/middleware/https_redirect.go:17 +0x1b4
ocis       | net/http.HandlerFunc.ServeHTTP(0xc0003b6be0, 0x3e57f20, 0xc0017907e0, 0xc0017b2100)
ocis       | 	/usr/local/go/src/net/http/server.go:2007 +0x44
ocis       | net/http.serverHandler.ServeHTTP(0xc0002480e0, 0x3e57f20, 0xc0017907e0, 0xc0017b2100)
ocis       | 	/usr/local/go/src/net/http/server.go:2802 +0xa4
ocis       | net/http.(*conn).serve(0xc0003bb400, 0x3e65460, 0xc000ad0340)
ocis       | 	/usr/local/go/src/net/http/server.go:1890 +0x875
ocis       | created by net/http.(*Server).Serve
ocis       | 	/usr/local/go/src/net/http/server.go:2927 +0x38e
ocis       | 2020-09-29 10:55:21.300192 I | http: panic serving 172.18.0.2:56250: runtime error: invalid memory address or nil pointer dereference
ocis       | goroutine 97 [running]:
ocis       | net/http.(*conn).serve.func1(0xc0003bb360)
ocis       | 	/usr/local/go/src/net/http/server.go:1767 +0x139
ocis       | panic(0x344c4a0, 0x541ceb0)
ocis       | 	/usr/local/go/src/runtime/panic.go:679 +0x1b2
ocis       | github.com/coreos/go-oidc.(*Provider).UserInfo(0x0, 0x3e65520, 0xc0017d88a0, 0x3e098a0, 0xc0016937a0, 0x0, 0x0, 0x0)
ocis       | 	/srv/app/pkg/mod/github.com/coreos/go-oidc@v2.2.1+incompatible/oidc.go:205 +0x51
ocis       | github.com/owncloud/ocis/proxy/pkg/middleware.OpenIDConnect.func1.1(0x3e57f20, 0xc00101f7a0, 0xc001711300)
ocis       | 	/drone/src/proxy/pkg/middleware/openidconnect.go:75 +0x24d
ocis       | net/http.HandlerFunc.ServeHTTP(0xc00030bbf0, 0x3e57f20, 0xc00101f7a0, 0xc001711300)
ocis       | 	/usr/local/go/src/net/http/server.go:2007 +0x44
ocis       | github.com/owncloud/ocis/proxy/pkg/middleware.RedirectToHTTPS.func1(0x3e57f20, 0xc00101f7a0, 0xc001711300)
ocis       | 	/drone/src/proxy/pkg/middleware/https_redirect.go:17 +0x1b4
ocis       | net/http.HandlerFunc.ServeHTTP(0xc0003b6be0, 0x3e57f20, 0xc00101f7a0, 0xc001711300)
ocis       | 	/usr/local/go/src/net/http/server.go:2007 +0x44
ocis       | net/http.serverHandler.ServeHTTP(0xc0002480e0, 0x3e57f20, 0xc00101f7a0, 0xc001711300)
ocis       | 	/usr/local/go/src/net/http/server.go:2802 +0xa4
ocis       | net/http.(*conn).serve(0xc0003bb360, 0x3e65460, 0xc000ad01c0)
ocis       | 	/usr/local/go/src/net/http/server.go:1890 +0x875
ocis       | created by net/http.(*Server).Serve
ocis       | 	/usr/local/go/src/net/http/server.go:2927 +0x38e
ocis       | 2020-09-29 10:55:21.302681 I | http: panic serving 172.18.0.2:56284: runtime error: invalid memory address or nil pointer dereference
ocis       | goroutine 304 [running]:
ocis       | net/http.(*conn).serve.func1(0xc0017f0320)
ocis       | 	/usr/local/go/src/net/http/server.go:1767 +0x139
ocis       | panic(0x344c4a0, 0x541ceb0)
ocis       | 	/usr/local/go/src/runtime/panic.go:679 +0x1b2
ocis       | github.com/coreos/go-oidc.(*Provider).UserInfo(0x0, 0x3e65520, 0xc0017d8a20, 0x3e098a0, 0xc001693800, 0x0, 0x0, 0x0)
ocis       | 	/srv/app/pkg/mod/github.com/coreos/go-oidc@v2.2.1+incompatible/oidc.go:205 +0x51
ocis       | github.com/owncloud/ocis/proxy/pkg/middleware.OpenIDConnect.func1.1(0x3e57f20, 0xc00101f880, 0xc0017fa400)
ocis       | 	/drone/src/proxy/pkg/middleware/openidconnect.go:75 +0x24d
ocis       | net/http.HandlerFunc.ServeHTTP(0xc00030bbf0, 0x3e57f20, 0xc00101f880, 0xc0017fa400)
ocis       | 	/usr/local/go/src/net/http/server.go:2007 +0x44
ocis       | github.com/owncloud/ocis/proxy/pkg/middleware.RedirectToHTTPS.func1(0x3e57f20, 0xc00101f880, 0xc0017fa400)
ocis       | 	/drone/src/proxy/pkg/middleware/https_redirect.go:17 +0x1b4
ocis       | net/http.HandlerFunc.ServeHTTP(0xc0003b6be0, 0x3e57f20, 0xc00101f880, 0xc0017fa400)
ocis       | 	/usr/local/go/src/net/http/server.go:2007 +0x44
ocis       | net/http.serverHandler.ServeHTTP(0xc0002480e0, 0x3e57f20, 0xc00101f880, 0xc0017fa400)
ocis       | 	/usr/local/go/src/net/http/server.go:2802 +0xa4
ocis       | net/http.(*conn).serve(0xc0017f0320, 0x3e65460, 0xc0017ec3c0)
ocis       | 	/usr/local/go/src/net/http/server.go:1890 +0x875
ocis       | created by net/http.(*Server).Serve
ocis       | 	/usr/local/go/src/net/http/server.go:2927 +0x38e
ocis       | 2020-09-29T10:55:38Z DBG refreshing external service-registration service={"endpoints":[],"metadata":null,"name":"com.owncloud.reva","nodes":[{"address":"0.0.0.0:9142","id":"com.owncloud.reva-270209bc-e1b6-4acd-a26b-653cd11d1f0d","metadata":{"broker":"http","protocol":"grpc","registry":"mdns","server":"grpc","transport":"grpc"}}],"version":""}
ocis       | 2020-09-29T10:56:08Z DBG refreshing external service-registration service={"endpoints":[],"metadata":null,"name":"com.owncloud.reva","nodes":[{"address":"0.0.0.0:9142","id":"com.owncloud.reva-270209bc-e1b6-4acd-a26b-653cd11d1f0d","metadata":{"broker":"http","protocol":"grpc","registry":"mdns","server":"grpc","transport":"grpc"}}],"version":""}
```

**Comment by C0rby** [comment]
While logging in the following entry appears in the logs.
```
ocis       | 2020-09-29T14:30:14Z ERR could not initialize oidc provider error="Get https://ocis-traefik-demo.owncloud.works/.well-known/openid-configuration: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)" service=proxy
```

Turns out for some reason the container can't send requests to its external address (https://ocis-traefik-demo.owncloud.works).

**Comment by C0rby** [comment]
The error comes from here https://github.com/owncloud/ocis/blob/90cf51af789bdcd6aaa8f8019cdd770623a3cb1b/proxy/pkg/middleware/openidconnect.go#L58-L62

And I guess somehow this https://github.com/owncloud/ocis/blob/90cf51af789bdcd6aaa8f8019cdd770623a3cb1b/proxy/pkg/middleware/openidconnect.go#L75 gets invoked even though the `oidcProvider` is nil which is causing the stacktrace from above

**Comment by C0rby** [comment]
My guess is that if the container is able to send requests to `https://ocis-traefik-demo.owncloud.work` then it should work without problems.
