### ISSUE TITLE
Intermittent E2E tests failure on CI

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/ocis#6431]
## Describe 

Currently, the drone has started to fail intermittently on E2E tests while creating project space with HTTP status 403.
Build: https://drone.owncloud.com/owncloud/ocis/22862/89/9
https://drone.owncloud.com/owncloud/ocis/22792

```
1) Scenario: members of the space can control the versions of the files (attempt 1, retried) # tests/e2e/cucumber/features/smoke/spaces/project.ocis.feature:132
   ✔ Before # tests/e2e/cucumber/environment/index.ts:39
   ✔ Given "Admin" creates following users using API # tests/e2e/cucumber/steps/api.ts:10
       | id    |
       | Alice |
       | Brian |
       | Carol |
   ✔ And "Alice" logs in # tests/e2e/cucumber/steps/ui/session.ts:24
   ✔ And "Admin" assigns following roles to the users using API # tests/e2e/cucumber/steps/api.ts:22
       | id    | role        |
       | Alice | Space Admin |
   ✖ And "Alice" creates the following project space using API # tests/e2e/cucumber/steps/api.ts:137
       | name | id     |
       | team | team.1 |
       Error: HTTP Request Failed: Failed while creating a space project, Status: 403
           at checkResponseStatus (/drone/src/webTestRunner/tests/e2e/support/api/http.ts:34:15)
           at Object.createSpace (/drone/src/webTestRunner/tests/e2e/support/api/graph/spaces.ts:52:36)
           at processTicksAndRejections (node:internal/process/task_queues:95:5)
           at World.<anonymous> (/drone/src/webTestRunner/tests/e2e/cucumber/steps/api.ts:140:25)
   - And "Alice" navigates to the projects space page # tests/e2e/cucumber/steps/ui/spaces.ts:11
   - And "Alice" navigates to the project space "team.1" # tests/e2e/cucumber/steps/ui/spaces.ts:23
   - And "Alice" creates the following resources # tests/e2e/cucumber/steps/ui/resources.ts:36
       | resource            | type    | content             |
       | parent/textfile.txt | txtFile | some random content |
   - When "Alice" uploads the following resources # tests/e2e/cucumber/steps/ui/resources.ts:43
       | resource     | to     | option  |
       | textfile.txt | parent | replace |
   - And "Alice" adds following users to the project space # tests/e2e/cucumber/steps/ui/spaces.ts:54
       | user  | role   | kind |
       | Carol | viewer | user |
       | Brian | editor | user |
   - And "Alice" logs out # tests/e2e/cucumber/steps/ui/session.ts:33
   - When "Carol" logs in # tests/e2e/cucumber/steps/ui/session.ts:24
   - And "Carol" opens the "files" app # tests/e2e/cucumber/steps/ui/application.ts:10
   - And "Carol" navigates to the projects space page # tests/e2e/cucumber/steps/ui/spaces.ts:11
   - And "Carol" navigates to the project space "team.1" # tests/e2e/cucumber/steps/ui/spaces.ts:23
   - And "Carol" should not see the version of the file # tests/e2e/cucumber/steps/ui/resources.ts:397
       | resource     | to     |
       | textfile.txt | parent |
   - And "Carol" logs out # tests/e2e/cucumber/steps/ui/session.ts:33
   - When "Brian" logs in # tests/e2e/cucumber/steps/ui/session.ts:24
   - And "Brian" opens the "files" app # tests/e2e/cucumber/steps/ui/application.ts:10
   - And "Brian" navigates to the projects space page # tests/e2e/cucumber/steps/ui/spaces.ts:11
   - And "Brian" navigates to the project space "team.1" # tests/e2e/cucumber/steps/ui/spaces.ts:23
   - And "Brian" downloads old version of the following resource # tests/e2e/cucumber/steps/ui/resources.ts:132
       | resource     | to     |
       | textfile.txt | parent |
   - And "Brian" restores following resources # tests/e2e/cucumber/steps/ui/resources.ts:114
       | resource     | to     | version |
       | textfile.txt | parent | 1       |
   - And "Brian" logs out # tests/e2e/cucumber/steps/ui/session.ts:33
   ✔ After # tests/e2e/cucumber/environment/index.ts:89

2) Scenario: public link for space (attempt 1, retried) # tests/e2e/cucumber/features/smoke/spaces/publicLink.ocis.feature:3
   ✔ Before # tests/e2e/cucumber/environment/index.ts:39
   ✔ Given "Admin" creates following users using API # tests/e2e/cucumber/steps/api.ts:10
       | id    |
       | Alice |
       | Brian |
       | Carol |
       | David |
   ✔ When "Alice" logs in # tests/e2e/cucumber/steps/ui/session.ts:24
   ✔ And "Admin" assigns following roles to the users using API # tests/e2e/cucumber/steps/api.ts:22
       | id    | role        |
       | Alice | Space Admin |
   ✖ And "Alice" creates the following project space using API # tests/e2e/cucumber/steps/api.ts:137
       | name | id     |
       | team | team.1 |
       Error: HTTP Request Failed: Failed while creating a space project, Status: 403
           at checkResponseStatus (/drone/src/webTestRunner/tests/e2e/support/api/http.ts:34:15)
           at Object.createSpace (/drone/src/webTestRunner/tests/e2e/support/api/graph/spaces.ts:52:36)
           at processTicksAndRejections (node:internal/process/task_queues:95:5)
           at World.<anonymous> (/drone/src/webTestRunner/tests/e2e/cucumber/steps/api.ts:140:25)
   - And "Alice" navigates to the projects space page # tests/e2e/cucumber/steps/ui/spaces.ts:11
   - And "Alice" navigates to the project space "team.1" # tests/e2e/cucumber/steps/ui/spaces.ts:23
   - And "Alice" creates the following resources # tests/e2e/cucumber/steps/ui/resources.ts:36
       | resource    | type   |
       | spaceFolder | folder |
   - And "Alice" creates a public link for the resource "spaceFolder" using the sidebar panel # tests/e2e/cucumber/steps/ui/links.ts:6
   - And "Alice" renames the most recently created public link of resource "spaceFolder" to "folderLink" # tests/e2e/cucumber/steps/ui/links.ts:19
   - And "Alice" adds following users to the project space # tests/e2e/cucumber/steps/ui/spaces.ts:54
       | user  | role    | kind |
       | Brian | editor  | user |
       | Carol | viewer  | user |
       | David | manager | user |
   - And "Alice" logs out # tests/e2e/cucumber/steps/ui/session.ts:33
   - When "Brian" logs in # tests/e2e/cucumber/steps/ui/session.ts:24
   - And "Brian" navigates to the projects space page # tests/e2e/cucumber/steps/ui/spaces.ts:11
   - And "Brian" navigates to the project space "team.1" # tests/e2e/cucumber/steps/ui/spaces.ts:23
   - And "Brian" should not be able to edit the public link named "folderLink" # tests/e2e/cucumber/steps/ui/links.ts:66
   - And "Brian" logs out # tests/e2e/cucumber/steps/ui/session.ts:33
   - When "David" logs in # tests/e2e/cucumber/steps/ui/session.ts:24
   - And "David" navigates to the projects space page # tests/e2e/cucumber/steps/ui/spaces.ts:11
   - And "David" navigates to the project space "team.1" # tests/e2e/cucumber/steps/ui/spaces.ts:23
   - And "David" edits the public link named "folderLink" of resource "spaceFolder" changing role to "editor" # tests/e2e/cucumber/steps/ui/links.ts:41
   - And "David" logs out # tests/e2e/cucumber/steps/ui/session.ts:33
   - When "Carol" logs in # tests/e2e/cucumber/steps/ui/session.ts:24
   - And "Carol" navigates to the projects space page # tests/e2e/cucumber/steps/ui/spaces.ts:11
   - And "Carol" navigates to the project space "team.1" # tests/e2e/cucumber/steps/ui/spaces.ts:23
   - And "Carol" should not be able to edit the public link named "folderLink" # tests/e2e/cucumber/steps/ui/links.ts:66
   - And "Carol" logs out # tests/e2e/cucumber/steps/ui/session.ts:33
   ✔ After # tests/e2e/cucumber/environment/index.ts:89
```

**Comment by SwikritiT** [comment]
Failing in this build too https://drone.owncloud.com/owncloud/ocis/22888/90/9

**Comment by SwikritiT** [comment]
keeps on failing on my PR: https://drone.owncloud.com/owncloud/ocis/22892/90/9
We need to make this p1 next week @grgprarup @saw-jan

**Comment by saw-jan** [comment]
Also, seen in https://drone.owncloud.com/owncloud/web/36274/8/13

**Comment by phil-davis** [comment]
Failed in PR #6408 

https://drone.owncloud.com/owncloud/ocis/22915/90/9
1) Scenario: public link for space (attempt 2) # tests/e2e/cucumber/features/smoke/spaces/publicLink.ocis.feature:3
```
...
And "Alice" creates the following project space using API # tests/e2e/cucumber/steps/api.ts:137
       | name | id     |
       | team | team.1 |
       Error: HTTP Request Failed: Failed while creating a space project, Status: 403
           at checkResponseStatus (/drone/src/webTestRunner/tests/e2e/support/api/http.ts:34:15)
```

**Comment by phil-davis** [comment]
Alice is already logged in.
Admin gives Alice a different role.
A very short time later (for example, the next test step), Alice tries to do something that needs the privileges of the new role.

I can see that that might be a problem - it might take some time (or some token change...) for the processing of an incoming request from Alice to know that Alice has a new role with more/different privileges. And so a test scenario that runs quickly might encounter such a timing window.
