### ISSUE TITLE
panic in gateway when making stat call

### ISSUE THREAD

**Issue by butonic** [owncloud/ocis#6519]
I was running a k6 load test and found this in the logs ...
```
github.com/cs3org/reva/v2/internal/grpc/services/gateway.(*cachedAPIClient).Stat(0xc0031db280, {0x4527528, 0xc0035fb0b0}, 0xc00297c7d0, {0x0, 0x0, 0x0})
	github.com/cs3org/reva/v2@v2.14.1-0.20230612154151-5fbd21b664e1/internal/grpc/services/gateway/storageprovidercache.go:94 +0x69
```
full stacktrace
```
{
  "level": "error",
  "service": "gateway",
  "pkg": "rgrpc",
  "traceid": "747d2ff7057814d7682fcf10570a7040",
  "time": "2023-06-13T15:24:51.998232448Z",
  "line": "github.com/cs3org/reva/v2@v2.14.1-0.20230612154151-5fbd21b664e1/internal/grpc/interceptors/recovery/recovery.go:50",
  "message": "user not found in context; stack: goroutine 267992 [running]:
runtime/debug.Stack()
	runtime/debug/stack.go:24 +0x65
github.com/cs3org/reva/v2/internal/grpc/interceptors/recovery.recoveryFunc({0x4527528, 0xc0035fae40}, {0x3e88d00, 0x44fc188})
	github.com/cs3org/reva/v2@v2.14.1-0.20230612154151-5fbd21b664e1/internal/grpc/interceptors/recovery/recovery.go:50 +0x5b
github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom({0x4527528?, 0xc0035fae40?}, {0x3e88d00?, 0x44fc188?}, 0x0?)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/recovery/interceptors.go:61 +0x36
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1.1()
	github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/recovery/interceptors.go:29 +0x7b
panic({0x3e88d00, 0x44fc188})
	runtime/panic.go:884 +0x213
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()
	go.opentelemetry.io/otel/sdk@v1.16.0/trace/span.go:383 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc00236e000, {0x0, 0x0, 0x40700a5710cf2f68?})
	go.opentelemetry.io/otel/sdk@v1.16.0/trace/span.go:421 +0xa29
panic({0x3e88d00, 0x44fc188})
	runtime/panic.go:884 +0x213
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()
	go.opentelemetry.io/otel/sdk@v1.16.0/trace/span.go:383 +0x2a
go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0xc00236e300, {0x0, 0x0, 0x417f50?})
	go.opentelemetry.io/otel/sdk@v1.16.0/trace/span.go:421 +0xa29
panic({0x3e88d00, 0x44fc188})
	runtime/panic.go:884 +0x213
github.com/cs3org/reva/v2/pkg/ctx.ContextMustGetUser({0x4527528?, 0xc0035fb0b0?})
	github.com/cs3org/reva/v2@v2.14.1-0.20230612154151-5fbd21b664e1/pkg/ctx/userctx.go:47 +0x65
github.com/cs3org/reva/v2/internal/grpc/services/gateway.(*cachedAPIClient).Stat(0xc0031db280, {0x4527528, 0xc0035fb0b0}, 0xc00297c7d0, {0x0, 0x0, 0x0})
	github.com/cs3org/reva/v2@v2.14.1-0.20230612154151-5fbd21b664e1/internal/grpc/services/gateway/storageprovidercache.go:94 +0x69
github.com/cs3org/reva/v2/internal/grpc/services/gateway.(*svc).Stat(0x0?, {0x4527528, 0xc0035fb0b0}, 0xc0040bbf90)
	github.com/cs3org/reva/v2@v2.14.1-0.20230612154151-5fbd21b664e1/internal/grpc/services/gateway/storageprovider.go:864 +0x23b
github.com/cs3org/go-cs3apis/cs3/gateway/v1beta1._GatewayAPI_Stat_Handler.func1({0x4527528, 0xc0035fb0b0}, {0x434fd20?, 0xc0040bbf90})
	github.com/cs3org/go-cs3apis@v0.0.0-20230516150832-730ac860c71d/cs3/gateway/v1beta1/gateway_api.pb.go:3014 +0x7b
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1({0x4527528, 0xc0035fae40}, {0x434fd20, 0xc0040bbf90}, 0xc0036cc820, 0xc0034bae88)
	go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.36.4/interceptor.go:341 +0x437
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x4527528?, 0xc0035fae40?}, {0x434fd20?, 0xc0040bbf90?})
	github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x4f
github.com/cs3org/reva/v2/internal/grpc/interceptors/prometheus.interceptorFromConfig.func1({0x4527528?, 0xc0035fae40?}, {0x434fd20?, 0xc0040bbf90?}, 0x3be78a0?, 0xc001764050?)
	github.com/cs3org/reva/v2@v2.14.1-0.20230612154151-5fbd21b664e1/internal/grpc/interceptors/prometheus/prometheus.go:72 +0x43
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x4527528?, 0xc0035fae40?}, {0x434fd20?, 0xc0040bbf90?})
	github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x4f
github.com/cs3org/reva/v2/internal/grpc/interceptors/auth.NewUnary.func2({0x4527528, 0xc0035fae40}, {0x434fd20, 0xc0040bbf90}, 0xc0036cc820, 0xc0031dab80)
	github.com/cs3org/reva/v2@v2.14.1-0.20230612154151-5fbd21b664e1/internal/grpc/interceptors/auth/auth.go:137 +0x651
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x4527528?, 0xc0035fae40?}, {0x434fd20?, 0xc0040bbf90?})
	github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x4f
github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1({0x4527528?, 0xc0035fae40?}, {0x434fd20?, 0xc0040bbf90?}, 0xc0021a5270?, 0x496b57?)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/recovery/interceptors.go:33 +0xc4
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x4527528?, 0xc0035fae40?}, {0x434fd20?, 0xc0040bbf90?})
	github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x4f
github.com/cs3org/reva/v2/internal/grpc/interceptors/log.NewUnary.func1({0x4527528, 0xc0035fae40}, {0x434fd20, 0xc0040bbf90}, 0xc0036cc820, 0xc0031dac00)
	github.com/cs3org/reva/v2@v2.14.1-0.20230612154151-5fbd21b664e1/internal/grpc/interceptors/log/log.go:39 +0x9a
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x4527528?, 0xc0035fae40?}, {0x434fd20?, 0xc0040bbf90?})
	github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x4f
github.com/cs3org/reva/v2/internal/grpc/interceptors/useragent.NewUnary.func1({0x4527528, 0xc0035fae40}, {0x434fd20, 0xc0040bbf90}, 0x1?, 0xc0031dac40)
	github.com/cs3org/reva/v2@v2.14.1-0.20230612154151-5fbd21b664e1/internal/grpc/interceptors/useragent/useragent.go:38 +0xf4
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x4527528?, 0xc0035fae40?}, {0x434fd20?, 0xc0040bbf90?})
	github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x4f
github.com/cs3org/reva/v2/internal/grpc/interceptors/token.NewUnary.func1({0x4527528, 0xc0035fadb0}, {0x434fd20, 0xc0040bbf90}, 0xc0016aa100?, 0xc0031dac80)
	github.com/cs3org/reva/v2@v2.14.1-0.20230612154151-5fbd21b664e1/internal/grpc/interceptors/token/token.go:44 +0x16d
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x4527528?, 0xc0035fadb0?}, {0x434fd20?, 0xc0040bbf90?})
	github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x4f
github.com/cs3org/reva/v2/internal/grpc/interceptors/appctx.NewUnary.func1({0x4527528, 0xc0035fad20}, {0x434fd20, 0xc0040bbf90}, 0xc0034bae88?, 0xc0031dacc0)
	github.com/cs3org/reva/v2@v2.14.1-0.20230612154151-5fbd21b664e1/internal/grpc/interceptors/appctx/appctx.go:51 +0x73c
github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2({0x4527528, 0xc0035fad20}, {0x434fd20, 0xc0040bbf90}, 0xc0036cc820, 0x3fd50e0?)
	github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:53 +0x14e
github.com/cs3org/go-cs3apis/cs3/gateway/v1beta1._GatewayAPI_Stat_Handler({0x44b1e40?, 0xc001762000}, {0x4527528, 0xc0035fad20}, 0xc00021e000, 0xc000ab7d40)
	github.com/cs3org/go-cs3apis@v0.0.0-20230516150832-730ac860c71d/cs3/gateway/v1beta1/gateway_api.pb.go:3016 +0x138
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0005641e0, {0x453a400, 0xc001c2b860}, 0xc002233c20, 0xc000ab7f80, 0x5dd91c0, 0x0)
	google.golang.org/grpc@v1.54.0/server.go:1345 +0xdf3
google.golang.org/grpc.(*Server).handleStream(0xc0005641e0, {0x453a400, 0xc001c2b860}, 0xc002233c20, 0x0)
	google.golang.org/grpc@v1.54.0/server.go:1722 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	google.golang.org/grpc@v1.54.0/server.go:966 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.54.0/server.go:964 +0x28a
"
}
```

**Comment by micbar** [comment]
`github.com/cs3org/reva/v2@v2.14.1-0.20230612154151-5fbd21b664e1/pkg/ctx/userctx.go:47 +0x65`

**Comment by kobergj** [comment]
I strongly this is fixed after a year. Closing.
