### ISSUE TITLE
Server panic when setting a password on a public link of a previously deleted file

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#6929]
ocis fresh master[4660a070e500](https://hub.docker.com/layers/owncloud/ocis/latest/images/sha256-d0fc0ebac72b5ea1f4150346dedc14701d6785d8709dae841e8e0c5ce18a9a55?context=explore)
in my configuration start with keycloak https://github.com/owncloud/ocis/blob/master/deployments/examples/ocis_keycloak/docker-compose.yml

Steps: 
- Create a file namend 'a.txt'
- Create public link
- Delete the file

- Create a file namend 'a.txt'
- Create public link
- Add password to the public link -> error

Actual: 502 error. server panic

https://github.com/owncloud/ocis/assets/84779829/c1316236-269b-4e0e-ba64-b6bcbbe0d7c5

log: 
```
2023/07/31 15:21:51 http: panic serving 127.0.0.1:35740: runtime error: invalid memory address or nil pointer dereference

goroutine 6588 [running]:

net/http.(*conn).serve.func1()

net/http/server.go:1854 +0xb0

panic({0x3cbb480, 0x5a53ca0})

runtime/panic.go:890 +0x258

go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()

go.opentelemetry.io/otel/sdk@v1.16.0/trace/span.go:383 +0x2c

go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0x40015c7c80, {0x0, 0x0, 0x1?})

go.opentelemetry.io/otel/sdk@v1.16.0/trace/span.go:421 +0x87c

panic({0x3cbb480, 0x5a53ca0})

runtime/panic.go:884 +0x204

go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()

go.opentelemetry.io/otel/sdk@v1.16.0/trace/span.go:383 +0x2c

go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0x40015c7e00, {0x0, 0x0, 0x1?})

go.opentelemetry.io/otel/sdk@v1.16.0/trace/span.go:421 +0x87c

panic({0x3cbb480, 0x5a53ca0})

runtime/panic.go:884 +0x204

go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()

go.opentelemetry.io/otel/sdk@v1.16.0/trace/span.go:383 +0x2c

go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0x40011ec300, {0x0, 0x0, 0x1?})

go.opentelemetry.io/otel/sdk@v1.16.0/trace/span.go:421 +0x87c

panic({0x3cbb480, 0x5a53ca0})

runtime/panic.go:884 +0x204

go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()

go.opentelemetry.io/otel/sdk@v1.16.0/trace/span.go:383 +0x2c

go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0x40011ec780, {0x0, 0x0, 0x1?})

go.opentelemetry.io/otel/sdk@v1.16.0/trace/span.go:421 +0x87c

panic({0x3cbb480, 0x5a53ca0})

runtime/panic.go:884 +0x204

go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()

go.opentelemetry.io/otel/sdk@v1.16.0/trace/span.go:383 +0x2c

go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0x40011ec900, {0x0, 0x0, 0x1?})

go.opentelemetry.io/otel/sdk@v1.16.0/trace/span.go:421 +0x87c

panic({0x3cbb480, 0x5a53ca0})

runtime/panic.go:884 +0x204

go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()

go.opentelemetry.io/otel/sdk@v1.16.0/trace/span.go:383 +0x2c

go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0x40011ecc00, {0x0, 0x0, 0x1?})

go.opentelemetry.io/otel/sdk@v1.16.0/trace/span.go:421 +0x87c

panic({0x3cbb480, 0x5a53ca0})

runtime/panic.go:884 +0x204

go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End.func1()

go.opentelemetry.io/otel/sdk@v1.16.0/trace/span.go:383 +0x2c

go.opentelemetry.io/otel/sdk/trace.(*recordingSpan).End(0x40011ecd80, {0x0, 0x0, 0x725f70?})

go.opentelemetry.io/otel/sdk@v1.16.0/trace/span.go:421 +0x87c

panic({0x3cbb480, 0x5a53ca0})

runtime/panic.go:884 +0x204

github.com/cs3org/reva/v2/internal/http/services/owncloud/ocs/handlers/apps/sharing/shares.(*Handler).updatePublicShare(0x4000c70140, {0xffff5b0fcba0, 0x40038c8f00}, 0x4003192100, 0x4002894000)

github.com/cs3org/reva/v2@v2.15.1-0.20230731073021-26b2f3432d11/internal/http/services/owncloud/ocs/handlers/apps/sharing/shares/public.go:419 +0xa64

github.com/cs3org/reva/v2/internal/http/services/owncloud/ocs/handlers/apps/sharing/shares.(*Handler).UpdateShare(0x40038c95f0?, {0xffff5b0fcba0, 0x40038c8f00}, 0x8?)

github.com/cs3org/reva/v2@v2.15.1-0.20230731073021-26b2f3432d11/internal/http/services/owncloud/ocs/handlers/apps/sharing/shares/shares.go:693 +0xec

net/http.HandlerFunc.ServeHTTP(0x3c8aa20?, {0xffff5b0fcba0?, 0x40038c8f00?}, 0x4003db7720?)

net/http/server.go:2122 +0x38

github.com/go-chi/chi/v5.(*Mux).routeHTTP(0x4001d21f80, {0xffff5b0fcba0, 0x40038c8f00}, 0x4003192100)

github.com/go-chi/chi/v5@v5.0.8/mux.go:444 +0x22c

net/http.HandlerFunc.ServeHTTP(0x4003bec128?, {0xffff5b0fcba0?, 0x40038c8f00?}, 0x4003bec108?)

net/http/server.go:2122 +0x38

github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0x4001d21f80, {0xffff5b0fcba0, 0x40038c8f00}, 0x4003192100)

github.com/go-chi/chi/v5@v5.0.8/mux.go:73 +0x328

github.com/go-chi/chi/v5.(*Mux).Mount.func1({0xffff5b0fcba0, 0x40038c8f00}, 0x4003192100)

github.com/go-chi/chi/v5@v5.0.8/mux.go:316 +0x1ec

net/http.HandlerFunc.ServeHTTP(0x3c8aa20?, {0xffff5b0fcba0?, 0x40038c8f00?}, 0x4002aa8b40?)

net/http/server.go:2122 +0x38

github.com/go-chi/chi/v5.(*Mux).routeHTTP(0x4001d21f20, {0xffff5b0fcba0, 0x40038c8f00}, 0x4003192100)

github.com/go-chi/chi/v5@v5.0.8/mux.go:444 +0x22c

net/http.HandlerFunc.ServeHTTP(0x4003bec2b8?, {0xffff5b0fcba0?, 0x40038c8f00?}, 0x4003bec298?)

net/http/server.go:2122 +0x38

github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0x4001d21f20, {0xffff5b0fcba0, 0x40038c8f00}, 0x4003192100)

github.com/go-chi/chi/v5@v5.0.8/mux.go:73 +0x328

github.com/go-chi/chi/v5.(*Mux).Mount.func1({0xffff5b0fcba0, 0x40038c8f00}, 0x4003192100)

github.com/go-chi/chi/v5@v5.0.8/mux.go:316 +0x1ec

net/http.HandlerFunc.ServeHTTP(0x3c8aa20?, {0xffff5b0fcba0?, 0x40038c8f00?}, 0x4003da8440?)

net/http/server.go:2122 +0x38

github.com/go-chi/chi/v5.(*Mux).routeHTTP(0x4001d21ec0, {0xffff5b0fcba0, 0x40038c8f00}, 0x4003192100)

github.com/go-chi/chi/v5@v5.0.8/mux.go:444 +0x22c

net/http.HandlerFunc.ServeHTTP(0x4214d88?, {0xffff5b0fcba0?, 0x40038c8f00?}, 0x38ef678?)

net/http/server.go:2122 +0x38

github.com/cs3org/reva/v2/internal/http/services/owncloud/ocs/response.VersionCtx.func1({0xffff5b0fcba0, 0x40038c8f00}, 0x4003192000)

github.com/cs3org/reva/v2@v2.15.1-0.20230731073021-26b2f3432d11/internal/http/services/owncloud/ocs/response/response.go:284 +0x234

net/http.HandlerFunc.ServeHTTP(0x40038c95f0?, {0xffff5b0fcba0?, 0x40038c8f00?}, 0x4003bec518?)

net/http/server.go:2122 +0x38

github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0x4001d21ec0, {0xffff5b0fcba0, 0x40038c8f00}, 0x4003192000)

github.com/go-chi/chi/v5@v5.0.8/mux.go:73 +0x328

github.com/go-chi/chi/v5.(*Mux).Mount.func1({0xffff5b0fcba0, 0x40038c8f00}, 0x4003192000)

github.com/go-chi/chi/v5@v5.0.8/mux.go:316 +0x1ec

net/http.HandlerFunc.ServeHTTP(0x3c8aa20?, {0xffff5b0fcba0?, 0x40038c8f00?}, 0x40038c48c8?)

net/http/server.go:2122 +0x38

github.com/go-chi/chi/v5.(*Mux).routeHTTP(0x4001d21e00, {0xffff5b0fcba0, 0x40038c8f00}, 0x4003192000)

github.com/go-chi/chi/v5@v5.0.8/mux.go:444 +0x22c

net/http.HandlerFunc.ServeHTTP(0x4214d88?, {0xffff5b0fcba0?, 0x40038c8f00?}, 0x5a522f0?)

net/http/server.go:2122 +0x38

github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0x4001d21e00, {0xffff5b0fcba0, 0x40038c8f00}, 0x4003cfdf00)

github.com/go-chi/chi/v5@v5.0.8/mux.go:90 +0x2e4

github.com/cs3org/reva/v2/internal/http/services/owncloud/ocs.(*svc).Handler.func1({0xffff5b0fcba0?, 0x40038c8f00}, 0x4003cfdf00)

github.com/cs3org/reva/v2@v2.15.1-0.20230731073021-26b2f3432d11/internal/http/services/owncloud/ocs/ocs.go:173 +0x17c

net/http.HandlerFunc.ServeHTTP(0x4002ad6880?, {0xffff5b0fcba0?, 0x40038c8f00?}, 0x4213ba0?)

net/http/server.go:2122 +0x38

github.com/cs3org/reva/v2/pkg/rhttp.traceHandler.func1({0xffff5b0fcba0, 0x40038c8f00}, 0x4003cfde00)

github.com/cs3org/reva/v2@v2.15.1-0.20230731073021-26b2f3432d11/pkg/rhttp/rhttp.go:316 +0x23c

net/http.HandlerFunc.ServeHTTP(0x40038c48c5?, {0xffff5b0fcba0?, 0x40038c8f00?}, 0x4003bec928?)

net/http/server.go:2122 +0x38

github.com/cs3org/reva/v2/pkg/rhttp.(*Server).getHandler.func1({0xffff5b0fcba0, 0x40038c8f00}, 0x4003cfde00)

github.com/cs3org/reva/v2@v2.15.1-0.20230731073021-26b2f3432d11/pkg/rhttp/rhttp.go:249 +0x194

net/http.HandlerFunc.ServeHTTP(0x4002ad6880?, {0xffff5b0fcba0?, 0x40038c8f00?}, 0x4213ba0?)

net/http/server.go:2122 +0x38

github.com/cs3org/reva/v2/pkg/rhttp.traceHandler.func1({0xffff5b0fcba0, 0x40038c8f00}, 0x4003cfdc00)

github.com/cs3org/reva/v2@v2.15.1-0.20230731073021-26b2f3432d11/pkg/rhttp/rhttp.go:316 +0x23c

net/http.HandlerFunc.ServeHTTP(0x4001d99140?, {0xffff5b0fcba0?, 0x40038c8f00?}, 0x4003cfdc00?)

net/http/server.go:2122 +0x38

github.com/rs/cors.(*Cors).Handler.func1({0xffff5b0fcba0, 0x40038c8f00}, 0x4003cfdc00)

github.com/rs/cors@v1.9.0/cors.go:236 +0x1e4

net/http.HandlerFunc.ServeHTTP(0x4002ad6880?, {0xffff5b0fcba0?, 0x40038c8f00?}, 0x4213ba0?)

net/http/server.go:2122 +0x38

github.com/cs3org/reva/v2/pkg/rhttp.traceHandler.func1({0xffff5b0fcba0, 0x40038c8f00}, 0x4003cfda00)

github.com/cs3org/reva/v2@v2.15.1-0.20230731073021-26b2f3432d11/pkg/rhttp/rhttp.go:316 +0x23c

net/http.HandlerFunc.ServeHTTP(0x4214d88?, {0xffff5b0fcba0?, 0x40038c8f00?}, 0x38f8270?)

net/http/server.go:2122 +0x38

github.com/go-chi/chi/v5/middleware.RequestID.func1({0xffff5b0fcba0, 0x40038c8f00}, 0x4003cfd900)

github.com/go-chi/chi/v5@v5.0.8/middleware/request_id.go:76 +0x214

net/http.HandlerFunc.ServeHTTP(0xf8?, {0xffff5b0fcba0?, 0x40038c8f00?}, 0x149fd70?)

net/http/server.go:2122 +0x38

github.com/cs3org/reva/v2/internal/http/interceptors/requestid.requestIDHandler.ServeHTTP(...)

github.com/cs3org/reva/v2@v2.15.1-0.20230731073021-26b2f3432d11/internal/http/interceptors/requestid/requestid.go:53

github.com/cs3org/reva/v2/pkg/rhttp.traceHandler.func1({0xffff5b0fcba0, 0x40038c8f00}, 0x4003cfd800)

github.com/cs3org/reva/v2@v2.15.1-0.20230731073021-26b2f3432d11/pkg/rhttp/rhttp.go:316 +0x23c

net/http.HandlerFunc.ServeHTTP(0xf8?, {0xffff5b0fcba0?, 0x40038c8f00?}, 0x93e0?)

net/http/server.go:2122 +0x38

github.com/cs3org/reva/v2/internal/http/interceptors/prometheus.prometheusHandler.ServeHTTP({{0x41fe7a0?, 0x4001499100?}, {0x421dc00?, 0x400195f980?}}, {0xffff5b0fcba0?, 0x40038c8f00?}, 0x4003becea8?)

github.com/cs3org/reva/v2@v2.15.1-0.20230731073021-26b2f3432d11/internal/http/interceptors/prometheus/prometheus.go:67 +0x50

github.com/cs3org/reva/v2/pkg/rhttp.traceHandler.func1({0xffff5b0fcba0, 0x40038c8f00}, 0x4003cfd700)

github.com/cs3org/reva/v2@v2.15.1-0.20230731073021-26b2f3432d11/pkg/rhttp/rhttp.go:316 +0x23c

net/http.HandlerFunc.ServeHTTP(0x40015c7e00?, {0xffff5b0fcba0?, 0x40038c8f00?}, 0x1?)

net/http/server.go:2122 +0x38

github.com/cs3org/reva/v2/internal/http/interceptors/auth.New.func2.1({0xffff5b0fcba0, 0x40038c8f00}, 0x4003cfd600)

github.com/cs3org/reva/v2@v2.15.1-0.20230731073021-26b2f3432d11/internal/http/interceptors/auth/auth.go:212 +0x628

net/http.HandlerFunc.ServeHTTP(0x4002ad6880?, {0xffff5b0fcba0?, 0x40038c8f00?}, 0x4213ba0?)

net/http/server.go:2122 +0x38

github.com/cs3org/reva/v2/pkg/rhttp.traceHandler.func1({0xffff5b0fcba0, 0x40038c8f00}, 0x4003cfd500)

github.com/cs3org/reva/v2@v2.15.1-0.20230731073021-26b2f3432d11/pkg/rhttp/rhttp.go:316 +0x23c

net/http.HandlerFunc.ServeHTTP(0x4212190?, {0xffff5b0fcba0?, 0x40038c8f00?}, 0x0?)

net/http/server.go:2122 +0x38

github.com/cs3org/reva/v2/internal/http/interceptors/log.loggingHandler.ServeHTTP({{0x41fe7a0?, 0x4001499180?}}, {0x4212190, 0x4002d5cc40}, 0x4003cfd500)

github.com/cs3org/reva/v2@v2.15.1-0.20230731073021-26b2f3432d11/internal/http/interceptors/log/log.go:57 +0xec

created by net/http.(*Server).Serve

net/http/server.go:3089 +0x520

2023/07/31 15:21:52 http: proxy error: EOF

{"level":"info","service":"proxy","proto":"HTTP/1.1","request-id":"d743c7f8-1379-4d7b-a847-1b384b58cbc6","remote-addr":"172.25.0.1","method":"PUT","status":502,"path":"/ocs/v1.php/apps/files_sharing/api/v1/shares/VFsgqxBWqRzSHqt","duration":30.865667,"bytes":0,"time":"2023-07-31T15:21:52.000103045Z","line":"github.com/owncloud/ocis/v2/services/proxy/pkg/middleware/accesslog.go:31","message":"access-log"}

```

**Comment by 2403905** [comment]
@ScharfViktor @JanAckermann  The cause of the HTTP error is here when we delete the file and create the new one the frontend still keeps data related to the old file until reloads a page.

https://github.com/owncloud/ocis/assets/11679989/27af6b46-a1ea-4c1d-a5b7-c6d6349470f5

**Comment by ScharfViktor** [comment]
This seems to be a web issue. web should not show the old link and request the backend to set the password of the old link

**Comment by 2403905** [comment]
@ScharfViktor It is also a backend issue. we have to prevent painc.

**Comment by 2403905** [comment]
[https://github.com/cs3org/reva/pull/4093](https://github.com/cs3org/reva/pull/4093)

**Comment by 2403905** [comment]
@ScharfViktor The reva fix already merged. 
@JanAckermann Please take a look at the frontend issue once you get a chance.

**Comment by individual-it** [comment]
ToDo QA-team: write API test for the panic

**Comment by ScharfViktor** [comment]
no panic when setting a password on a public link of deleted file
