### ISSUE TITLE
Access Denied / Exception on owncloud/ocis:latest (rc1)

### ISSUE THREAD

**Issue by biwerr** [owncloud/ocis#694]
I'm trying to get the RC1 running for some testing, but every time after login with moss:vista, i get a screen with access denied and the following output in the docker container logs. Seems there a some related issues #626 or #463, but can not find a fix :(

Due to this error `ocis_1   | 2020-10-13T13:49:27Z ERR could not initialize oidc provider error="oidc: issuer did not match the issuer returned by provider, expected \"https://localhost:9200\" got \"https://192.168.2.100:9200\"" service=proxy` if changed the entries in the config/identifier-registration.yml the ip from my docker host.

**Log:**
```
ocis_1   | 2020-10-13T12:52:32Z DBG director found path=/konnect/v1/token policy=reva prefix=/konnect/ routeType=prefix service=proxy
ocis_1   | 2020-10-13T12:52:32Z DBG identifier client lookup client_id=phoenix known=true redirect_uri=https://192.168.2.100:9200/oidc-callback.html service=konnectd trusted=false
ocis_1   | 2020-10-13T12:52:32Z DBG  bytes=1820 duration=5.718748 method=POST path=/konnect/v1/token proto=HTTP/1.1 request=6076ee3a-c46b-4b7a-9351-e635b92663ac service=konnectd status=200
ocis_1   | 2020-10-13T12:52:32Z DBG director found path=/konnect/v1/userinfo policy=reva prefix=/konnect/ routeType=prefix service=proxy
ocis_1   | 2020-10-13T12:52:32Z DBG Bind request basedn=dc=example,dc=org binddn=cn=konnectd,ou=sysusers,dc=example,dc=org handler=ocis service=glauth src={"IP":"127.0.0.1","Port":40496,"Zone":""}
ocis_1   | 2020-10-13T12:52:32Z DBG using query query={"conjuncts":[{"field":"bleve_type","term":"account"},{"field":"on_premises_sam_account_name","fuzziness":0,"match":"konnectd","prefix_length":0}]} service=accounts
ocis_1   | 2020-10-13T12:52:32Z DBG result result={"facets":null,"hits":[{"id":"820ba2a1-3f54-4538-80a4-2d73007e30bf","index":"/var/tmp/ocis-accounts/index.bleve","score":3.4921022015832683,"sort":["_score"]}],"max_score":3.4921022015832683,"request":{"explain":false,"facets":null,"fields":null,"from":0,"highlight":null,"includeLocations":false,"query":{"conjuncts":[{"field":"bleve_type","term":"account"},{"field":"on_premises_sam_account_name","fuzziness":0,"match":"konnectd","prefix_length":0}]},"search_after":null,"search_before":null,"size":10,"sort":["-_score"]},"status":{"failed":0,"successful":1,"total":1},"took":84323,"total_hits":1} service=accounts
ocis_1   | 2020-10-13T12:52:32Z INF access token is already provided pkg=rhttp service=storage traceid=fe5a8c4e29da81a673bbb7b3f27285c4
ocis_1   | 2020-10-13T12:52:32Z DBG http routing: head=data tail=/accounts/820ba2a1-3f54-4538-80a4-2d73007e30bf svc=data pkg=rhttp service=storage
ocis_1   | 2020-10-13T12:52:32Z INF http end="13/Oct/2020:12:52:32 +0000" host=127.0.0.1 method=GET pkg=rhttp proto=HTTP/1.1 service=storage size=440 start="13/Oct/2020:12:52:32 +0000" status=200 time_ns=381731 traceid=fe5a8c4e29da81a673bbb7b3f27285c4 uri=/data/accounts/820ba2a1-3f54-4538-80a4-2d73007e30bf url=/data/accounts/820ba2a1-3f54-4538-80a4-2d73007e30bf
ocis_1   | 2020-10-13T12:52:32Z DBG found account AccountEnabled=true CreatedDateTime=null DeletedDateTime=null Description= DisplayName="Kopano Konnectd" GidNumber=15000 Id=820ba2a1-3f54-4538-80a4-2d73007e30bf Identities=null IsResourceAccount=false Mail=idp@example.org MemberOf=[{"id":"34f38767-c937-4eb6-b847-1c175829a2a0"}] OnPremisesDistinguishedName= OnPremisesLastSyncDateTime=null OnPremisesSamAccountName=konnectd OnPremisesSecurityIdentifier= OnPremisesSyncEnabled=false OnPremisesUserPrincipalName= PreferredName=konnectd UidNumber=10000 service=accounts
ocis_1   | 2020-10-13T12:52:32Z INF access token is already provided pkg=rhttp service=storage traceid=04f1c318ffdec0b87309192c72f03cdb
ocis_1   | 2020-10-13T12:52:32Z DBG http routing: head=data tail=/groups/34f38767-c937-4eb6-b847-1c175829a2a0 svc=data pkg=rhttp service=storage
ocis_1   | 2020-10-13T12:52:32Z INF http end="13/Oct/2020:12:52:32 +0000" host=127.0.0.1 method=GET pkg=rhttp proto=HTTP/1.1 service=storage size=328 start="13/Oct/2020:12:52:32 +0000" status=200 time_ns=423595 traceid=04f1c318ffdec0b87309192c72f03cdb uri=/data/groups/34f38767-c937-4eb6-b847-1c175829a2a0 url=/data/groups/34f38767-c937-4eb6-b847-1c175829a2a0
ocis_1   | 2020-10-13T12:52:32Z DBG Bind success binddn=cn=konnectd,ou=sysusers,dc=example,dc=org handler=ocis service=glauth src={"IP":"127.0.0.1","Port":40496,"Zone":""}
ocis_1   | 2020-10-13T12:52:32Z DBG Search request basedn=dc=example,dc=org binddn=cn=konnectd,ou=sysusers,dc=example,dc=org filter=(objectClass=posixaccount) handler=ocis service=glauth src={"IP":"127.0.0.1","Port":40496,"Zone":""}
ocis_1   | 2020-10-13T12:52:32Z DBG parsed query basedn=dc=example,dc=org binddn=cn=konnectd,ou=sysusers,dc=example,dc=org filter=(objectClass=posixaccount) handler=ocis qtype=users query="on_premises_sam_account_name eq 'moss'" service=glauth
ocis_1   | 2020-10-13T12:52:32Z DBG using query query={"conjuncts":[{"field":"bleve_type","term":"account"},{"field":"on_premises_sam_account_name","fuzziness":0,"match":"moss","prefix_length":0}]} service=accounts
ocis_1   | 2020-10-13T12:52:32Z DBG result result={"facets":null,"hits":[{"id":"058bff95-6708-4fe5-91e4-9ea3d377588b","index":"/var/tmp/ocis-accounts/index.bleve","score":3.4921022015832683,"sort":["_score"]}],"max_score":3.4921022015832683,"request":{"explain":false,"facets":null,"fields":null,"from":0,"highlight":null,"includeLocations":false,"query":{"conjuncts":[{"field":"bleve_type","term":"account"},{"field":"on_premises_sam_account_name","fuzziness":0,"match":"moss","prefix_length":0}]},"search_after":null,"search_before":null,"size":10,"sort":["-_score"]},"status":{"failed":0,"successful":1,"total":1},"took":55233,"total_hits":1} service=accounts
ocis_1   | 2020-10-13T12:52:32Z INF access token is already provided pkg=rhttp service=storage traceid=321ab1f23812691b60a8fcb05ca21919
ocis_1   | 2020-10-13T12:52:32Z DBG http routing: head=data tail=/accounts/058bff95-6708-4fe5-91e4-9ea3d377588b svc=data pkg=rhttp service=storage
ocis_1   | 2020-10-13T12:52:32Z INF http end="13/Oct/2020:12:52:32 +0000" host=127.0.0.1 method=GET pkg=rhttp proto=HTTP/1.1 service=storage size=431 start="13/Oct/2020:12:52:32 +0000" status=200 time_ns=512100 traceid=321ab1f23812691b60a8fcb05ca21919 uri=/data/accounts/058bff95-6708-4fe5-91e4-9ea3d377588b url=/data/accounts/058bff95-6708-4fe5-91e4-9ea3d377588b
ocis_1   | 2020-10-13T12:52:32Z DBG found account AccountEnabled=true CreatedDateTime=null DeletedDateTime=null Description= DisplayName="Maurice Moss" GidNumber=30000 Id=058bff95-6708-4fe5-91e4-9ea3d377588b Identities=null IsResourceAccount=false Mail=moss@example.org MemberOf=[{"id":"509a9dcd-bb37-4f4f-a01a-19dca27d9cfa"}] OnPremisesDistinguishedName= OnPremisesLastSyncDateTime=null OnPremisesSamAccountName=moss OnPremisesSecurityIdentifier= OnPremisesSyncEnabled=false OnPremisesUserPrincipalName= PreferredName=moss UidNumber=20003 service=accounts
ocis_1   | 2020-10-13T12:52:32Z INF access token is already provided pkg=rhttp service=storage traceid=eb7e6bd42f975ddfb28a588f78c76210
ocis_1   | 2020-10-13T12:52:32Z DBG http routing: head=data tail=/groups/509a9dcd-bb37-4f4f-a01a-19dca27d9cfa svc=data pkg=rhttp service=storage
ocis_1   | 2020-10-13T12:52:32Z INF http end="13/Oct/2020:12:52:32 +0000" host=127.0.0.1 method=GET pkg=rhttp proto=HTTP/1.1 service=storage size=326 start="13/Oct/2020:12:52:32 +0000" status=200 time_ns=437578 traceid=eb7e6bd42f975ddfb28a588f78c76210 uri=/data/groups/509a9dcd-bb37-4f4f-a01a-19dca27d9cfa url=/data/groups/509a9dcd-bb37-4f4f-a01a-19dca27d9cfa
ocis_1   | 2020-10-13T12:52:32Z DBG AP: Search OK basedn=dc=example,dc=org binddn=cn=konnectd,ou=sysusers,dc=example,dc=org filter=(objectClass=posixaccount) handler=ocis num_entries=1 service=glauth src={"IP":"127.0.0.1","Port":40496,"Zone":""}
ocis_1   | 2020-10-13T12:52:32Z DBG  bytes=243 duration=17.297581 method=GET path=/konnect/v1/userinfo proto=HTTP/1.1 request=3db2a6d8-d2ec-48b8-a0a0-2c657bf17c4a service=konnectd status=200
ocis_1   | 2020-10-13 12:52:32.691787 I | http: panic serving 170.60.10.76:51516: runtime error: invalid memory address or nil pointer dereference
ocis_1   | goroutine 281 [running]:
ocis_1   | net/http.(*conn).serve.func1(0xc001432640)
ocis_1   |      /usr/local/go/src/net/http/server.go:1767 +0x139
ocis_1   | panic(0x346bf40, 0x544ef40)
ocis_1   |      /usr/local/go/src/runtime/panic.go:679 +0x1b2
ocis_1   | github.com/coreos/go-oidc.(*Provider).UserInfo(0x0, 0x3e8b400, 0xc0015963c0, 0x3e2f5c0, 0xc00156a420, 0x0, 0x0, 0x0)
ocis_1   |      /srv/app/pkg/mod/github.com/coreos/go-oidc@v2.2.1+incompatible/oidc.go:205 +0x51
ocis_1   | github.com/owncloud/ocis/proxy/pkg/middleware.OpenIDConnect.func1.1(0x3e7e040, 0xc001492ee0, 0xc001247800)
ocis_1   |      /drone/src/proxy/pkg/middleware/openidconnect.go:75 +0x24d
ocis_1   | net/http.HandlerFunc.ServeHTTP(0xc0013d9a10, 0x3e7e040, 0xc001492ee0, 0xc001247800)
ocis_1   |      /usr/local/go/src/net/http/server.go:2007 +0x44
ocis_1   | github.com/owncloud/ocis/proxy/pkg/middleware.RedirectToHTTPS.func1(0x3e7e040, 0xc001492ee0, 0xc001247800)
ocis_1   |      /drone/src/proxy/pkg/middleware/https_redirect.go:17 +0x1b4
ocis_1   | net/http.HandlerFunc.ServeHTTP(0xc001cf4760, 0x3e7e040, 0xc001492ee0, 0xc001247800)
ocis_1   |      /usr/local/go/src/net/http/server.go:2007 +0x44
ocis_1   | net/http.serverHandler.ServeHTTP(0xc000278380, 0x3e7e040, 0xc001492ee0, 0xc001247800)
ocis_1   |      /usr/local/go/src/net/http/server.go:2802 +0xa4
ocis_1   | net/http.(*conn).serve(0xc001432640, 0x3e8b340, 0xc000eb3280)
ocis_1   |      /usr/local/go/src/net/http/server.go:1890 +0x875
ocis_1   | created by net/http.(*Server).Serve
ocis_1   |      /usr/local/go/src/net/http/server.go:2927 +0x38e
ocis_1   | 2020-10-13 12:52:32.700897 I | http: TLS handshake error from 170.60.10.76:51517: remote error: tls: unknown certificate
ocis_1   | 2020-10-13 12:52:32.708413 I | http: panic serving 170.60.10.76:51518: runtime error: invalid memory address or nil pointer dereference
ocis_1   | goroutine 271 [running]:
ocis_1   | net/http.(*conn).serve.func1(0xc0013d77c0)
ocis_1   |      /usr/local/go/src/net/http/server.go:1767 +0x139
ocis_1   | panic(0x346bf40, 0x544ef40)
ocis_1   |      /usr/local/go/src/runtime/panic.go:679 +0x1b2
ocis_1   | github.com/coreos/go-oidc.(*Provider).UserInfo(0x0, 0x3e8b400, 0xc0014c3b60, 0x3e2f5c0, 0xc0016244e0, 0x0, 0x0, 0x0)
ocis_1   |      /srv/app/pkg/mod/github.com/coreos/go-oidc@v2.2.1+incompatible/oidc.go:205 +0x51
ocis_1   | github.com/owncloud/ocis/proxy/pkg/middleware.OpenIDConnect.func1.1(0x3e7e040, 0xc0013cca80, 0xc001247900)
ocis_1   |      /drone/src/proxy/pkg/middleware/openidconnect.go:75 +0x24d
ocis_1   | net/http.HandlerFunc.ServeHTTP(0xc0013d9a10, 0x3e7e040, 0xc0013cca80, 0xc001247900)
ocis_1   |      /usr/local/go/src/net/http/server.go:2007 +0x44
ocis_1   | github.com/owncloud/ocis/proxy/pkg/middleware.RedirectToHTTPS.func1(0x3e7e040, 0xc0013cca80, 0xc001247900)
ocis_1   |      /drone/src/proxy/pkg/middleware/https_redirect.go:17 +0x1b4
ocis_1   | net/http.HandlerFunc.ServeHTTP(0xc001cf4760, 0x3e7e040, 0xc0013cca80, 0xc001247900)
ocis_1   |      /usr/local/go/src/net/http/server.go:2007 +0x44
ocis_1   | net/http.serverHandler.ServeHTTP(0xc000278380, 0x3e7e040, 0xc0013cca80, 0xc001247900)
ocis_1   |      /usr/local/go/src/net/http/server.go:2802 +0xa4
ocis_1   | net/http.(*conn).serve(0xc0013d77c0, 0x3e8b340, 0xc000eb3600)
ocis_1   |      /usr/local/go/src/net/http/server.go:1890 +0x875
ocis_1   | created by net/http.(*Server).Serve
ocis_1   |      /usr/local/go/src/net/http/server.go:2927 +0x38e
```

**docker-compose.yml**
```
services:
  ocis:
    depends_on:
    - redis
    environment:
      KONNECTD_IDENTIFIER_REGISTRATION_CONF: /etc/ocis/identifier-registration.yml
      KONNECTD_ISS: https://192.168.2.100:9200
      KONNECTD_LOG_LEVEL: debug
      KONNECTD_TLS: '0'
      OCIS_LOG_LEVEL: debug
      PHOENIX_OIDC_AUTHORITY: https://192.168.2.100:9200
      PHOENIX_OIDC_METADATA_URL: https://192.168.2.100:9200/.well-known/openid-configuration
      PHOENIX_WEB_CONFIG_SERVER: https://192.168.2.100:9200
      PROXY_HTTP_ADDR: 0.0.0.0:9200
      REVA_DATAGATEWAY_URL: https://192.168.2.100:9200/data
      REVA_FRONTEND_URL: https://192.168.2.100:9200
      REVA_OIDC_ISSUER: https://192.168.2.100:9200
      REVA_STORAGE_OWNCLOUD_REDIS_ADDR: redis:6379
    image: owncloud/ocis:latest
    ports:
    - published: 9200
      target: 9200
    restart: always
    volumes:
    - /home/dsadmin/apps/owncloud/compose-playground/compose/ocis/config:/etc/ocis:rw
  redis:
    environment:
      REDIS_MAXCONN: '10000'
    image: redis
    restart: always
version: '3.4'
```

**Comment by refs** [comment]
most likely your `identifier-registration.yml` file is misaligned.
