### ISSUE TITLE
ocis panics when OCIS_TRACING_ENABLED=true

### ISSUE THREAD

**Issue by rhafer** [owncloud/ocis#7012]
Used ocis version:
Version: 3.1.0-next.4

1. "invalid memory address or nil pointer dereference".
 
After short tests it turned out that the error only occurs if `OCIS_TRACING_ENABLED=true` is set.

```
OCIS_TRACING_ENABLED=true
OCIS_LOG_LEVEL=debug
```

Log 1:
```
...
{"level":"debug","service":"nats","time":"2023-07-14T11:49:48.386181465+02:00","line":"github.com/owncloud/ocis/v2/services/nats/pkg/logging/nats.go:45","message":"127.0.0.1:39382 - cid:26 - Client Ping Timer"}
Jul 14 11:49:48 owncloud ocis[1512682]: {"level":"debug","service":"nats","time":"2023-07-14T11:49:48.458650046+02:00","line":"github.com/owncloud/ocis/v2/services/nats/pkg/logging/nats.go:45","message":"127.0.0.1:39428 - cid:30 - Client Ping Timer"}
Jul 14 11:49:50 owncloud ocis[1512682]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 14 11:49:50 owncloud ocis[1512682]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xbb46c1]
Jul 14 11:49:50 owncloud ocis[1512682]: goroutine 242 [running]:
Jul 14 11:49:50 owncloud ocis[1512682]: go.opentelemetry.io/otel/exporters/jaeger.(*Exporter).ExportSpans(0x0, {0x4430eb0, 0xc001551020}, {0xc001af8000, 0xe, 0x200})
Jul 14 11:49:50 owncloud ocis[1512682]:         go.opentelemetry.io/otel/exporters/jaeger@v1.15.1/jaeger.go:87 +0x81
Jul 14 11:49:50 owncloud ocis[1512682]: go.opentelemetry.io/otel/sdk/trace.(*batchSpanProcessor).exportSpans(0xc001aca280, {0x4430e40, 0xc001a9d1d0?})
Jul 14 11:49:50 owncloud ocis[1512682]:         go.opentelemetry.io/otel/sdk@v1.16.0/trace/batch_span_processor.go:269 +0x264
Jul 14 11:49:50 owncloud ocis[1512682]: go.opentelemetry.io/otel/sdk/trace.(*batchSpanProcessor).processQueue(0xc001aca280)
Jul 14 11:49:50 owncloud ocis[1512682]:         go.opentelemetry.io/otel/sdk@v1.16.0/trace/batch_span_processor.go:297 +0x392
Jul 14 11:49:50 owncloud ocis[1512682]: go.opentelemetry.io/otel/sdk/trace.NewBatchSpanProcessor.func1()
Jul 14 11:49:50 owncloud ocis[1512682]:         go.opentelemetry.io/otel/sdk@v1.16.0/trace/batch_span_processor.go:128 +0x65
Jul 14 11:49:50 owncloud ocis[1512682]: created by go.opentelemetry.io/otel/sdk/trace.NewBatchSpanProcessor
Jul 14 11:49:50 owncloud ocis[1512682]:         go.opentelemetry.io/otel/sdk@v1.16.0/trace/batch_span_processor.go:126 +0x2ea
Jul 14 11:49:50 owncloud ocis[1512693]: {"level":"warn","service":"storage-system","type":"","time":"2023-07-14T11:49:50.459397876+02:00","line":"github.com/owncloud/ocis/v2/ocis-pkg/tracing/tracing.go:185","message":"Unknown tracing exporter"}
````

_Originally posted by @ChrisEdS in https://github.com/owncloud/enterprise/issues/5858#issuecomment-1654527098_

**Comment by rhafer** [comment]
Of course just setting `OCIS_TRACING_ENABLED=true` with out further configuring the other tracing options creates an invalid config. But we should handle that more graceful (i.e. exit with an error message) than just crashing with a panic.

**Comment by dragonchaser** [comment]
Still reproducible with current master.
