### ISSUE TITLE
Nightly failures while connecting to selenium on port 4444

### ISSUE THREAD

**Issue by PrajwolAmatya** [owncloud/ocis#7644]
Multiple scenarios failed with error:
```log
- Connecting to selenium on port 4444...

    POST http://selenium:4444 /wd/hub/session - ECONNRESET
Error: socket hang up
    at connResetException (node:internal/errors:717:14)
    at Socket.socketCloseListener (node:_http_client:475:25)
    at Socket.emit (node:events:525:35)
    at TCP.<anonymous> (node:net:322:12)
⚠ Error connecting to selenium on port 4444.
    ✖ failed
      Error: An error occurred while retrieving a new session: "socket hang up"
          at Selenium2Protocol.handleSessionCreateError (/drone/src/webTestRunner/node_modules/.pnpm/nightwatch@1.7.11_chromedriver@93.0.1/node_modules/nightwatch/lib/transport/transport.js:110:15)
          at HttpRequest.<anonymous> (/drone/src/webTestRunner/node_modules/.pnpm/nightwatch@1.7.11_chromedriver@93.0.1/node_modules/nightwatch/lib/transport/transport.js:166:32)
          at HttpRequest.emit (node:events:513:28)
          at ClientRequest.<anonymous> (/drone/src/webTestRunner/node_modules/.pnpm/nightwatch@1.7.11_chromedriver@93.0.1/node_modules/nightwatch/lib/http/request.js:143:19)
          at ClientRequest.emit (node:events:525:35)
          at Socket.socketCloseListener (node:_http_client:475:11)
          at Socket.emit (node:events:525:35)
          at TCP.<anonymous> (node:net:322:12)
    - skipped
    - skipped
    - skipped
    - skipped
    - skipped
    - skipped
    - skipped
    - skipped
```

Build:
- https://drone.owncloud.com/owncloud/ocis/28306/46/13

**Comment by ScharfViktor** [comment]
still relevant? I didn't find this error in the failed builds

**Comment by saw-jan** [comment]
Haven't seen this kind of failure for months. So closing now

**Comment by ScharfViktor** [comment]
> Haven't seen this kind of failure for months. So closing now

because there's no more selenium 😀
