### ISSUE TITLE
Requests to webdav URLs with an invalid fileid result in a nil pointer dereference

### ISSUE THREAD

**Issue by individual-it** [owncloud/ocis#771]
make any HTTP request to the meta data endpoint but give a fileId that does not base64 decode to a valid value e.g.
`curl -k -u richard:superfluidity -XPROPFIND https://localhost:9200/remote.php/dav/meta/MTI4NGQyMzgtYWE5Mi00MmNlLWJkYzQtMGIwMDAwMDA5MTU3PThjY2QyNzUxLTkwYTQtNDBmMi1iOWYzLTYxZWRmODQ0MjFmNA==/v -v`

```
2020-10-29 10:51:33.646678 I | http: panic serving 127.0.0.1:54668: runtime error: invalid memory address or nil pointer dereference
goroutine 801 [running]:
net/http.(*conn).serve.func1(0xc001276140)
	/usr/local/go/src/net/http/server.go:1767 +0x139
panic(0x353ada0, 0x556ff90)
	/usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/cs3org/reva/internal/http/services/owncloud/ocdav.wrapResourceID(...)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/internal/http/services/owncloud/ocdav/ocdav.go:207
github.com/cs3org/reva/internal/http/services/owncloud/ocdav.(*VersionsHandler).Handler.func1(0x7fbab5f57ec0, 0xc000bea750, 0xc001290700)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/internal/http/services/owncloud/ocdav/versions.go:49 +0xcb
net/http.HandlerFunc.ServeHTTP(0xc000d88ce0, 0x7fbab5f57ec0, 0xc000bea750, 0xc001290700)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/services/owncloud/ocdav.(*MetaHandler).Handler.func1(0x7fbab5f57ec0, 0xc000bea750, 0xc001290700)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/internal/http/services/owncloud/ocdav/meta.go:54 +0x183
net/http.HandlerFunc.ServeHTTP(0xc000d88ca0, 0x7fbab5f57ec0, 0xc000bea750, 0xc001290700)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/services/owncloud/ocdav.(*DavHandler).Handler.func1(0x7fbab5f57ec0, 0xc000bea750, 0xc001290600)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/internal/http/services/owncloud/ocdav/dav.go:130 +0xd04
net/http.HandlerFunc.ServeHTTP(0xc000d88c80, 0x7fbab5f57ec0, 0xc000bea750, 0xc001290600)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/services/owncloud/ocdav.(*svc).Handler.func1(0x7fbab5f57ec0, 0xc000bea750, 0xc001290500)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/internal/http/services/owncloud/ocdav/ocdav.go:190 +0x8b8
net/http.HandlerFunc.ServeHTTP(0xc0012d0550, 0x7fbab5f57ec0, 0xc000bea750, 0xc001290500)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x7fbab5f57ec0, 0xc000bea750, 0xc001290400)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/pkg/rhttp/rhttp.go:306 +0x185
net/http.HandlerFunc.ServeHTTP(0xc00129a3f0, 0x7fbab5f57ec0, 0xc000bea750, 0xc001290400)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.(*Server).getHandler.func1(0x7fbab5f57ec0, 0xc000bea750, 0xc001290400)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/pkg/rhttp/rhttp.go:244 +0x46b
net/http.HandlerFunc.ServeHTTP(0xc0012d0a40, 0x7fbab5f57ec0, 0xc000bea750, 0xc001290400)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x7fbab5f57ec0, 0xc000bea750, 0xc001290300)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/pkg/rhttp/rhttp.go:306 +0x185
net/http.HandlerFunc.ServeHTTP(0xc00129a540, 0x7fbab5f57ec0, 0xc000bea750, 0xc001290300)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/rs/cors.(*Cors).Handler.func1(0x7fbab5f57ec0, 0xc000bea750, 0xc001290300)
	/home/artur/go/pkg/mod/github.com/rs/cors@v1.7.0/cors.go:219 +0x1b8
net/http.HandlerFunc.ServeHTTP(0xc001297500, 0x7fbab5f57ec0, 0xc000bea750, 0xc001290300)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x7fbab5f57ec0, 0xc000bea750, 0xc001290200)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/pkg/rhttp/rhttp.go:306 +0x185
net/http.HandlerFunc.ServeHTTP(0xc00129a630, 0x7fbab5f57ec0, 0xc000bea750, 0xc001290200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/interceptors/auth.New.func1.1(0x7fbab5f57ec0, 0xc000bea750, 0xc000573e00)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/internal/http/interceptors/auth/auth.go:245 +0xe9d
net/http.HandlerFunc.ServeHTTP(0xc00127c2d0, 0x7fbab5f57ec0, 0xc000bea750, 0xc000573e00)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x7fbab5f57ec0, 0xc000bea750, 0xc000573500)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/pkg/rhttp/rhttp.go:306 +0x185
net/http.HandlerFunc.ServeHTTP(0xc00129a660, 0x7fbab5f57ec0, 0xc000bea750, 0xc000573500)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/interceptors/log.loggingHandler.ServeHTTP(0x3f20840, 0xc00129a660, 0x3f71f60, 0xc000cb7180, 0xc000573500)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/internal/http/interceptors/log/log.go:57 +0x297
github.com/cs3org/reva/pkg/rhttp.traceHandler.func1(0x3f71f60, 0xc000cb7180, 0xc000573200)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/pkg/rhttp/rhttp.go:306 +0x185
net/http.HandlerFunc.ServeHTTP(0xc00129a690, 0x3f71f60, 0xc000cb7180, 0xc000573200)
	/usr/local/go/src/net/http/server.go:2007 +0x44
github.com/cs3org/reva/internal/http/interceptors/appctx.handler.func1(0x3f71f60, 0xc000cb7180, 0xc000573100)
	/home/artur/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/internal/http/interceptors/appctx/appctx.go:52 +0x5e9
net/http.HandlerFunc.ServeHTTP(0xc000112000, 0x3f71f60, 0xc000cb7180, 0xc000573100)
	/usr/local/go/src/net/http/server.go:2007 +0x44
go.opencensus.io/plugin/ochttp.(*Handler).ServeHTTP(0xc0012b23c0, 0x3f71f60, 0xc000cb7180, 0xc000104800)
	/home/artur/go/pkg/mod/go.opencensus.io@v0.22.5/plugin/ochttp/server.go:92 +0x2b9
net/http.serverHandler.ServeHTTP(0xc000236c40, 0x3f6fba0, 0xc0002360e0, 0xc000104800)
	/usr/local/go/src/net/http/server.go:2802 +0xa4
net/http.(*conn).serve(0xc001276140, 0x3f7d2e0, 0xc0012da000)
	/usr/local/go/src/net/http/server.go:1890 +0x875
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2927 +0x38e
2020-10-29 10:51:33.646848 I | http: proxy error: EOF

**Comment by refs** [comment]
Confirm still happens in the current master.

**Comment by individual-it** [comment]
- [ ]  ToDo QA-team: add API tests for this case
