### ISSUE TITLE
500 when open public link from deleted user

### ISSUE THREAD

**Issue by ScharfViktor** [owncloud/ocis#7740]
Steps:

- einstein creates public link for file or folder 
- einstein deletes file

- public opens link - `404` correct
<img width="1308" alt="Screenshot 2023-11-16 at 15 35 21" src="https://github.com/owncloud/ocis/assets/84779829/e6982aa4-b2c4-4b1e-9032-3ceb80fc10f3">

- admin deletes einstein
- public opens link - `500` 

Expect: 404 error
Actual: 500 error
<img width="1235" alt="Screenshot 2023-11-16 at 15 37 59" src="https://github.com/owncloud/ocis/assets/84779829/c2d18a58-a0e9-40e0-8feb-bef9d4d2b547">

log: 
```
2023-11-16 15:39:58 goroutine 17015 [running]:
2023-11-16 15:39:58 runtime/debug.Stack()
2023-11-16 15:39:58     runtime/debug/stack.go:24 +0x64
2023-11-16 15:39:58 runtime/debug.PrintStack()
2023-11-16 15:39:58     runtime/debug/stack.go:16 +0x1c
2023-11-16 15:39:58 github.com/cs3org/reva/v2/internal/grpc/interceptors/recovery.recoveryFunc({0x41a0090, 0x40044d23c0}, {0x3c14f00, 0x5ae4360})
2023-11-16 15:39:58     github.com/cs3org/reva/v2@v2.16.1-0.20231110061744-953e57a6a95c/internal/grpc/interceptors/recovery/recovery.go:48 +0x2c
2023-11-16 15:39:58 github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom({0x41a0090?, 0x40044d23c0?}, {0x3c14f00?, 0x5ae4360?}, 0x4004dc2588?)
2023-11-16 15:39:58     github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/recovery/interceptors.go:61 +0x38
2023-11-16 15:39:58 github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1.1()
2023-11-16 15:39:58     github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/recovery/interceptors.go:29 +0x78
2023-11-16 15:39:58 panic({0x3c14f00, 0x5ae4360})
2023-11-16 15:39:58     runtime/panic.go:884 +0x204
2023-11-16 15:39:58 github.com/cs3org/reva/v2/pkg/auth/manager/publicshares.(*manager).Authenticate(0x41a0090?, {0x41a0090, 0x40044d2630}, {0x40016371e0, 0xf}, {0x40045a8e10, 0x11})
2023-11-16 15:39:58     github.com/cs3org/reva/v2@v2.16.1-0.20231110061744-953e57a6a95c/pkg/auth/manager/publicshares/publicshares.go:160 +0x7e8
2023-11-16 15:39:58 github.com/cs3org/reva/v2/internal/grpc/services/authprovider.(*service).Authenticate(0x400185fe20, {0x41a0090, 0x40044d2630}, 0x4004256f50)
2023-11-16 15:39:58     github.com/cs3org/reva/v2@v2.16.1-0.20231110061744-953e57a6a95c/internal/grpc/services/authprovider/authprovider.go:138 +0x90
2023-11-16 15:39:58 github.com/cs3org/go-cs3apis/cs3/auth/provider/v1beta1._ProviderAPI_Authenticate_Handler.func1({0x41a0090, 0x40044d2630}, {0x3f85ae0?, 0x4004256f50})
2023-11-16 15:39:58     github.com/cs3org/go-cs3apis@v0.0.0-20231023073225-7748710e0781/cs3/auth/provider/v1beta1/provider_api.pb.go:263 +0x74
2023-11-16 15:39:58 go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1({0x41a0090, 0x40044d2480}, {0x3f85ae0, 0x4004256f50}, 0x40018f61c0, 0x4004669308)
2023-11-16 15:39:58     go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.36.4/interceptor.go:341 +0x370
2023-11-16 15:39:58 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x41a0090?, 0x40044d2480?}, {0x3f85ae0?, 0x4004256f50?})
2023-11-16 15:39:58     github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x50
2023-11-16 15:39:58 github.com/cs3org/reva/v2/internal/grpc/interceptors/prometheus.interceptorFromConfig.func1({0x41a0090?, 0x40044d2480?}, {0x3f85ae0?, 0x4004256f50?}, 0x400333ed48?, 0x128881c?)
2023-11-16 15:39:58     github.com/cs3org/reva/v2@v2.16.1-0.20231110061744-953e57a6a95c/internal/grpc/interceptors/prometheus/prometheus.go:72 +0x44
2023-11-16 15:39:58 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x41a0090?, 0x40044d2480?}, {0x3f85ae0?, 0x4004256f50?})
2023-11-16 15:39:58     github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x50
2023-11-16 15:39:58 github.com/cs3org/reva/v2/internal/grpc/interceptors/auth.NewUnary.func2({0x41a0090, 0x40044d23c0}, {0x3f85ae0, 0x4004256f50}, 0x40018f61c0, 0x40046d6940)
2023-11-16 15:39:58     github.com/cs3org/reva/v2@v2.16.1-0.20231110061744-953e57a6a95c/internal/grpc/interceptors/auth/auth.go:137 +0x4fc
2023-11-16 15:39:58 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x41a0090?, 0x40044d23c0?}, {0x3f85ae0?, 0x4004256f50?})
2023-11-16 15:39:58     github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x50
2023-11-16 15:39:58 github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1({0x41a0090?, 0x40044d23c0?}, {0x3f85ae0?, 0x4004256f50?}, 0x400333f158?, 0x128e1cc?)
2023-11-16 15:39:58     github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/recovery/interceptors.go:33 +0x98
2023-11-16 15:39:58 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x41a0090?, 0x40044d23c0?}, {0x3f85ae0?, 0x4004256f50?})
2023-11-16 15:39:58     github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x50
2023-11-16 15:39:58 github.com/cs3org/reva/v2/internal/grpc/interceptors/log.NewUnary.func1({0x41a0090, 0x40044d23c0}, {0x3f85ae0, 0x4004256f50}, 0x40018f61c0, 0x40046d69c0)
2023-11-16 15:39:58     github.com/cs3org/reva/v2@v2.16.1-0.20231110061744-953e57a6a95c/internal/grpc/interceptors/log/log.go:39 +0x68
2023-11-16 15:39:58 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x41a0090?, 0x40044d23c0?}, {0x3f85ae0?, 0x4004256f50?})
2023-11-16 15:39:58     github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x50
2023-11-16 15:39:58 github.com/cs3org/reva/v2/internal/grpc/interceptors/useragent.NewUnary.func1({0x41a0090, 0x40044d23c0}, {0x3f85ae0, 0x4004256f50}, 0x0?, 0x40046d6a00)
2023-11-16 15:39:58     github.com/cs3org/reva/v2@v2.16.1-0.20231110061744-953e57a6a95c/internal/grpc/interceptors/useragent/useragent.go:38 +0xdc
2023-11-16 15:39:58 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x41a0090?, 0x40044d23c0?}, {0x3f85ae0?, 0x4004256f50?})
2023-11-16 15:39:58     github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x50
2023-11-16 15:39:58 github.com/cs3org/reva/v2/internal/grpc/interceptors/token.NewUnary.func1({0x41a0090, 0x40044d23c0}, {0x3f85ae0, 0x4004256f50}, 0x400333f408?, 0x40046d6a40)
2023-11-16 15:39:58     github.com/cs3org/reva/v2@v2.16.1-0.20231110061744-953e57a6a95c/internal/grpc/interceptors/token/token.go:44 +0x134
2023-11-16 15:39:58 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x41a0090?, 0x40044d23c0?}, {0x3f85ae0?, 0x4004256f50?})
2023-11-16 15:39:58     github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x50
2023-11-16 15:39:58 github.com/cs3org/reva/v2/internal/grpc/interceptors/appctx.NewUnary.func1({0x41a0090, 0x40044d2330}, {0x3f85ae0, 0x4004256f50}, 0x4004669308?, 0x40046d6b00)
2023-11-16 15:39:58     github.com/cs3org/reva/v2@v2.16.1-0.20231110061744-953e57a6a95c/internal/grpc/interceptors/appctx/appctx.go:51 +0x60c
2023-11-16 15:39:58 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2({0x41a0090, 0x40044d2330}, {0x3f85ae0, 0x4004256f50}, 0x40018f61c0, 0x98bcd8?)
2023-11-16 15:39:58     github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:53 +0x158
2023-11-16 15:39:58 github.com/cs3org/go-cs3apis/cs3/auth/provider/v1beta1._ProviderAPI_Authenticate_Handler({0x3d12b20?, 0x400185fe20}, {0x41a0090, 0x40044d2330}, 0x40058d9d00, 0x4001aba420)
2023-11-16 15:39:58     github.com/cs3org/go-cs3apis@v0.0.0-20231023073225-7748710e0781/cs3/auth/provider/v1beta1/provider_api.pb.go:265 +0x138
2023-11-16 15:39:58 google.golang.org/grpc.(*Server).processUnaryRPC(0x400187b0e0, {0x41a0090, 0x40044d2270}, {0x41b3700, 0x40044e3380}, 0x40047f9200, 0x4001aba660, 0x5ae6720, 0x0)
2023-11-16 15:39:58     google.golang.org/grpc@v1.59.0/server.go:1343 +0xc6c
2023-11-16 15:39:58 google.golang.org/grpc.(*Server).handleStream(0x400187b0e0, {0x41b3700, 0x40044e3380}, 0x40047f9200)
2023-11-16 15:39:58     google.golang.org/grpc@v1.59.0/server.go:1737 +0x9f0
2023-11-16 15:39:58 google.golang.org/grpc.(*Server).serveStreams.func1.1()
2023-11-16 15:39:58     google.golang.org/grpc@v1.59.0/server.go:986 +0x88
2023-11-16 15:39:58 created by google.golang.org/grpc.(*Server).serveStreams.func1
2023-11-16 15:39:58     google.golang.org/grpc@v1.59.0/server.go:997 +0x174
2023-11-16 15:39:58 2023-11-16T14:39:58Z ERR runtime error: invalid memory address or nil pointer dereference; stack: goroutine 17015 [running]:
2023-11-16 15:39:58 runtime/debug.Stack()
2023-11-16 15:39:58     runtime/debug/stack.go:24 +0x64
2023-11-16 15:39:58 github.com/cs3org/reva/v2/internal/grpc/interceptors/recovery.recoveryFunc({0x41a0090, 0x40044d23c0}, {0x3c14f00, 0x5ae4360})
2023-11-16 15:39:58     github.com/cs3org/reva/v2@v2.16.1-0.20231110061744-953e57a6a95c/internal/grpc/interceptors/recovery/recovery.go:50 +0x44
2023-11-16 15:39:58 github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom({0x41a0090?, 0x40044d23c0?}, {0x3c14f00?, 0x5ae4360?}, 0x4004dc2588?)
2023-11-16 15:39:58     github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/recovery/interceptors.go:61 +0x38
2023-11-16 15:39:58 github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1.1()
2023-11-16 15:39:58     github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/recovery/interceptors.go:29 +0x78
2023-11-16 15:39:58 panic({0x3c14f00, 0x5ae4360})
2023-11-16 15:39:58     runtime/panic.go:884 +0x204
2023-11-16 15:39:58 github.com/cs3org/reva/v2/pkg/auth/manager/publicshares.(*manager).Authenticate(0x41a0090?, {0x41a0090, 0x40044d2630}, {0x40016371e0, 0xf}, {0x40045a8e10, 0x11})
2023-11-16 15:39:58     github.com/cs3org/reva/v2@v2.16.1-0.20231110061744-953e57a6a95c/pkg/auth/manager/publicshares/publicshares.go:160 +0x7e8
2023-11-16 15:39:58 github.com/cs3org/reva/v2/internal/grpc/services/authprovider.(*service).Authenticate(0x400185fe20, {0x41a0090, 0x40044d2630}, 0x4004256f50)
2023-11-16 15:39:58     github.com/cs3org/reva/v2@v2.16.1-0.20231110061744-953e57a6a95c/internal/grpc/services/authprovider/authprovider.go:138 +0x90
2023-11-16 15:39:58 github.com/cs3org/go-cs3apis/cs3/auth/provider/v1beta1._ProviderAPI_Authenticate_Handler.func1({0x41a0090, 0x40044d2630}, {0x3f85ae0?, 0x4004256f50})
2023-11-16 15:39:58     github.com/cs3org/go-cs3apis@v0.0.0-20231023073225-7748710e0781/cs3/auth/provider/v1beta1/provider_api.pb.go:263 +0x74
2023-11-16 15:39:58 go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc.UnaryServerInterceptor.func1({0x41a0090, 0x40044d2480}, {0x3f85ae0, 0x4004256f50}, 0x40018f61c0, 0x4004669308)
2023-11-16 15:39:58     go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc@v0.36.4/interceptor.go:341 +0x370
2023-11-16 15:39:58 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x41a0090?, 0x40044d2480?}, {0x3f85ae0?, 0x4004256f50?})
2023-11-16 15:39:58     github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x50
2023-11-16 15:39:58 github.com/cs3org/reva/v2/internal/grpc/interceptors/prometheus.interceptorFromConfig.func1({0x41a0090?, 0x40044d2480?}, {0x3f85ae0?, 0x4004256f50?}, 0x400333ed48?, 0x128881c?)
2023-11-16 15:39:58     github.com/cs3org/reva/v2@v2.16.1-0.20231110061744-953e57a6a95c/internal/grpc/interceptors/prometheus/prometheus.go:72 +0x44
2023-11-16 15:39:58 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x41a0090?, 0x40044d2480?}, {0x3f85ae0?, 0x4004256f50?})
2023-11-16 15:39:58     github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x50
2023-11-16 15:39:58 github.com/cs3org/reva/v2/internal/grpc/interceptors/auth.NewUnary.func2({0x41a0090, 0x40044d23c0}, {0x3f85ae0, 0x4004256f50}, 0x40018f61c0, 0x40046d6940)
2023-11-16 15:39:58     github.com/cs3org/reva/v2@v2.16.1-0.20231110061744-953e57a6a95c/internal/grpc/interceptors/auth/auth.go:137 +0x4fc
2023-11-16 15:39:58 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x41a0090?, 0x40044d23c0?}, {0x3f85ae0?, 0x4004256f50?})
2023-11-16 15:39:58     github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x50
2023-11-16 15:39:58 github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1({0x41a0090?, 0x40044d23c0?}, {0x3f85ae0?, 0x4004256f50?}, 0x400333f158?, 0x128e1cc?)
2023-11-16 15:39:58     github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/recovery/interceptors.go:33 +0x98
2023-11-16 15:39:58 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x41a0090?, 0x40044d23c0?}, {0x3f85ae0?, 0x4004256f50?})
2023-11-16 15:39:58     github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x50
2023-11-16 15:39:58 github.com/cs3org/reva/v2/internal/grpc/interceptors/log.NewUnary.func1({0x41a0090, 0x40044d23c0}, {0x3f85ae0, 0x4004256f50}, 0x40018f61c0, 0x40046d69c0)
2023-11-16 15:39:58     github.com/cs3org/reva/v2@v2.16.1-0.20231110061744-953e57a6a95c/internal/grpc/interceptors/log/log.go:39 +0x68
2023-11-16 15:39:58 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x41a0090?, 0x40044d23c0?}, {0x3f85ae0?, 0x4004256f50?})
2023-11-16 15:39:58     github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x50
2023-11-16 15:39:58 github.com/cs3org/reva/v2/internal/grpc/interceptors/useragent.NewUnary.func1({0x41a0090, 0x40044d23c0}, {0x3f85ae0, 0x4004256f50}, 0x0?, 0x40046d6a00)
2023-11-16 15:39:58     github.com/cs3org/reva/v2@v2.16.1-0.20231110061744-953e57a6a95c/internal/grpc/interceptors/useragent/useragent.go:38 +0xdc
2023-11-16 15:39:58 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x41a0090?, 0x40044d23c0?}, {0x3f85ae0?, 0x4004256f50?})
2023-11-16 15:39:58     github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x50
2023-11-16 15:39:58 github.com/cs3org/reva/v2/internal/grpc/interceptors/token.NewUnary.func1({0x41a0090, 0x40044d23c0}, {0x3f85ae0, 0x4004256f50}, 0x400333f408?, 0x40046d6a40)
2023-11-16 15:39:58     github.com/cs3org/reva/v2@v2.16.1-0.20231110061744-953e57a6a95c/internal/grpc/interceptors/token/token.go:44 +0x134
2023-11-16 15:39:58 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2.1({0x41a0090?, 0x40044d23c0?}, {0x3f85ae0?, 0x4004256f50?})
2023-11-16 15:39:58     github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:48 +0x50
2023-11-16 15:39:58 github.com/cs3org/reva/v2/internal/grpc/interceptors/appctx.NewUnary.func1({0x41a0090, 0x40044d2330}, {0x3f85ae0, 0x4004256f50}, 0x4004669308?, 0x40046d6b00)
2023-11-16 15:39:58     github.com/cs3org/reva/v2@v2.16.1-0.20231110061744-953e57a6a95c/internal/grpc/interceptors/appctx/appctx.go:51 +0x60c
2023-11-16 15:39:58 github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func2({0x41a0090, 0x40044d2330}, {0x3f85ae0, 0x4004256f50}, 0x40018f61c0, 0x98bcd8?)
2023-11-16 15:39:58     github.com/grpc-ecosystem/go-grpc-middleware@v1.4.0/chain.go:53 +0x158
2023-11-16 15:39:58 github.com/cs3org/go-cs3apis/cs3/auth/provider/v1beta1._ProviderAPI_Authenticate_Handler({0x3d12b20?, 0x400185fe20}, {0x41a0090, 0x40044d2330}, 0x40058d9d00, 0x4001aba420)
2023-11-16 15:39:58     github.com/cs3org/go-cs3apis@v0.0.0-20231023073225-7748710e0781/cs3/auth/provider/v1beta1/provider_api.pb.go:265 +0x138
2023-11-16 15:39:58 google.golang.org/grpc.(*Server).processUnaryRPC(0x400187b0e0, {0x41a0090, 0x40044d2270}, {0x41b3700, 0x40044e3380}, 0x40047f9200, 0x4001aba660, 0x5ae6720, 0x0)
2023-11-16 15:39:58     google.golang.org/grpc@v1.59.0/server.go:1343 +0xc6c
2023-11-16 15:39:58 google.golang.org/grpc.(*Server).handleStream(0x400187b0e0, {0x41b3700, 0x40044e3380}, 0x40047f9200)
2023-11-16 15:39:58     google.golang.org/grpc@v1.59.0/server.go:1737 +0x9f0
2023-11-16 15:39:58 google.golang.org/grpc.(*Server).serveStreams.func1.1()
2023-11-16 15:39:58     google.golang.org/grpc@v1.59.0/server.go:986 +0x88
2023-11-16 15:39:58 created by google.golang.org/grpc.(*Server).serveStreams.func1
2023-11-16 15:39:58     google.golang.org/grpc@v1.59.0/server.go:997 +0x174
2023-11-16 15:39:58  pkg=rgrpc service=storage-publiclink traceid=00000000000000000000000000000000
2023-11-16 15:39:58 2023-11-16T14:39:58Z ERR rpc error: code = Internal desc = runtime error: invalid memory address or nil pointer dereference code=Internal end="16/Nov/2023:14:39:58 +0000" from=tcp://127.0.0.1:36684 pkg=rgrpc service=storage-publiclink start="16/Nov/2023:14:39:58 +0000" time_ns=275434833 traceid=00000000000000000000000000000000 uri=/cs3.auth.provider.v1beta1.ProviderAPI/Authenticate user-agent=grpc-go/1.59.0

**Comment by micbar** [comment]
Fixed and updated in #7951
