### ISSUE TITLE
[QA] error whil logging in

### ISSUE THREAD

**Issue by jnweiger** [owncloud/ocis#807]
1.0.0-rc3 ... deployed with github/owncloud-docker/compose-playground/examples/hetzner-deploy/make_ocis_eos_compose_test.sh
```
da92d758d92c5cd2dfaf uri=/cs3.storage.provider.v1beta1.ProviderAPI/ListContainer user-agent=grpc-go/1.26.0
ocis          | goroutine 101 [running]:
ocis          | runtime/debug.Stack(0xc000773c80, 0xc0008eeb40, 0xbfe122108263a9dd)
ocis          |         /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
ocis          | runtime/debug.PrintStack()
ocis          |         /usr/local/go/src/runtime/debug/stack.go:16 +0x22
ocis          | github.com/cs3org/reva/internal/grpc/interceptors/recovery.recoveryFunc(0x3d3f060, 0xc000937470, 0x35f8180, 0xc0008c96c0, 0x38, 0x8)
ocis          |         /root/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/internal/grpc/interceptors/recovery/recovery.go:48 +0x26
ocis          | github.com/grpc-ecosystem/go-grpc-middleware/recovery.recoverFrom(0x3d3f060, 0xc000937470, 0x35f8180, 0xc0008c96c0, 0x3891180, 0xc00086aa20, 0x13b5046)
ocis          |         /root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/recovery/interceptors.go:61 +0x5a
ocis          | github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1.1(0xc00086b44e, 0x3d3f060, 0xc000937470, 0xc000028860, 0xc00086b4d0)
ocis          |         /root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/recovery/interceptors.go:29 +0x6d
ocis          | panic(0x35f8180, 0xc0008c96c0)
ocis          |         /usr/local/go/src/runtime/panic.go:969 +0x166
ocis          | github.com/cs3org/reva/pkg/storage/utils/etag.GenerateEtagFromResources(0xc0018ad8c0, 0x584e9e8, 0x0, 0x0, 0x0, 0x0)
ocis          |         /root/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/pkg/storage/utils/etag/etag.go:62 +0x4cf
ocis          | github.com/cs3org/reva/internal/grpc/services/gateway.(*svc).statSharesFolder(0xc0018b21e0, 0x3d3f060, 0xc0009377d0, 0xc0009330e0, 0xc0002c6380, 0x0)
ocis          |         /root/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/internal/grpc/services/gateway/storageprovider.go:1270 +0x59a
ocis          | github.com/cs3org/reva/internal/grpc/services/gateway.(*svc).statHome(0xc0018b21e0, 0x3d3f060, 0xc0009377d0, 0x1, 0x0, 0x0)
ocis          |         /root/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/internal/grpc/services/gateway/storageprovider.go:1211 +0x339
ocis          | github.com/cs3org/reva/internal/grpc/services/gateway.(*svc).Stat(0xc0018b21e0, 0x3d3f060, 0xc0009377d0, 0xc000932d20, 0xc0018b21e0, 0x31b0160, 0x3c92058)
ocis          |         /root/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/internal/grpc/services/gateway/storageprovider.go:1312 +0x2920
ocis          | github.com/cs3org/go-cs3apis/cs3/gateway/v1beta1._GatewayAPI_Stat_Handler.func1(0x3d3f060, 0xc0009377d0, 0x3641780, 0xc000932d20, 0x36d9320, 0xc000773d00, 0x3d3f060, 0xc0009377d0)
ocis          |         /root/go/pkg/mod/github.com/cs3org/go-cs3apis@v0.0.0-20201007120910-416ed6cf8b00/cs3/gateway/v1beta1/gateway_api.pb.go:2690 +0x89
ocis          | github.com/cs3org/reva/internal/grpc/interceptors/auth.NewUnary.func1(0x3d3f060, 0xc000937470, 0x3641780, 0xc000932d20, 0xc000907ea0, 0xc000907ec0, 0x0, 0x0, 0x0, 0x0)
ocis          |         /root/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/internal/grpc/interceptors/auth/auth.go:96 +0x318
ocis          | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x3d3f060, 0xc000937470, 0x3641780, 0xc000932d20, 0x13fbae8, 0xc000936e70, 0x8, 0x584e9e8)
ocis          |         /root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:25 +0x63
ocis          | github.com/grpc-ecosystem/go-grpc-middleware/recovery.UnaryServerInterceptor.func1(0x3d3f060, 0xc000937470, 0x3641780, 0xc000932d20, 0xc000907ea0, 0xc000907ee0, 0x0, 0x0, 0x0, 0x0)
ocis          |         /root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/recovery/interceptors.go:33 +0xcb
ocis          | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x3d3f060, 0xc000937470, 0x3641780, 0xc000932d20, 0xc000070700, 0x7fee961bf7d0, 0x0, 0xc000907fc0)
ocis          |         /root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:25 +0x63
ocis          | github.com/cs3org/reva/internal/grpc/interceptors/log.NewUnary.func1(0x3d3f060, 0xc000937470, 0x3641780, 0xc000932d20, 0xc000907ea0, 0xc000907f00, 0x0, 0xc000907fa0, 0x1, 0x1)
ocis          |         /root/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/internal/grpc/interceptors/log/log.go:39 +0x9b
ocis          | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x3d3f060, 0xc000937470, 0x3641780, 0xc000932d20, 0x2, 0x3d3f060, 0xc000937470, 0xc000937440)
ocis          |         /root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:25 +0x63
ocis          | github.com/cs3org/reva/internal/grpc/interceptors/token.NewUnary.func1(0x3d3f060, 0xc000937410, 0x3641780, 0xc000932d20, 0xc000907ea0, 0xc000907f20, 0x3746920, 0xc000904d80, 0x3d3f060, 0xc000937410)
ocis          |         /root/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/internal/grpc/interceptors/token/token.go:44 +0xb4
ocis          | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x3d3f060, 0xc000937410, 0x3641780, 0xc000932d20, 0xc000937410, 0xc000903800, 0x4f, 0x1f4)
ocis          |         /root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:25 +0x63
ocis          | github.com/cs3org/reva/internal/grpc/interceptors/appctx.NewUnary.func1(0x3d3f060, 0xc000937200, 0x3641780, 0xc000932d20, 0xc000907ea0, 0xc000907f40, 0x279981a, 0x3535f20, 0xc000907f60, 0xc000907ea0)
ocis          |         /root/go/pkg/mod/github.com/cs3org/reva@v1.3.1-0.20201023144216-cdb3d6688da5/internal/grpc/interceptors/appctx/appctx.go:36 +0x4fc
ocis          | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1.1.1(0x3d3f060, 0xc000937200, 0x3641780, 0xc000932d20, 0xc000707200, 0xc000907bc0, 0xc00037fb08, 0x135b298)
ocis          |         /root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:25 +0x63
ocis          | github.com/grpc-ecosystem/go-grpc-middleware.ChainUnaryServer.func1(0x3d3f060, 0xc000937200, 0x3641780, 0xc000932d20, 0xc000907ea0, 0xc000907ec0, 0xc00043fb78, 0x13fb688, 0x35bc520, 0xc000937200)
ocis          |         /root/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-middleware@v1.2.2/chain.go:34 +0xd5
ocis          | github.com/cs3org/go-cs3apis/cs3/gateway/v1beta1._GatewayAPI_Stat_Handler(0x37bfe40, 0xc0018b21e0, 0x3d3f060, 0xc000937200, 0xc000904c60, 0xc0005fd800, 0x3d3f060, 0xc000937200, 0xc0002df110, 0x9)
ocis          |         /root/go/pkg/mod/github.com/cs3org/go-cs3apis@v0.0.0-20201007120910-416ed6cf8b00/cs3/gateway/v1beta1/gateway_api.pb.go:2692 +0x14b
ocis          | google.golang.org/grpc.(*Server).processUnaryRPC(0xc000027680, 0x3d5f740, 0xc000600780, 0xc000707200, 0xc0005fd9b0, 0x5500d88, 0x0, 0x0, 0x0)
ocis          |         /root/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1024 +0x501
ocis          | google.golang.org/grpc.(*Server).handleStream(0xc000027680, 0x3d5f740, 0xc000600780, 0xc000707200, 0x0)
ocis          |         /root/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1313 +0xd3f
ocis          | google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc001359ef0, 0xc000027680, 0x3d5f740, 0xc000600780, 0xc000707200)
ocis          |         /root/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:722 +0xa1
ocis          | created by google.golang.org/grpc.(*Server).serveStreams.func1
ocis          |         /root/go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:720 +0xa1
ocis          | 2020-11-05T14:48:34Z ERR runtime error: slice bounds out of range [:3] with length 1 pkg=rgrpc service=storage traceid=1599a041b95dda92d758d92c5cd2dfaf

**Comment by jnweiger** [comment]
[traceid=traceid=1599a041b95dda92d758d92c5cd2dfaf.log.zip](https://github.com/owncloud/ocis/files/5495123/traceid.traceid.1599a041b95dda92d758d92c5cd2dfaf.log.zip)
