### ISSUE TITLE
OIDC middleware panics when IDP cert invalid

### ISSUE THREAD

**Issue by wkloucek** [owncloud/ocis#8672]
## Describe the bug
The OIDC middleware panics when the IDP has a invalid certificate

## Steps to reproduce
1. have a IDP with invalid certificate
2. try to use eg. Webfinger

## Expected behavior

Have  a log in the backend that the cert is not valid.

## Actual behavior

Panic + stacktrace:

```
2024/03/15 07:16:56 http: panic serving 10.96.6.13:56472: runtime error: invalid memory address or nil pointer dereference
goroutine 1181 [running]:
net/http.(*conn).serve.func1()
	net/http/server.go:1898 +0xbe
panic({0x41759c0?, 0x621e270?})
	runtime/panic.go:770 +0x132
github.com/coreos/go-oidc/v3/oidc.(*Provider).UserInfo(0x47205a0?, {0x47205a0?, 0xc0015bca20?}, {0x46fe5e0?, 0xc001580780?})
	github.com/coreos/go-oidc/v3@v3.9.0/oidc/oidc.go:322 +0x58
github.com/owncloud/ocis/v2/ocis-pkg/middleware.OidcAuth.func2.1({0x471afc0, 0xc001580720}, 0xc0006819e0)
	github.com/owncloud/ocis/v2/ocis-pkg/middleware/oidc.go:67 +0x279
net/http.HandlerFunc.ServeHTTP(0x4713dc8?, {0x471afc0?, 0xc001580720?}, 0xc000735da0?)
	net/http/server.go:2166 +0x29
github.com/riandyrn/otelchi.traceware.ServeHTTP({{0x0, 0x0}, {0x470d668, 0xc000b844b0}, {0x4717f80, 0xc001b84d08}, {0x46fb128, 0xc001b9ef80}, {0x4718b50, 0xc000d8d740}, ...}, ...)
	github.com/riandyrn/otelchi@v0.5.1/middleware.go:151 +0x699
github.com/owncloud/ocis/v2/services/webfinger/pkg/server/http.Server.Version.func16.1({0x4713dc8, 0xc00037c460}, 0xc0006818c0)
	github.com/owncloud/ocis/v2/ocis-pkg/middleware/version.go:18 +0xfd
net/http.HandlerFunc.ServeHTTP(0x43e9820?, {0x4713dc8?, 0xc00037c460?}, 0x16?)
	net/http/server.go:2166 +0x29
github.com/owncloud/ocis/v2/ocis-pkg/middleware.Secure.func1({0x4713dc8, 0xc00037c460}, 0xc0006818c0)
	github.com/owncloud/ocis/v2/ocis-pkg/middleware/header.go:57 +0x324
net/http.HandlerFunc.ServeHTTP(0xc001b56960?, {0x4713dc8?, 0xc00037c460?}, 0xc0006818c0?)
	net/http/server.go:2166 +0x29
github.com/go-chi/cors.(*Cors).Handler-fm.(*Cors).Handler.func1({0x4713dc8, 0xc00037c460}, 0xc0006818c0)
	github.com/go-chi/cors@v1.2.1/cors.go:228 +0x17e
net/http.HandlerFunc.ServeHTTP(0x43e9820?, {0x4713dc8?, 0xc00037c460?}, 0xd?)
	net/http/server.go:2166 +0x29
github.com/owncloud/ocis/v2/ocis-pkg/middleware.NoCache.func1({0x4713dc8, 0xc00037c460}, 0xc0006818c0)
	github.com/owncloud/ocis/v2/ocis-pkg/middleware/header.go:20 +0x322
net/http.HandlerFunc.ServeHTTP(0x15bc930?, {0x4713dc8?, 0xc00037c460?}, 0x4718190?)
	net/http/server.go:2166 +0x29
github.com/owncloud/ocis/v2/ocis-pkg/middleware.TraceContext.func1({0x4713dc8, 0xc00037c460}, 0xc0006817a0)
	github.com/owncloud/ocis/v2/ocis-pkg/middleware/tracing.go:19 +0x168
net/http.HandlerFunc.ServeHTTP(0x47205a0?, {0x4713dc8?, 0xc00037c460?}, 0x3d9b078?)
	net/http/server.go:2166 +0x29
github.com/go-chi/chi/v5/middleware.RequestID.func1({0x4713dc8, 0xc00037c460}, 0xc000681680)
	github.com/go-chi/chi/v5@v5.0.12/middleware/request_id.go:76 +0x20e
net/http.HandlerFunc.ServeHTTP(0xc000681680?, {0x4713dc8?, 0xc00037c460?}, 0x0?)
	net/http/server.go:2166 +0x29
github.com/go-chi/chi/v5/middleware.RealIP.func1({0x4713dc8, 0xc00037c460}, 0xc000681680)
	github.com/go-chi/chi/v5@v5.0.12/middleware/realip.go:36 +0x95
net/http.HandlerFunc.ServeHTTP(0x47205d8?, {0x4713dc8?, 0xc00037c460?}, 0x6221890?)
	net/http/server.go:2166 +0x29
github.com/go-chi/chi/v5.(*Mux).ServeHTTP(0xc000d8d740, {0x4713dc8, 0xc00037c460}, 0xc000680ea0)
	github.com/go-chi/chi/v5@v5.0.12/mux.go:90 +0x2ee
net/http.serverHandler.ServeHTTP({0xc0015bc840?}, {0x4713dc8?, 0xc00037c460?}, 0x6?)
	net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc000e88240, {0x47205a0, 0xc000726d80})
	net/http/server.go:2039 +0x5e8
created by net/http.(*Server).Serve in goroutine 97
	net/http/server.go:3285 +0x4b4
```

## Setup

oCIS 5.0.0-rc.6 in Kubernetes, in this case using the Webfinger.

## Additional context

Raised before in https://chat.owncloud.com/channel/ocis-internal?msg=5QnYcohAsvrqJBLes

**Comment by butonic** [comment]
Is WEBFINGER_INSECURE or OCIS_INSECURE set to true?

I think we need to retry fetching the userinfo when an error occurs:
```diff
diff --git a/ocis-pkg/middleware/oidc.go b/ocis-pkg/middleware/oidc.go
index d66c2213e5..f26ba1f46f 100644
--- a/ocis-pkg/middleware/oidc.go
+++ b/ocis-pkg/middleware/oidc.go
@@ -56,6 +56,7 @@ func OidcAuth(opts ...Option) func(http.Handler) http.Handler {
                                        var err error
                                        provider, err = providerFunc()
                                        if err != nil {
+                                               getProviderOnce = sync.Once{}
                                                return
                                        }
                                })
```

**Comment by wkloucek** [comment]
> Is WEBFINGER_INSECURE or OCIS_INSECURE set to true?

no, because I didn't expect the certificate to be invalid.

**Comment by butonic** [comment]
ok, creating a PR to fix this.
