### ISSUE TITLE
[stable] nightly failure on stable 5.0 on e2e tests

### ISSUE THREAD

**Issue by S-Panta** [owncloud/ocis#9170]
```feature
  And "Alice" navigates to the projects space page
    And "Alice" navigates to the project space "team.1"
    And "Alice" uploads the following resources via drag-n-drop
      │ resource       │
      │ simple.pdf     │
      │ testavatar.jpg │
    ✖ failed
      locator.click: Timeout 30000ms exceeded.
      =========================== logs ===========================
      waiting for locator('#close-upload-info-btn')
      ============================================================
          at Object.dropUploadFiles (/drone/src/webTestRunner/tests/e2e/support/objects/app-files/resource/actions.ts:580:45)
          at async Resource.dropUpload (/drone/src/webTestRunner/tests/e2e/support/objects/app-files/resource/index.ts:39:5)
          at async World.<anonymous> (/drone/src/webTestRunner/tests/e2e/cucumber/steps/ui/resources.ts:716:5)
    And "Alice" creates a public link for the space with password "%public%" using the sidebar panel
```
The nightly fails on uploading via drag-n-drop step
Failure build: https://drone.owncloud.com/owncloud/ocis/34983/66/9

**Comment by PrajwolAmatya** [comment]
Fixed with PRs https://github.com/owncloud/web/pull/10910 and https://github.com/owncloud/ocis/pull/9175. So, closing this issue.
