### ISSUE TITLE
user cannot login to ocis when using ocis-keycloak setup 

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#9258]
e2e tests with ocis-keycloak began to fail

Builds:
- https://drone.owncloud.com/owncloud/web/44753/14/15
- https://drone.owncloud.com/owncloud/web/44751/14/15
- https://drone.owncloud.com/owncloud/web/44749/14/15

```feature
1) Scenario: Alice can share this weeks meal plan with all parents (attempt 2) # tests/e2e/cucumber/features/journeys/kindergarten.feature:21
   ✔ Before # tests/e2e/cucumber/environment/index.ts:44
   ✖ Given "Admin" creates following users using API # tests/e2e/cucumber/steps/api.ts:7
       | id    |
       | Alice |
       | Brian |
       | Carol |
       locator.waitFor: Timeout 30000ms exceeded.
       =========================== logs ===========================
       waiting for locator('#web-content') to be visible
       ============================================================
           at getTokenFromLogin (/var/www/owncloud/web/tests/e2e/support/utils/tokenHelper.ts:29:59)
           at async initializeUser (/var/www/owncloud/web/tests/e2e/support/api/keycloak/user.ts:83:10)
           at async createUser (/var/www/owncloud/web/tests/e2e/support/api/keycloak/user.ts:56:3)
           at async Object.createUser (/var/www/owncloud/web/tests/e2e/support/api/provision/user.ts:18:12)
           at async World.<anonymous> (/var/www/owncloud/web/tests/e2e/cucumber/steps/api.ts:14:7)
```

ocis log:

```bash
{"level":"error","service":"proxy","error":"not found","time":"2024-05-27T00:56:31Z","message":"Error setting up libregraph client."}
{"level":"error","service":"proxy","error":"not found","time":"2024-05-27T00:56:31Z","message":"Autoprovisioning user failed"}
{"level":"error","service":"proxy","error":"not found","time":"2024-05-27T00:56:31Z","message":"Error setting up libregraph client."}
{"level":"error","service":"proxy","error":"not found","time":"2024-05-27T00:56:31Z","message":"Autoprovisioning user failed"}
{"level":"error","service":"proxy","error":"not found","time":"2024-05-27T00:57:01Z","message":"Error setting up libregraph client"}
{"level":"error","service":"proxy","error":"not found","userid":"c2e39992-2bd2-4da1-8d6c-ca3b6bd4b74b","claims":{"allowed-origins":["https://ocis:9200"],"aud":"account","auth_time":1716771387,"azp":"web","email":"admin@example.org","email_verified":true,"exp":1716771987,"family_name":"Admin","given_name":"Admin","iat":1716771387,"iss":"https://keycloak:8443/realms/oCIS","jti":"7637b315-8d82-4afe-a803-58596707114c","name":"Admin Admin","preferred_username":"admin","resource_access":{"account":{"roles":["manage-account","manage-account-links","view-profile"]}},"roles":["offline_access","uma_authorization","ocisAdmin"],"scope":"openid email profile","session_state":"785fecc7-6d20-4a1c-88c1-8fc49b1da25d","sid":"785fecc7-6d20-4a1c-88c1-8fc49b1da25d","sub":"389845cd-65b9-47fc-b723-ba75940bcbd7","typ":"Bearer"},"time":"2024-05-27T00:57:01Z","message":"Failed to update autoprovisioned user"}
```
- checked with ocis-commit 5f831c0b4735bd3cbb4d7ab049133e6480f70672 ocis-keycloak works fine :white_check_mark:
- started failing from ocis commit 7b47d558373c5030f6fc8a66def1af4de8b39ae5 ❌ 
   Found related changes in PR https://github.com/owncloud/ocis/pull/9149

**Comment by saw-jan** [comment]
CI: online office e2e tests pipeline is happy (https://drone.owncloud.com/owncloud/web/44770/13/19)
