### ISSUE TITLE
ocis crashed: `invalid memory address or nil pointer dereference`

### ISSUE THREAD

**Issue by saw-jan** [owncloud/ocis#9673]
oCIS crashed twice in web ci pipeline.

builds:
- https://drone.owncloud.com/owncloud/web/46039/12/8
- https://drone.owncloud.com/owncloud/web/46033/11/6

ocis commit: https://github.com/owncloud/ocis/commit/c7a3ec2ed0fce86166a44ab6c769661b73546342
```go
+ ./ocis server
2024/07/23 06:31:22 INFO memory is not limited, skipping package=github.com/KimMachineGun/automemlimit/memlimit
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xa8 pc=0xf1c4c2]

goroutine 33 [running]:
github.com/go-micro/plugins/v4/store/nats-js-kv.(*natsStore).WatchAll(0x6a6e8a0?, {0x354b8c8?, 0x8?}, {0x0, 0x0, 0x0})
	/var/www/owncloud/web/repo_ocis/vendor/github.com/go-micro/plugins/v4/store/nats-js-kv/nats.go:344 +0xa2
github.com/owncloud/ocis/v2/ocis-pkg/natsjsregistry.NewWatcher(0xc000ad2ea0)
	/var/www/owncloud/web/repo_ocis/ocis-pkg/natsjsregistry/watcher.go:29 +0x65
github.com/owncloud/ocis/v2/ocis-pkg/natsjsregistry.(*storeregistry).Watch(0x64?, {0xc00080eb40?, 0x3572ae9?, 0x18?})
	/var/www/owncloud/web/repo_ocis/ocis-pkg/natsjsregistry/registry.go:136 +0x13
go-micro.dev/v4/registry/cache.(*cache).run(0xc000ad2f30, {0x3572ae9, 0x18})
	/var/www/owncloud/web/repo_ocis/vendor/go-micro.dev/v4/registry/cache/cache.go:348 +0x1f9
created by go-micro.dev/v4/registry/cache.(*cache).get in goroutine 1
	/var/www/owncloud/web/repo_ocis/vendor/go-micro.dev/v4/registry/cache/cache.go:186 +0x2e5
```

**Comment by kobergj** [comment]
Issue with nats-js store. Will file a fix today.
